### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by 0mniscient** [rauenzi/BetterDiscordAddons#1]
This issue still hasn't affected the stable build as of now but in Canary there's an update to the css of the text area which prevents your plugin from showing up at all. If you fix it on Canary asap then when that update roles out to Stable build then it will already be fixed.

**Comment by rauenzi** [comment]
Just ran this myself in canary, should be all good. Thanks for pointing it out!

**Comment by rauenzi** [comment]
I lied, this only make it show up, there is some other issues apparently _facepalm_

**Comment by rauenzi** [comment]
As of right now Canary is using some sort of internal update for the message that will only update if I type a key after BFR has been applied. I have tried simulating this in the console using `trigger()` as well as the native `dispatchEvent()`. I also tried the `change` event, but nothing seems to update the internal structure so the message before the formatting is what is actually sent. It seems the devs don't want people to programmatically change the `val()` of the textarea. I'll continue looking into this.

**Comment by rauenzi** [comment]
Turns out they were using a native input listener, so this has been addressed. Thank you @0mniscient

**Comment by 0mniscient** [comment]
made this shit clean boi
![2017-07-21_23-40-46](https://user-images.githubusercontent.com/17326479/28489084-6ed5cad0-6e6e-11e7-94eb-8698a366be5f.gif)

**Comment by rauenzi** [comment]
That looks real nice there! Having it connected to the main chat and the border is nice. Hopefully you don't run into anymore errors though. I wonder if your theme works with some of the settings like hover vs. click, or swapping right side to left side. You should give the settings a test ;) @0mniscient
