### ISSUE TITLE
Minified React Error

### ISSUE THREAD

**Issue by Waterspark63** [rauenzi/BetterDiscordAddons#100]
When I try to open a dm or a server, discord crashes, and when I check the console, this error greets me:
![image](https://user-images.githubusercontent.com/23124229/56382785-0addaa80-61cd-11e9-949c-2f8d16b6a287.png)
Any idea if its local or global? I tried reinstalling bd, didn't work, so I tried pulling plugins, and got down to these: The Library Plugin, ReplySystem.

**Comment by rauenzi** [comment]
Is it when you click them or only when you hover them?

**Comment by Waterspark63** [comment]
When I click, like if I close and open discord, it opens on the store/news thingy, and if I click any dm, or server, it crashes immediately.

**Comment by rauenzi** [comment]
ah I see you are on canary, there are changes in canary that I have not fixed for yet.

**Comment by Waterspark63** [comment]
Alright, I'll just put them in another folder till it's fixed then.

**Comment by SLASHLogin** [comment]
Today it occured to me on stable:
Release Channel: stable, Build Number: 35997, os: "Windows"
https://pastebin.com/UqPWzLRv

**Comment by rauenzi** [comment]
This has been fixed.
