### ISSUE TITLE
AccountDetailsPlus when already update

### ISSUE THREAD

**Issue by orblazer** [rauenzi/BetterDiscordAddons#101]
Hello,

I have update AccountDetailsPlus to 0.1.4 and now when launch discord i have message for update the plugin.
I have try delete and re download but this is same.

Thanks.

**Comment by rauenzi** [comment]
Sounds like you have a duplicate version of the plugin in your plugins folder.

**Comment by orblazer** [comment]
I have check and no i don't have duplicate version of the plugin.

This is my plugin folder :
![Screenshot_20190423_095723](https://user-images.githubusercontent.com/1344792/56564411-36d2a480-65ae-11e9-929d-821b5dab80ec.png)

**Comment by rauenzi** [comment]
Follow these steps:
1. Delete the plugin and corresponding config file
2. Close Discord fully
3. Download the plugin and place in folder
4. Start Discord and see if the issue persists

**Comment by orblazer** [comment]
Ok, i am stupid, if you look the folder i have `AccountDetailsPlus` and `ccountDetailsPlus`. Sorry.
