### ISSUE TITLE
ReplySystem prevents launch

### ISSUE THREAD

**Issue by Technetium1** [rauenzi/BetterDiscordAddons#102]
Repeatable with a clean install of Discord stable and BBD

**Comment by ashishkotnala29** [comment]
I confirm the above issue. Discord crashes as soon as you open some chat page like DM or any text channel. With the plugin disabled, no issues.

**Comment by joshuah345** [comment]
Relaunch discord and check for updates, the newest version seems to have fixed it (0.0.9)

**Comment by ashishkotnala29** [comment]
Yes, fixed with the update. Issue may be closed. Thanks!
