### ISSUE TITLE
[Bug] [EmojiUtilities] Favourites Disappear with Custom Emotes

### ISSUE THREAD

**Issue by McCovican** [rauenzi/BetterDiscordAddons#111]
Since the latest update, it seems that the Favourites list of EmojiUtilities will disappear completely if you add an emote to the list that is not part of the inbuilt Discord set. I deleted my "EmojiUtilities.config.json" file entirely after Discord's latest update, and whenever I add a custom emote to the list (or restore my old config), the entire Favourites list disappears from the emote picker. It'll show the "Favourites" title only above the "Frequently Used" list instead. Behaviour returns to normal after removing custom emotes from the favourites list. Screenshots attached. Using the most recent version of the stable desktop Discord branch. I have no custom CSS or themes that affect the emote picker.

![Before adding custom emote](https://x.brutix.uk/e7e7a2.png)
![After adding custom emote, blobthink](https://x.brutix.uk/d3e612.png)

**Comment by SnakeATWAR** [comment]
This is also effecting me.

**Comment by nerdorican** [comment]
The same problem, but deleting the json doesn't help. Running on Ubuntu Mate.

**Comment by McCovican** [comment]
To clarify, I wasn't suggesting that deleting the JSON file fixed the issue going forwards - it only returns you to a default state (which has the "Frequently Used" list show its title correctly). Adding a custom emote to the favourites list again after that still causes it to fail.

**Comment by pupnewfster** [comment]
I messed around with it some (and also looked at previous commits to this repo), and it *seems* changing `flatten()` on this [line](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/EmojiUtilities/EmojiUtilities.plugin.js#L384) to `flat()` fixes it.

**Comment by nerdorican** [comment]
> I messed around with it some (and also looked at previous commits to this repo), and it _seems_ changing `flatten()` on this [line](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/EmojiUtilities/EmojiUtilities.plugin.js#L384) to `flat()` fixes it.

this worked, thank you

**Comment by mayassi** [comment]
> 
> 
> I messed around with it some (and also looked at previous commits to this repo), and it _seems_ changing `flatten()` on this [line](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/EmojiUtilities/EmojiUtilities.plugin.js#L384) to `flat()` fixes it.

thx a lot my dude, this fixed the whole script.
