### ISSUE TITLE
[Bug] [EmoteSearch] All emotes disappear after hovering an emote

### ISSUE THREAD

**Issue by D-Dragon13** [rauenzi/BetterDiscordAddons#117]
The EmoteSearch plugin stop working correctly a few days ago.
After searching for emotes, most of the emotes get loaded but after a few seconds all of them disappear and you can't choose anything anymore.

Here is the error log from the DevTool Console.

If you need more information I'll gladly provide them.

```
e10ac9ed94e024f778d9.js:49 Error: Unexpected null element
    at e.exports (e10ac9ed94e024f778d9.js:26)
    at u.t.calculatePositionStyle (e10ac9ed94e024f778d9.js:49)
    at u.c.componentDidMount (e10ac9ed94e024f778d9.js:49)
    at fo (e10ac9ed94e024f778d9.js:75)
    at lo (e10ac9ed94e024f778d9.js:75)
    at co (e10ac9ed94e024f778d9.js:75)
    at Pa (e10ac9ed94e024f778d9.js:75)
    at Object.enqueueSetState (e10ac9ed94e024f778d9.js:75)
    at r.g.setState (e10ac9ed94e024f778d9.js:57)
    at r.i.toggleShow (e10ac9ed94e024f778d9.js:45)
    at e10ac9ed94e024f778d9.js:45
    at e10ac9ed94e024f778d9.js:33
    at i (e10ac9ed94e024f778d9.js:49)
e.(anonymous function) @ e10ac9ed94e024f778d9.js:49
aa @ e10ac9ed94e024f778d9.js:75
n.callback @ e10ac9ed94e024f778d9.js:75
ii @ e10ac9ed94e024f778d9.js:75
ri @ e10ac9ed94e024f778d9.js:75
fo @ e10ac9ed94e024f778d9.js:75
lo @ e10ac9ed94e024f778d9.js:75
co @ e10ac9ed94e024f778d9.js:75
Pa @ e10ac9ed94e024f778d9.js:75
enqueueSetState @ e10ac9ed94e024f778d9.js:75
g.setState @ e10ac9ed94e024f778d9.js:57
i.toggleShow @ e10ac9ed94e024f778d9.js:45
(anonymous) @ e10ac9ed94e024f778d9.js:45
(anonymous) @ e10ac9ed94e024f778d9.js:33
i @ e10ac9ed94e024f778d9.js:49
setTimeout (async)
(anonymous) @ e10ac9ed94e024f778d9.js:49
t.start @ e10ac9ed94e024f778d9.js:33
i.show @ e10ac9ed94e024f778d9.js:45
t.handleMouseEnter @ e10ac9ed94e024f778d9.js:45
(anonymous) @ e10ac9ed94e024f778d9.js:75
f @ e10ac9ed94e024f778d9.js:75
(anonymous) @ e10ac9ed94e024f778d9.js:75
I @ e10ac9ed94e024f778d9.js:75
C @ e10ac9ed94e024f778d9.js:75
L @ e10ac9ed94e024f778d9.js:75
O @ e10ac9ed94e024f778d9.js:75
P @ e10ac9ed94e024f778d9.js:75
Sn @ e10ac9ed94e024f778d9.js:75
ho @ e10ac9ed94e024f778d9.js:75
Ge @ e10ac9ed94e024f778d9.js:75
Cn @ e10ac9ed94e024f778d9.js:75
i @ e10ac9ed94e024f778d9.js:49
e10ac9ed94e024f778d9.js:26 

Uncaught Error: Unexpected null element
    at e.exports (e10ac9ed94e024f778d9.js:26)
    at u.t.calculatePositionStyle (e10ac9ed94e024f778d9.js:49)
    at u.c.componentDidMount (e10ac9ed94e024f778d9.js:49)
    at fo (e10ac9ed94e024f778d9.js:75)
    at lo (e10ac9ed94e024f778d9.js:75)
    at co (e10ac9ed94e024f778d9.js:75)
    at Pa (e10ac9ed94e024f778d9.js:75)
    at Object.enqueueSetState (e10ac9ed94e024f778d9.js:75)
    at r.g.setState (e10ac9ed94e024f778d9.js:57)
    at r.i.toggleShow (e10ac9ed94e024f778d9.js:45)
    at e10ac9ed94e024f778d9.js:45
    at e10ac9ed94e024f778d9.js:33
    at i (e10ac9ed94e024f778d9.js:49)
```

**Comment by rauenzi** [comment]
Can you confirm something for me? They disappear if you hover an emote, otherwise they stay?

**Comment by D-Dragon13** [comment]
Confirmed, emotes disappear on hover

**Comment by rauenzi** [comment]
Coolio, it's a tooltip thing then. I'll fix it later hopefully

**Comment by D-Dragon13** [comment]
> Coolio, it's a tooltip thing then. I'll fix it later hopefully

Glad to hear. Thanks for all your work and I hope it's an easy fix :)

**Comment by rauenzi** [comment]
Unfortunately it seems not. I found the issue: The state isn't being set quickly enough through react's lifecycle. How to fix it? No clue honestly.

**Comment by rauenzi** [comment]
So now it looks like this is root caused by being in an adjacent react tree, so the only way to really fix this is to create a react version of this modal and place it in discord's modal stack

**Comment by D-Dragon13** [comment]
Looks like it worth the effort to fix it.
You can still choose emotes but you have to be quick and avoid hovering above them

**Comment by D-Dragon13** [comment]
It seems the issue is (somehow) resolved by now and everything works fine. Thanks for your help :)

**Comment by rauenzi** [comment]
Do the tooltips no longer show though?

**Comment by D-Dragon13** [comment]
> Do the tooltips no longer show though?

I can search for any emotes and select them without that the window is closing itself.
I don't see any "Unexpected null element" errors in the console as well.

**Comment by rauenzi** [comment]
I mean when you hover the emotes in the modal does a little box popup showing you the name?

**Comment by D-Dragon13** [comment]
> I mean when you hover the emotes in the modal does a little box popup showing you the name?

Ah no, the only work around to see the names is to select them and read it in the chat box
