### ISSUE TITLE
[Repo] [BetterRoleColors] Images on README dead

### ISSUE THREAD

**Issue by JTD420** [rauenzi/BetterDiscordAddons#118]
Would be nice to see what this plugin does before adding it to my discord... I'm aware it's not exactly the most important thing in the world but its definitely held me back from adding it even though it's very tempting...

**Comment by rauenzi** [comment]
Which README are you referring to?

**Comment by JTD420** [comment]
> Which README are you referring to?

Hey sorry didn't realise the issue wasn't linked to the plugin!
https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/BetterRoleColors

The images for that plugin are dead.

Thanks for the reply :)

**Comment by rauenzi** [comment]
Hmm I will try to remember to do this when I get home in a week.

**Comment by rauenzi** [comment]
fixed
