### ISSUE TITLE
BetterFormattingRedux not working

### ISSUE THREAD

**Issue by JTD420** [rauenzi/BetterDiscordAddons#119]
Hi,

I don't see the "BFR" plugin at all.

I'm using Enhanced Discord so I'm wondering if that's the issue and if theres any suggested fixes I could try as I'd like to use this plugin if I can!

I've already enabled the option to use BetterDiscord plugins within ED.

Thanks

**Comment by TheDarkBomber** [comment]
Delete the plugin's config and reload; see #98

**Comment by rauenzi** [comment]
Make sure you also have the corresponding library

**Comment by JTD420** [comment]
> Delete the plugin's config and reload; see #98

I tried your suggestion however it's now messed up my client... (I deleted the config.json that was in my EnhancedDiscord folder however I think you meant a different config.json? I noticed there is a config.json in the src folder for BetterFormattingRedux which I found while looking for the corresponding library that rauenzi mentioned but none of that was added to my discord...)


Anyway, I've now tried literally **everything** and I cannot get my plugins or settings menu to re-appear.

Everything from restarting my pc, uninstalling and reinstalling enhanced discord, reinjecting, deleting everything in plugins folder, deleting better discord from appdata, etc.

I can't even understand what could possibly be stopping it from loading anymore as it should be a completely new installation of ED at this point afaik.

I've tried re-adding the original config.json etc. Nothing has worked!

Interestingly, discord is still reading everything I believe as it does still load a custom theme, show the experiments tab in settings etc. It's just not showing the plugins or enhanced discord menu in the settings tab.

E,x if I edit the config.json to change from the default theme to my own theme it does correctly load my theme instead. 

What else could it possibly be?

@TheDarkBomber @rauenzi

**Comment by JTD420** [comment]
I've also checked the console and these are the only 2 errors I could find.

```
1b615292e6432bf3fb4b.js:49 [RPCServer:WSS] Error: listen EADDRINUSE 127.0.0.1:6463
e.(anonymous function) @ 1b615292e6432bf3fb4b.js:49
events.js:167 Uncaught Error: listen EADDRINUSE 127.0.0.1:6463
    at Server.setupListenHandle [as _listen2] (net.js:1286)
    at listenInCluster (net.js:1334)
    at doListen (net.js:1460)
    at process._tickCallback (internal/process/next_tick.js:63)
```
