### ISSUE TITLE
ImageToClipboard GIF support?

### ISSUE THREAD

**Issue by Drakonas** [rauenzi/BetterDiscordAddons#12]
Was wondering if GIF/Animated GIF support could be added to this. And possibly even other forms of content like WEBM video files. Not sure how this plugin could handle them though. GIF's can get quite large.

**Comment by Inve1951** [comment]
unfortunately that's way more difficult than it might appear

every image copied to clipboard via [electron's API](https://electron.atom.io/docs/api/clipboard/) automatically gets turned into a [NativeImage](https://electron.atom.io/docs/api/native-image/#supported-formats) and thus has the same restrictions

**Comment by Drakonas** [comment]
hmmm damn... thanks then. I assume this means that making the copied image keep the original URL filename is not possible either?

**Comment by Inve1951** [comment]
i don't think there's a way to associate a filename with the image in clipboard. discord chooses it.

**Comment by Drakonas** [comment]
alright thanks then.
