### ISSUE TITLE
[Bug] AccountDetailsPlus

### ISSUE THREAD

**Issue by CinnamonFreak** [rauenzi/BetterDiscordAddons#128]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
After leaving the Activity tab on startup
Or
Upon opening the Activity tab after temporarily fixing the problem as described below 

**To Reproduce**
1. Start Discord
2. Go to any server
Additional step if the plugin still works:
3. Open Activity tab

**Expected Behaviour**
It keeps working

[**Video**](https://streamable.com/887jx)
In the video I always left click and close then right click and close on the name then the same on the avatar

**Discord Version**
Stable

**Additional Context**
The issue temporarily fixes itself if the plugin is disabled then enabled

**Comment by Maximilian1271** [comment]
Can reproduce
Was about to make a report myself

**Comment by CinnamonFreak** [comment]
Update v0.1.7 fixed it
