### ISSUE TITLE
[Bug][TransientMaterial] Broken Messages Opacity

### ISSUE THREAD

**Issue by phantom745** [rauenzi/BetterDiscordAddons#129]
When editing sub settings the messages opacity does not change no matter what value.

**Comment by phantom745** [comment]
Even though I have set the opacity for the message box to 0.9 it is tied to the chat opacity

![image](https://user-images.githubusercontent.com/4897085/58924237-b6ed3d80-8708-11e9-82d0-513b8b9c95d6.png)

![image](https://user-images.githubusercontent.com/4897085/58924519-bef9ad00-8709-11e9-888f-02d69df5aa0b.png)

**Comment by MasicoreLord** [comment]
Got your answer, it's because the message box is a child or whatever has the chat opacity, children of an element, can't be more opaque than their parent.

You'll have to mess w/ background color instead, and use something like an rgba value @phantom745 
Hope that helps you.

**Comment by rauenzi** [comment]
Just going to merge this into #244
