### ISSUE TITLE
DoNotTrack v0.0.3 [Bug] 

### ISSUE THREAD

**Issue by DKnightX91** [rauenzi/BetterDiscordAddons#130]
**Which plugin/theme is this about?**
DoNotTrack v0.0.3

**Describe the Bug**
When starting from off you can nolonger move servers channels or members around.

**To Reproduce**
Turn on close fully close Discord, open Discord up and try and move a channel.

**Expected Behavior**
You lose all dragging.

**Discord Version**
Stable BD v03.2 BBD v0.217

**Comment by MasicoreLord** [comment]
I also can't drag and drop anything w/ that plugin enabled.

I didn't think that could be the source, I thought it was something w/ BandagedBD, but I didn't think it could be a plugin, as I don't have anything that messes w/ channels/categories.
