### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by ObeyBeastJj23** [rauenzi/BetterDiscordAddons#131]
**Which plugin/theme is this about?**
BFRedux

**Is your feature request related to a problem? Please describe.**
Kind of, the "Zalgo" plugin for BD/BBD does not work, and I thought it would be cool to have one built into BFRedux

**Describe the feature you'd like**
Adding Zalgo text into the BFRedux Plugin so that we don't need another plugin, which as i said above, has never actually worked for me.

**Additional context**
N/A

**Comment by rauenzi** [comment]
It worked last time I checked but you can bug that plugin developer to fix it if it indeed broken. I don't want to add Zalgo to BFRedux.
