### ISSUE TITLE
[Bug] BFRedux load() error

### ISSUE THREAD

**Issue by RelievedStudios** [rauenzi/BetterDiscordAddons#133]
---
name: BFRedux load() error
about: An error that appears when discord starts up.
title: "[Bug] BFRedux load() error"
labels: bug
assignees: ''

---

**Which plugin/theme is this about?**
BFRedux

**Describe the Bug**
When discord starts up it appears with a "Load()" error and prceeds not to work.

**To Reproduce**

**Expected Behavior**
BFRedux stops working

**Screenshots**
https://i.imgur.com/uLZrgNv.png

**Discord Version**
Stable

**Comment by SDCore** [comment]
Can confirm. The error `Cannot read property 'version' of undefined` causes it to not work.

I fixed it locally by removing `getVersion() {return config.info.version;}` on line 34 and deleting the `BetterFormattingRedux.config.json` file in the plugins folder and reloading.

I'm not 100%, but if it asks you to update, don't. It'll just bring it back to the version on the repository, and until it's updated, it'll remain broken.

**Comment by rauenzi** [comment]
In the modal that appears in the screenshot, click the error and it will log additional info to the console in discord. If someone gets me that additional info I can fix this.

**Comment by RelievedStudios** [comment]
I will get it right away

**Comment by RelievedStudios** [comment]
|screen shot|
|------|
|https://i.imgur.com/R7T4cEu.png|

**Comment by rauenzi** [comment]
Alright I think I understand the error now

**Comment by rauenzi** [comment]
Please re-open if this persists
