### ISSUE TITLE
Plugin isn't working anymore

### ISSUE THREAD

**Issue by WolfiezRawr** [rauenzi/BetterDiscordAddons#134]
So I know there was a recent update and I did in fact update it. But for some reason, it's not working. I also re-downloaded the plugin library. Is there maybe a plugin that can interfere and cause this plugin not to work? I haven't even added any other plugins to cause this issue before or after the update.

**Comment by snappyapple632** [comment]
Can confirm, role colors on users are not appearing in the voice chat.
