### ISSUE TITLE
[Bug] ReplySystem elements don't appear where they should

### ISSUE THREAD

**Issue by I4ck** [rauenzi/BetterDiscordAddons#135]
Which plugin/theme is this about?
ReplySystem v.0.0.10

Describe the Bug

Emotes along with pictures, videos and other related content is misplaced.

To Reproduce

Open Discord Settings.
Under Appearance activate Compact View.
Go to a chat room that has any element mentioned above.

Image:

![image](https://user-images.githubusercontent.com/42396618/59556725-2ea44d80-8fd0-11e9-80e3-ac72e7d0057e.png)

Image with ReplySystem disabled:

![image](https://user-images.githubusercontent.com/42396618/59556749-a07c9700-8fd0-11e9-869a-90762699ae55.png)

Discord Version
Stable

Additional Context
It's a really great video, and placing it like that is just a form of disrespect.

**Comment by rauenzi** [comment]
Hmm seems like they made changes as this was fixed once upon a time.
