### ISSUE TITLE
[Not a bug] Save original

### ISSUE THREAD

**Issue by kkthebeast** [rauenzi/BetterDiscordAddons#139]
Sorry to do this on here sir. Just an idea. A save current layout button and restore saved layout. would be great too. Thank you for all your work, Your coding skills are amazing! Thanks for all your do! :)

**Comment by rauenzi** [comment]
I honestly have no clue what this is referring to.

**Comment by kkthebeast** [comment]
Sorry brother, I am referring to the sort servers plugin. The ability to capture and restore the current server order. So we could use this old find out what the most recent servers joined were. Then revert the change. My apologies

**Comment by rauenzi** [comment]
Well there is a reset button that resets it to the way it was originally sorted.
