### ISSUE TITLE
Allow role colors for bot tags

### ISSUE THREAD

**Issue by washingdone** [rauenzi/BetterDiscordAddons#14]
An option to allow bot tags to be modified with the role color using BetterRoleColors would be fantastic

**Comment by rauenzi** [comment]
Bot tags for all locations or just in chat?

**Comment by washingdone** [comment]
All locations preferably

**Comment by rauenzi** [comment]
All I can say for now then is maybe when I have more free time

**Comment by rauenzi** [comment]
@washingdone This has been implemented
