### ISSUE TITLE
[Bug][BetterRoleColors] Mention coloring not working

### ISSUE THREAD

**Issue by DanRocs298** [rauenzi/BetterDiscordAddons#140]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
It seems that mention coloring does not work on Mac computers running Discord (The mentions turn to the default color)

**To Reproduce**
1. Go to a message conversation
2. Mention a user
3. You should see that the default color is displayed and not the role color

**Expected Behavior**
It should display the color of the user's top role over their username

**Screenshots**
![image](https://user-images.githubusercontent.com/6370453/61097070-d40fdd00-a427-11e9-9fb8-80ef5c2641fa.png)
![image](https://user-images.githubusercontent.com/6370453/61097117-fe619a80-a427-11e9-9e41-3ca6f627d19d.png)

**Discord Version**
BBD v0.2.17

**Additional Context**

**Comment by Gitykins** [comment]
Experiencing the same issue on Ubuntu 18.04. Adding !important does not work nor does it work using the default light or dark theme.

BBD v0.2.17

**Comment by Harlecorn** [comment]
It's happening on windows as well, just started doing it today.

**Comment by rauenzi** [comment]
Issues with plugins are almost never platform specific

**Comment by rauenzi** [comment]
This has been fixed in latest update.
