### ISSUE TITLE
[Issue] AccountDetailsPlus is not working (with console message)

### ISSUE THREAD

**Issue by Mirrored6** [rauenzi/BetterDiscordAddons#143]
if i enable the plugin (AccountDetailsPlus) i get an ERROR (screenshot down below) in the console of my discord client. 

![image](https://user-images.githubusercontent.com/47297746/61242035-0893d980-a745-11e9-998b-b29e14964ae2.png)

because of the error the plugin won't work on my pc for some reason.
it did work the first time i installed the plugin.

if you know how to fix pls reply, cause i really like this plugin and i want to use it again.

thanks in advance,
Mirrored 6

**Comment by Maximilian1271** [comment]
possible result of https://github.com/rauenzi/BetterDiscordAddons/issues/128

**Comment by Mirrored6** [comment]
@Maximilian1271 this is not the issue and i tried the fix you said but it had no result.
and \/
![image](https://user-images.githubusercontent.com/47297746/61389209-cab7c200-a8b8-11e9-838c-40e99be8f874.png)

**Comment by Maximilian1271** [comment]
> @Maximilian1271 this is not the issue and i tried the fix you said but it had no result.
> and /
> ![image](https://user-images.githubusercontent.com/47297746/61389209-cab7c200-a8b8-11e9-838c-40e99be8f874.png)

@Mirrored6 never claimed this was a fix lol
All i am saying is that i think this bug resulted out of this #128 implementation

I could be wrong though, i only skipped through the thing once or twice

**Comment by jamesdu031** [comment]
I have the same problem with exactly the same screenshot of the console
![image](https://user-images.githubusercontent.com/35631276/61495130-5cf2bf80-a9b8-11e9-9221-7aab55926b1c.png)

**Comment by rauenzi** [comment]
This has been fixed in latest update.
