### ISSUE TITLE
Better Role Colors - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by AaronV42** [rauenzi/BetterDiscordAddons#145]
When I Better Discord launches, the program gives me a content error reading that it couldn't be compiled because "Class extends value undefined is not a constructor or null."
I've already tried redownloading the .js as well as repairing my BD, but unfortunately, neither of those did anything and I am getting the same report both times.
It worked earlier this morning, but just out of the blue stopped working and I am not 100% sure as to why.
This plugin is one of my most favourite out of the ones I have and I really enjoy using it.
Attached is an image of the crash report itself:
![BetterRoleColors error](https://user-images.githubusercontent.com/26773436/61577416-c5ff3380-aa9b-11e9-9c00-a92c9ee4e189.PNG)

**Comment by Arashiryuu** [comment]
Duplicate issue of #144.

**Comment by AaronV42** [comment]
> Duplicate issue of #144.

thank you

**Comment by rauenzi** [comment]
I do not support DiscordSource.
