### ISSUE TITLE
New Update Broke Status Everywhere

### ISSUE THREAD

**Issue by lostdreamsaa** [rauenzi/BetterDiscordAddons#146]
The new update made the Status everywhere break :/. I attached some images with some dms with the plugin on and it not showing up anywhere but where discord intends it to.
![image](https://user-images.githubusercontent.com/51776085/61577772-fbf2e680-aaa0-11e9-9ac0-603ab8a2d617.png)
![image](https://user-images.githubusercontent.com/51776085/61577783-1f1d9600-aaa1-11e9-97dc-c75001e09256.png)

**Comment by williamjcm** [comment]
Screenshot of the error that appears in the console when enabling the plugin:
![image](https://user-images.githubusercontent.com/13572456/61577918-87469900-aaee-11e9-9d65-14b96cec708b.png)

**Comment by eco999** [comment]
This also breaks RadialStatus.

**Comment by rauenzi** [comment]
This has been fixed in latest update.
