### ISSUE TITLE
ImageToClipboard doesn't work on ubuntu.

### ISSUE THREAD

**Issue by Mef45** [rauenzi/BetterDiscordAddons#15]
Ubuntu 17.04, Discord Stable, ImageToClipboard v0.2.4
When i click "Copy image" in RMB menu or "Copy original" in image modal it does nothing.
Console has no errors.

There is plugin called [CopyCode](https://github.com/Finicalmist/CopyCode) which works fine for me on ubuntu.

**Comment by rauenzi** [comment]
CopyCode uses JavaScript exec copy, which can't be done for images. I am using node's built-in which in theory should be cross-platform but I will look into it.

**Comment by rauenzi** [comment]
Would you be willing to test if I had updates?

**Comment by Mef45** [comment]
Of course i'm ready to help. 
I'm on your server, think it will be easier to contact.
@Mef45#6741

**Comment by rauenzi** [comment]
Fixed
