### ISSUE TITLE
Voice Colours and typing colours not working

### ISSUE THREAD

**Issue by 1Doctor-Healer** [rauenzi/BetterDiscordAddons#150]
So originally this addon was working fine and I really liked it but at a random time of which i am unable to recall certain features ceased to work.
- The In voice chat colours no longer work
- Role headers on memebers list no longer works
- Ping colours no longer work
- Typing list at the bottom no longer works.

![2019-07-25 (3)](https://user-images.githubusercontent.com/48485065/61871870-d1a68c00-aed9-11e9-8904-fa2d13a1ce57.png)
![2019-07-25 (1)_LI](https://user-images.githubusercontent.com/48485065/61871871-d1a68c00-aed9-11e9-9298-57dda2fd348c.jpg)
![2019-07-25_LI](https://user-images.githubusercontent.com/48485065/61871872-d23f2280-aed9-11e9-9296-99dabe8fc900.jpg)

**Comment by rauenzi** [comment]
What plugin version are you on?

**Comment by 1Doctor-Healer** [comment]
V0.8.3

**Comment by 1Doctor-Healer** [comment]
Strangest thing It just reappeared for seemingly no reason i didnt click anything.  Just came back after playing a game for 3 hours

**Comment by snappyapple632** [comment]
I am getting an error on startup reading: "Could not be compiled. Class extends value undefined is not a constructor or null"

**Comment by rauenzi** [comment]
Redownload the plugin
