### ISSUE TITLE
[Bug] HideDisabledEmojis no longer works

### ISSUE THREAD

**Issue by ZachFett** [rauenzi/BetterDiscordAddons#152]
As the title says, the plugin no longer works. Disabled emotes are showing up in the emoji picker. The GitHub page's invite link to a "Zere's server" for support/updates is also invalid.

**Comment by adac7786** [comment]
life isnt the same without this plugin D:

**Comment by rauenzi** [comment]
Can you double check that the plugin no longer works?

**Comment by rauenzi** [comment]
This plugin still works, it's likely you have EmojiUtilities enabled which would break it (as that plugin is broken).
