### ISSUE TITLE
[Bug] [EmojiUtilities] No Context Menu

### ISSUE THREAD

**Issue by McCovican** [rauenzi/BetterDiscordAddons#154]
**Which plugin/theme is this about?**
EmojiUtilities

**Describe the Bug**
Context menu in emoji picker doesn't show up at all, meaning you can no longer add/remove favourite emojis.

**To Reproduce**
No special considerations.

**Expected Behavior**
Right clicking on an emoji should have the option to favourite/blacklist an emoji (or remove it from the favourite/blacklist sections)

**Screenshots**
N/A

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by pie-flavor** [comment]
Seconded

**Comment by rauenzi** [comment]
@pie-flavor the same comment I made in the other issue applies to all issues--comme ts like this do not help. Please refrain from it in the future.

**Comment by rauenzi** [comment]
Duplicate of #212
Since the plugin is totally broken, going to mark as duplicate and consolidate everything there.
