### ISSUE TITLE
[Bug]  RadialStatus

### ISSUE THREAD

**Issue by barbiehunter** [rauenzi/BetterDiscordAddons#157]
**Which plugin/theme is this about?**
RadialStatus

**Describe the Bug**
The Theme doesnt work anymore

**To Reproduce**
Install it > Enable it

**Screenshots**
https://axolotl.pics/916Nk8yP?key=bhMWpoxx9X3YeD

**Discord Version**
Stable

**Additional Context**
Works if a Player is Offline, but not by other Status

**Comment by wefalltomorrow** [comment]
Dupe: https://github.com/rauenzi/BetterDiscordAddons/issues/149

**Comment by rauenzi** [comment]
What he said ^
