### ISSUE TITLE
Role Members - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [rauenzi/BetterDiscordAddons#159]
Doesn't show everyone, only part or sometimes none.

![Discord_csiCs04IUC](https://user-images.githubusercontent.com/44043300/64370176-85c02a00-cfe3-11e9-9beb-8d6cbd51e3d0.png)

![Discord_MpeDsjfq4V](https://user-images.githubusercontent.com/44043300/64370228-a7211600-cfe3-11e9-8d41-77c9b92d932e.png)

Role Members plugin says there are 427 people with the "Verified" role as seen in the first picture; but, the second picture shows 504 people have that role, not 427.

**Comment by rauenzi** [comment]
Discord Source is an unofficial source.
