### ISSUE TITLE
[Bug] [AccountDetailsPlus] Fails to launch with "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by frankbuttolph** [rauenzi/BetterDiscordAddons#160]
**Which plugin/theme is this about?**
Account Details Plus

**Describe the Bug**
content error failing to compile

**To Reproduce**
launch discord

**Expected Behavior**
for discord to launch with addon enabled

**Screenshots**
[https://i.imgur.com/GmW5Rvs.png](url)

**Discord Version**
Bandaged BD

**Additional Context**
Just started today 9/9/2019 maybe a discord update broke it?

**Comment by Z3ROGRAV1TYx** [comment]
> Additional Context
> Just started today 9/9/2019 maybe a discord update broke it

99% sure this is what happened

**Comment by rauenzi** [comment]
100% that's what happened.

**Comment by rauenzi** [comment]
Fixed

**Comment by KaKi87** [comment]
No more error, but still nothing happens when I click on my nickname.
Thanks
