### ISSUE TITLE
[AutoPlayGIFs] doesn't play on friends list if they aren't on a mutual server]

### ISSUE THREAD

**Issue by afterlifes** [rauenzi/BetterDiscordAddons#162]
**Which plugin/theme is this about?**

AutoPlayGifs

**Describe the Bug**

AutoPlayGIF doesn't play the GIF on the friends list if they aren't on a mutual server with you

**To Reproduce**

Have someone on your friends list with a GIF as their pfp but not share a mutual server

**Expected Behavior**

The GIF should auto play but it doesn't unless you hover over it

**Screenshots**

**Discord Version**

Stable

**Additional Context**

**Comment by rauenzi** [comment]
This is an oddly specific bug, I will look into this soon

**Comment by rauenzi** [comment]
I don't have anyone on my friends list that has both an animated avatar and no mutual servers so I've been unable to reproduce.

**Comment by jordanhart0** [comment]
Oh yes, that has been an issue for me as well

**Comment by rauenzi** [comment]
This plugin has now been discontinued.
