### ISSUE TITLE
[Bug] Plugins fails to load

### ISSUE THREAD

**Issue by TurboBiscuit** [rauenzi/BetterDiscordAddons#163]
**Which plugin/theme is this about?**
Account Details Plus

**Describe the Bug**
When loading the plugin the "Content Errors" page opens with this message:
https://imgur.com/a/UbG6qOq

**To Reproduce**
Load the plugin

**Expected Behavior**
Loads the plugin with no issues

**Screenshots**
https://imgur.com/a/oNNifua

**Discord Version**
PBT

**Additional Context**
None

**Comment by rauenzi** [comment]
Duplicate of #160
