### ISSUE TITLE
[Bug] Not installing?

### ISSUE THREAD

**Issue by Padingtondoge420** [rauenzi/BetterDiscordAddons#164]
All i did was change the background on a theme i had and it didnt work so i restarted discord and it wont install anymore. I've uninstalled, repaired, installed atleast 15+ times now and i restarted my pc a few times but nothing is changing. I have a flashing discord icon in the corner of my discord window but my settings dont appear (yes im on mac)

**Comment by rauenzi** [comment]
Wrong repo?
