### ISSUE TITLE
[Bug] BetterRoleColors not coloring memberlist headers

### ISSUE THREAD

**Issue by MichalD96** [rauenzi/BetterDiscordAddons#165]
**Which plugin/theme is this about?**
BetterRoleColors v0.8.3

**Describe the Bug**
Memberlist Headers are not colored anymore, even if i turn on !important mode

**To Reproduce**
if i install the plugin, turn on coloring "Memberlist Headers" in "Module Settings", nothing happens

**Expected Behavior**
The tag for a group of people with a given role, should have the same color as the role

**Discord Version**
Stable

**Comment by Huddlect** [comment]
Could you please add a title? I wanted to report the same thing.

**Comment by MichalD96** [comment]
ach i forgot, sry
