### ISSUE TITLE
[Bug] CSS Snippets broken after latest update

### ISSUE THREAD

**Issue by Technetium1** [rauenzi/BetterDiscordAddons#166]
**Which plugin/theme is this about?**
[CSS Snippets](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Themes/Snippets/README.md)

**Describe the Bug**
Everything is broken except `Blur Email` & `Better Headers` on the user list

**To Reproduce**
1. Add CSS
2. Not everything applies

**Expected Behavior**
CSS should show like in screenshots.

**Screenshots**
N/A

**Discord Version**
Stable

**Additional Context**
Tried with and without `Normalize Classes`.

**Comment by rauenzi** [comment]
May or may not fix this at some point, I'm spread pretty thin as-is.
