### ISSUE TITLE
[Feature][StatusEverywhere] Doesn't show mobile status or match aria-labels

### ISSUE THREAD

**Issue by Huddlect** [rauenzi/BetterDiscordAddons#168]
**Which plugin/theme is this about?**
StatusEverywhere

**Describe the Bug**
The plugin doesn't show the new mobile status.
![grafik](https://user-images.githubusercontent.com/47282036/65393127-374db200-dd7d-11e9-9533-6e657155a76f.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Due to my own time management issues I am starting to offload some of my plugins starting with StausEverywhere. You can find the new maintained version by @Strencher here: https://betterdiscord.app/plugin/StatusEverywhere
