### ISSUE TITLE
[Bug] [BetterRoleColors] Plugin crashes Discord and causes others to fail to start.

### ISSUE THREAD

**Issue by RisingChops** [rauenzi/BetterDiscordAddons#169]
**Which plugin/theme is this about?**

BetterRoleColors

**Describe the Bug**

Ever since the update 2 days ago, whenever I enable BRC it crashes my discord and disables all my plugins and causes them to not work until i restard discord

**To Reproduce**

enable the plugin

**Expected Behavior**

it's suppose to enable the plugin

**Screenshots**

this shows in console after i enable the plugin https://prnt.sc/pakid5

**Discord Version**

stable

**Additional Context**

**Comment by pie-flavor** [comment]
Seconded

**Comment by Starzcraft88** [comment]
Thirded

**Comment by rauenzi** [comment]
Comments that don't contribute more information aren't helpful. If you must signify that you also see the problem consider reacting "+1" to the original issue instead.

**Comment by pie-flavor** [comment]
I suppose I could also leave some info.
- Instantly crashes when enabling it, upon reload a [window pops up](https://i.imgur.com/GI7MG3A.png) saying all the plugins that have crashed and it has to be reloaded a second time
- Plugins that do not crash: ZeresPluginLibrary, LibDiscordInternals, BetterNsfwTag, BetterFormattingRedux, BDContextMenu, Avatar Hover
- Plugins that do crash: BetterRoleColors (obviously), Citador, Discord Experiments, Double Click Edit, EmojiUtilities, ImageToClipboard, MessageUtilities, PersonalPins, QuickReact, Send Embeds, ShowHiddenChannels, SteamProfileLink

**Comment by Starzcraft88** [comment]
> I suppose I could also leave some info.
> 
> * Instantly crashes when enabling it, upon reload a [window pops up](https://i.imgur.com/GI7MG3A.png) saying all the plugins that have crashed and it has to be reloaded a second time
> * Plugins that do not crash: ZeresPluginLibrary, LibDiscordInternals, BetterNsfwTag, BetterFormattingRedux, BDContextMenu, Avatar Hover
> * Plugins that do crash: BetterRoleColors (obviously), Citador, Discord Experiments, Double Click Edit, EmojiUtilities, ImageToClipboard, MessageUtilities, PersonalPins, QuickReact, Send Embeds, ShowHiddenChannels, SteamProfileLink

it also crashes these plugins:

CharCounter
CreationDate
JoinAtDate
MessageLogger
OwnerTag
Silent Typing
BadgesEverywhere

**Comment by rauenzi** [comment]
It should "crash" every plugin that comes after BRC in the file list. In reality what is happening is the crash screen appears from BRC crashing Discord then BBD tries to load the rest of the plugins and show the start toast. But the toast causes an error because it's not expecting the crash screen then assumes the error belongs to the plugin and blames all the plugins.

**Comment by rauenzi** [comment]
Also @Starzcraft88 do not use MessageLogger, you will not receive support from me if you do. That plugin breaks not only BD's rules but also Discord privacy policy and their API/Application terms and increases your chance of being banned significantly.

Simlarly @pie-flavor sending embeds with SendEmbeds can get you banned as Discord views sending embeds from a user account as selfbotting which goes against every set of terms they have.

**Comment by Starzcraft88** [comment]
> Also @Starzcraft88 do not use MessageLogger, you will not receive support from me if you do. That plugin breaks not only BD's rules but also Discord privacy policy and their API/Application terms and increases your chance of being banned significantly.
> 
> Simlarly @pie-flavor sending embeds with SendEmbeds can get you banned as Discord views sending embeds from a user account as selfbotting which goes against every set of terms they have.

I don't use message logger for that very reason, it's just in my folder I always have it turned off.

**Comment by Harlecorn** [comment]
I'm having the same issue, made a post that was closed, hopefully this gets fixed soon, cuz it's my most utilized plugin and is a bit of a hinderance without it.

**Comment by Nindota** [comment]
I removed the config file earlier in the day, and that appeared to fix the issue, in addition to allowing BRC to run, though as of only a few minutes ago, this is no longer functioning.

**Comment by Gitykins** [comment]
Commenting out line 160 seems to restore functionality
 
`if (isUsername) retVal.props.children[0].props.style = {color: "inherit"};`

**Comment by Nindota** [comment]
> 
> 
> Commenting out line 160 seems to restore functionality
> 
> `if (isUsername) retVal.props.children[0].props.style = {color: "inherit"};`

I can second that. It does appear to fix the issue.
