### ISSUE TITLE
[Bug] BetterRoleColors crashed Discord.

### ISSUE THREAD

**Issue by Strencher** [rauenzi/BetterDiscordAddons#172]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Arashiryuu** [comment]
Update your version of the plugin, this issue was fixed already.

**Comment by Strencher** [comment]
it happened after the update. @Arashiryuu

**Comment by rauenzi** [comment]
Cannot repro
