### ISSUE TITLE
[Feature] New plugin to store discord settings

### ISSUE THREAD

**Issue by MichalD96** [rauenzi/BetterDiscordAddons#173]
**Which plugin/theme is this about?**
It is only the idea about new plugin.

**Is your feature request related to a problem? Please describe.**
Every time i login to discord, i have to go to settings -> Appearance -> and decrease chat font scaling and zoom level.

**Describe the feature you'd like**
Is it possible to make plugin, which will store this settings, and load it on discord start?

**Comment by Osyruu** [comment]
Normally when you adjust your zoom level, it saves automatically, and when you raise Discord normally it does not change.

**Comment by rauenzi** [comment]
Discord should automatically do this. If it doesn't that is a bug with Discord.
