### ISSUE TITLE
[Feature] A plugins like name ShowsInvisibleUsers

### ISSUE THREAD

**Issue by Osyruu** [rauenzi/BetterDiscordAddons#174]
**_Which plugin/theme is this about?_**
To shows invisible users on mouseover on her status, in the profile menu

**_Describe the feature you'd like_**
Just a plugin to see if users are in status invisible or not ( I don't know if is possible or not to code this )

**_Describe the feature you'd like_**
Like this: http://prntscr.com/pbg6mq or on click on a user in the list of users in the right like: http://prntscr.com/pbg8k6 but to other users.

**Comment by rauenzi** [comment]
Differentiating between offline and invisible is not possible unfortunately.
