### ISSUE TITLE
[Bug][BFRedux] Restore codeblock languages context menu

### ISSUE THREAD

**Issue by AMcilraith** [rauenzi/BetterDiscordAddons#176]
![Screenshot_2](https://user-images.githubusercontent.com/36273472/65844651-bbafb000-e2fc-11e9-94de-16a46ceb0767.png)
![Screenshot_3](https://user-images.githubusercontent.com/36273472/65844671-c79b7200-e2fc-11e9-84b8-a5dcf7f714eb.png)
![Screenshot_4](https://user-images.githubusercontent.com/36273472/65844694-d8e47e80-e2fc-11e9-935b-04d4d030b082.png)

Whenever I right-click on codeblock, it does this.

**Comment by rauenzi** [comment]
This has been temporarily disabled to avoid this issue, will be fixed when context menus are fixed.

**Comment by rauenzi** [comment]
Duplicate of #195 
Grouping these together.
