### ISSUE TITLE
[Bug] BFR not working

### ISSUE THREAD

**Issue by Strencher** [rauenzi/BetterDiscordAddons#178]
**Which plugin/theme is this about?**

BetterFormatigRedux

**Describe the Bug**

Supterscript, UpsideDown, Varied, not working, they no longer convert the characters.
**To Reproduce**

**Expected Behavior**

**Screenshots**

![bfbroken gif](https://user-images.githubusercontent.com/46447572/66395979-00140d80-e9d9-11e9-8255-84b688c57f52.gif)

**Discord Version**

Canary - 0.0.257

**Additional Context**

**Comment by rauenzi** [comment]
You seem to have lots of plugins that could interfere, also could be a canary issue.

**Comment by rauenzi** [comment]
Without testing for outside interference I cannot help.
