### ISSUE TITLE
[Feature][AutoPlayGifs] Autoplay emojis in custom statuses for the AutoPlayGifs plugin

### ISSUE THREAD

**Issue by S-B99** [rauenzi/BetterDiscordAddons#179]
**Which plugin/theme is this about?**

AutoPlayGifs
**Describe the Bug**

Animated emojis in custom statuses don't play
**To Reproduce**

Look at it
**Expected Behavior**

It works
**Screenshots**

This place
![Screenshot_20191010_162909](https://user-images.githubusercontent.com/17222512/66603907-1b1e8300-eb7b-11e9-8325-0b682e28e0ba.png)

**Discord Version**

Stable
**Additional Context**

**Comment by rauenzi** [comment]
This is a new feature by Discord, so this is an enhancement to the plugin rather than a bug.

**Comment by S-B99** [comment]
```
Object.values(webpackJsonp.push([
    [], {
        ['']: (_, e, r) => {
            e.cache = r.c
        }
    },
    [
        ['']
    ]
]).cache).find(m => m.exports && m.exports.default && m.exports.default.getCurrentUser !== void 0).exports.default.getCurrentUser().flags += 1
```
You can use this to test statuses yourself
Thanks!

![Screenshot_20191025_110446](https://user-images.githubusercontent.com/17222512/67582189-470f3c00-f717-11e9-8736-857faeeffa0a.png)

**Comment by rauenzi** [comment]
That's much much more complicated than it needs to be to enable that. There's also be some initial reports of Discord issuing warnings to those that have been using it so I'll hold off for now personally.

**Comment by S-B99** [comment]
Oh, strange. Alright thank you.
