### ISSUE TITLE
[Bug] "Hover Color" option in BetterRoleColors does not function

### ISSUE THREAD

**Issue by MithicSpirit** [rauenzi/BetterDiscordAddons#185]
**Which plugin/theme is this about?**
BetterRoleColors (specifically the option "Hover Color")

**Describe the Bug**
The "Hover Color" option in the settings does not seem to produce any difference in mentions when combined with a plugin that alters mention appearance on hover.

**To Reproduce**
1. Have the plugin installed
2. Use a theme that affects mentions on hover (I use [this one](https://github.com/codedotspectra/themes/tree/master/discorddark))
3. Enable the option "Hover Color"
4. Find a message that pings someone else, hover and observe

**Expected Behavior**
"Turning this on adjusts the color on hover to match role color, having it off defers to your theme" (option description).
I suspect that this means that if one is using a theme that affects the appearance of mentions when you hover on them, the plugin will make sure it still follows the role color (at least once it is un-hovered).

**Discord Version**
Canary

**Additional Context**
Windows 10, BD v0.3.2, BBD v0.2.17, latest Discord Canary version as of Oct 25th, 2019 (5 PM EST)

**Comment by MithicSpirit** [comment]
Update: I've looked through the code and it looks like the "problem" is that it was never actually implemented. The ID of the switch (`changeOnHover`) is never actually present in any of the code except for the config constant.

**Comment by rauenzi** [comment]
Yes I accidentally removed it as on option at some point. This means it is always active right now.
