### ISSUE TITLE
[Bug][DoNotTrack] StopProcessMonitor Freezes on game playing

### ISSUE THREAD

**Issue by TonicNoodles** [rauenzi/BetterDiscordAddons#186]
**Which plugin/theme is this about?**
Plugin: DoNotTrack
Setting: StopProcessMonitor
**Describe the Bug**
On reload, Discord playing game is stuck on playing even when the game is closed and there is no way to clear the current games played. 
**To Reproduce**

**Expected Behavior**
Never show or clear the current games and applications running.
Have a button to clear the current detected processes in case unpatching the game detection leads to game getting stuck on play.
**Screenshots**

**Discord Version**
Stable

**Comment by rauenzi** [comment]
You should be able to just disable that Discord setting, it should clear it.

**Comment by rauenzi** [comment]
Need confirmation of this, otherwise will be closing.
