### ISSUE TITLE
[Bug] [BetterRoleColors] "Account Details Options" nonfunctional

### ISSUE THREAD

**Issue by Leo40Git** [rauenzi/BetterDiscordAddons#187]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
The "Account Details Options" no longer work. Both the username and discriminator do not get colored.

**To Reproduce**
1. Enable "Account Details Options" -> "Username"
2. Select a server where you have a colored role.
3. Look at your account details.

**Expected Behavior**
The username in the account details should be colored.

**Screenshots**
![image](https://user-images.githubusercontent.com/7997354/67802877-a57c4780-fa94-11e9-90ae-dc280009d97c.png)

**Discord Version**
Stable

**Comment by Leo40Git** [comment]
Sorry to report, but those options are still nonfunctional. I did see an error message this time, however: `[BetterRoleColors] Could not get account details username and discrim`

**Comment by Leo40Git** [comment]
Fixed by https://github.com/rauenzi/BetterDiscordAddons/commit/68d7f96dac42587daaefb5a6a317070b45a2b46d! Thank you for your work, Zere.

**Comment by rauenzi** [comment]
oops meant to comment this but had to run to a meeting!

**Comment by Blizzardo1** [comment]
I want to know if this can be opened again, since Discord is no longer using discriminators. This error shows up again; however, it does still color
