### ISSUE TITLE
[Bug] Permission viewer could not be stopped

### ISSUE THREAD

**Issue by ardittristan** [rauenzi/BetterDiscordAddons#188]
**Which plugin/theme is this about?**
Permission viewer

**Describe the Bug**
When you turn off permission viewer, better discord gives the error: permission viewer could not be stopped. If you turn the plugin on again after that it creates a duplicate menu entry.

**To Reproduce**
Turn permission viewer off and then on again

**Expected Behavior**
permission viewer will turn off and then on again with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/42787508/68042271-c5994a00-fcd2-11e9-9ebb-8e2ac0be6ef1.png)
![image](https://user-images.githubusercontent.com/42787508/68042288-d053df00-fcd2-11e9-9665-1c17e83ad97e.png)

**Discord Version**
Stable

**Additional Context**
Have tried only running plugin + libraries and it still happened.

**Comment by rauenzi** [comment]
Make sure your version is up to date, I cannot reproduce either the multiple labels (something fixed long ago) or the issue with stopping.

**Comment by ardittristan** [comment]
I am on the latest version, I now also tried to download it directly from github and use that, but the issues still persists for me.

**Comment by rauenzi** [comment]
Do you have the latest version of the library as well? Perhaps you can show me the error produced in console? (`ctrl`+`shift`+`i`)

**Comment by ardittristan** [comment]
the library was the issue, apparently it hadn't auto updated via plugin repo. It works now, thanks for the help!
