### ISSUE TITLE
[Bug] ImageToClipboard incompatible with Lightys MessageLogger.V2

### ISSUE THREAD

**Issue by leumasme** [rauenzi/BetterDiscordAddons#189]
**Which plugin/theme is this about?**

ImageToClipboard 0.3.3

**Describe the Bug**

Copying deleted images that are shown with Lightys Message Logger Plugin does not work.
**To Reproduce**

Download MessageLogger.V2 by Lighty https://_lighty_.gitlab.io/bdstuff/?plugin=MessageLoggerV2
and use it together with this plugin.
Let someone send an Image and delete it. Right click the image and click Copy Image. You get the Confimation toast.
Now try to Paste the image. Your clipboard will still have the same content as before copying, the image has not been copied.
**Expected Behavior**

It should copy the image to clipboard, allowing me to paste it into discord again.
**Screenshots**

Video > https://streamable.com/780nf
**Discord Version**

Stable
**Additional Context**

Sorry if this is not something to fix on your end but on Lightys.

**Comment by rauenzi** [comment]
That's fine, I do not support message loggers and will not go out of my way to be compatible with them. BD does not condone plugins like that nor are they official plugins. Use at your own risk.
