### ISSUE TITLE
[Bug] ImageToClipboard text not aligned horizontal

### ISSUE THREAD

**Issue by jacobmix** [rauenzi/BetterDiscordAddons#191]
**Which plugin/theme is this about?**
ImageToClipboard v0.3.3

**Describe the Bug**
The "Open Original | Copy Original" is all on different lines instead of the same line.
This also cuts off some of the image if you use Better Image Popups by Orrie.

**To Reproduce**
Click on an image while having the plugin(s) installed, and enabled.

**Expected Behavior**
It to be neatly on the same line, and not cut off the image with Better Image Popups.

**Screenshots**
https://prnt.sc/q3qn2h

**Discord Version**
Stable "app-0.0.305"

**Additional Context**
Image related plugins i use:

> Better Image Popups v1.5.5 by Orrie
> CollapsibleEmbeds v2.1.1 by shtrih
> Direct Media v0.1.0 by samfun123
> ImageGallery v1.6.0 by DevilBro
> ImageToClipboard v0.3.3 by Zerebos
> ResizeX v0.1.2 by Anxeal
> ReverseImageSearch v3.4.8 by DevilBro

Full list of plugins i have installed (Few i have disabled tho):

> 0PluginLibrary.plugin.js
> 1lib_discord_internals.plugin.js
> AutoStartRichPresence.plugin.js
> AvatarIconViewer.plugin.js
> BadgesEverywhere.plugin.js
> BDContextMenu.plugin.js
> BetterEmoteSizes.plugin.js
> BetterImagePopups.plugin.js
> BetterNsfwTag.plugin.js
> BetterReplyer.plugin.js
> BetterSearchPage.plugin.js
> BotsMutualGuilds.plugin.js
> changingBackground.plugin.js
> CharCounter.plugin.js
> CheckAllPluginsButton.plugin.js
> Citador.plugin.js
> clock.plugin.js
> CollapsibleEmbeds.plugin.js
> copyCode.plugin.js
> dateViewer.plugin.js
> DeveloperUtils.plugin.js
> directMedia.plugin.js
> DiscordCakeDay.plugin.js
> discordexperiments.plugin.js
> DiscordLogger.plugin.js
> DoNotTrack.plugin.js
> EmoteBlacklistRedux.plugin.js
> emoteSorter.plugin.js
> FriendNotifications.plugin.js
> full_offline_list.plugin.js
> GuildAndFriendRemovalAlerts.plugin.js
> HorizontalCodeScroll.plugin.js
> ImageGallery.plugin.js
> ImageToClipboard.plugin.js
> KawaiiEmotes.plugin.js
> lazyload_patcher.plugin.js
> LineNumbers.plugin.js
> LineNumbersRedux.plugin.js
> localFileServer.plugin.js
> mediaSupport.plugin.js
> messageTimestamps.plugin.js
> OwnerTag.plugin.js
> PermissionsViewer.plugin.js
> PinPluginsAndThemes.plugin.js
> PluginRepo.plugin.js
> RepoControls.plugin.js
> RepoUtils.plugin.js
> ResizableCSS.plugin.js
> ResizeX.plugin.js
> restartNoMore.plugin.js
> ReverseImageSearch.plugin.js
> SendBDEmotes.plugin.js
> SendButton.plugin.js
> SendLargeMessages.plugin.js
> serverscreenshare.plugin.js
> serverTheme.plugin.js
> ShowHiddenChannels.plugin.js
> ShowImageDetails.plugin.js
> SilentTyping.plugin.js
> SpellCheck.plugin.js
> SteamProfileLink.plugin.js
> suppressmentions.plugin.js
> ThemeCustomizer.plugin.js
> ThemeRepo.plugin.js
> VoiceChatNotifications.plugin.js
>

**Comment by NightWolf1038** [comment]
```
.inner-1ilYF7 {
    display: block;
}
```

Paste that into Custom CSS

**Comment by rauenzi** [comment]
This has been fixed
