### ISSUE TITLE
[Bug] RoleMembers doesn't work anymore

### ISSUE THREAD

**Issue by Huddlect** [rauenzi/BetterDiscordAddons#192]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
The context menu entry just doesn't appear anymore.

**To Reproduce**
/

**Expected Behavior**
It should appear.

**Screenshots**
/

**Discord Version**
Stable

**Additional Context**
/

**Comment by FounderHawk** [comment]
Having this issue as well, going to attempt a downgrade and see what happens

**Comment by rauenzi** [comment]
This has been fixed
