### ISSUE TITLE
[Bug] PermissionsViewer doesn't work anymore

### ISSUE THREAD

**Issue by Huddlect** [rauenzi/BetterDiscordAddons#194]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
Doesn't appear in the context menu

**To Reproduce**
/

**Expected Behavior**
Should appear in the context menu

**Screenshots**
/

**Discord Version**
Stable

**Additional Context**
/

**Comment by oskpozn** [comment]
It doesnt work also after right click on server, channel and user and also context menu doesnt work, which is great feature. What works: Permissions tab appear after clicking on user,

**Comment by QuentinMcCarthy** [comment]
Doesn't work for me either. Can't see the permissions anywhere.

**Comment by rauenzi** [comment]
This has been fixed.
