### ISSUE TITLE
[Bug][BetterFormattingRedux] nonfunctional

### ISSUE THREAD

**Issue by BZ98** [rauenzi/BetterDiscordAddons#195]
**Which plugin/theme is this about?**
BetterFormattingRedux v2.3.7 by Zerebos

**Describe the Bug**
Additional formatting tags don't work, though the menu for the tags still does. Tags aren't placed into the message body and using the tags manually does nothing.

**Discord Version**
Stable

**Comment by xero-lib** [comment]
Same here.

**Comment by Nox13last** [comment]
16 January 2020. Still not working.

**Comment by rauenzi** [comment]
Guys I don't need multiple comments to say the same thing. If you feel you need your voice hear then react +1 to the original issue.

**Comment by xero-lib** [comment]
After Feb 3rd update, still non-functional.

**Comment by xero-lib** [comment]
Request to add the `confirmed` tag to this thread.

**Comment by rauenzi** [comment]
It's really only used by me to confirm bugs that are uncertain, this was never uncertain. But if you insist.

**Comment by xero-lib** [comment]
Works relatively well again, although when clicking an option in the popup menu, it spams a few hundred of the prefix/suffix characters in the text area.

**Comment by rauenzi** [comment]
I cannot recreate. Clicking once causes them to show up only once for me. Can you try reloading and trying it again? Is it perhaps a plugin conflict somehow?

**Comment by xero-lib** [comment]
It was a plugin conflict. I disabled everything else, and it inserts the normal amount of prefix/suffix characters. I will attempt to find which exact plugin is causing this.

**Comment by xero-lib** [comment]
The bug occurs with [SpellCheck v1.4.0 by DevilBro](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpellCheck)

**Comment by rauenzi** [comment]
Are you using the beta textarea or no? https://i.imgur.com/1kG1FYM.png

**Comment by xero-lib** [comment]
> 
> 
> Are you using the beta textarea or no? https://i.imgur.com/1kG1FYM.png

Yes, [I am](https://cdn.discordapp.com/attachments/248325175936942080/686332480500137985/unknown.png).

**Comment by rauenzi** [comment]
Alright, I'll try to work that out with him then.
