### ISSUE TITLE
[Bug] SendButton not positioned properly

### ISSUE THREAD

**Issue by Huddlect** [rauenzi/BetterDiscordAddons#197]
**Which plugin/theme is this about?**
SendButton

**Describe the Bug**
See screenshot

**To Reproduce**
/

**Expected Behavior**
It should have the same distance to the right border of the chat bar and the other items they have to each other and it should be vertically centered.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/47282036/70811038-21bcb700-1dc5-11ea-98c0-f4f0c3ce45b3.png)

**Discord Version**
Stable

**Additional Context**
Other plugins messing with the chat bar: GoogleTranslateOption, BetterFormatingRedux

**Comment by rauenzi** [comment]
Sounds like it's some conflict with the google translate plugin as it looks fine normally and the styling and functionality of SendButton has not changed.
![screenshot](https://cdn.discordapp.com/attachments/341062370627682315/655069320921088050/unknown.png)

**Comment by Huddlect** [comment]
Can you do anything about it or can the author of the translate plugin?

**Comment by rauenzi** [comment]
This should be fixed now

**Comment by Huddlect** [comment]
No, unfortunately not
