### ISSUE TITLE
[Bug] Formatting Redux doesn't work at all

### ISSUE THREAD

**Issue by LillyWho** [rauenzi/BetterDiscordAddons#198]
**Which plugin/theme is this about?**
Formatting Redux

**Describe the Bug**
Text isn't being converted via manual tagging. Clicking on formatting options in the toolbar doesn't add formatting symbols.

**To Reproduce**
Bug description says it all I think.

**Expected Behavior**
Working formatting via the symbols set in the settings, and a toolbar that inserts them into the chat box.

**Discord Version**
Stable

**Comment by williamjcm** [comment]
The plugin wasn't updated for the new WYSIWYG chatbox.

**Comment by Huddlect** [comment]
Isn't that a duplicate of #195 ?

**Comment by marcocorriero** [comment]
Same, can someone fix it? Since i used it all the time?

**Comment by rauenzi** [comment]
Yes this is a duplicate, and it will be fixed when I have time. Please be patient.
