### ISSUE TITLE
[Feature][BlurNSFW] Settings in BetterDiscord UI

### ISSUE THREAD

**Issue by QuentinMcCarthy** [rauenzi/BetterDiscordAddons#199]
**Which plugin/theme is this about?**
BlurNSFW

**Is your feature request related to a problem? Please describe.**
Having to open up the code for the plugin to edit the blur amount and duration is annoying, especially considering said edits are reset back to default every time the plugin is reinstalled or updated.

**Describe the feature you'd like**
The settings for the blur amount and duration should be in the BetterDiscord UI to allow for easy editing, this would also ensure the settings persist over reinstalls of the plugin or updates. So many other plugins have settings in the UI, this is the only plugin I've encountered where you have to edit the code to set the settings.

**Comment by rauenzi** [comment]
You don't have to edit the code for the record, it tells you to set css variables.
