### ISSUE TITLE
[Bug][ImageToClipboard] Some images wrongly declared as not copy-able.

### ISSUE THREAD

**Issue by Roadhog360** [rauenzi/BetterDiscordAddons#201]
This is related to ImageToClipboard.

It falsely deems some images as formats that cannot be copied. Webp, jpg_large, etc. These formats can be copied just fine from my browser. I think this could be solved by adding an option to turn off the format check, as this plugin was fine before it was added. Now it's done nothing but cause arbitrary restrictions.

**Comment by rauenzi** [comment]
The plugin actually wasn't able to copy webp images before, that's a limitation of electron's copy image (from their clipboard module). I could try to force it to copy it manually by putting the raw buffer on the clipboard, but that wouldn't guarantee success.

> These formats can be copied just fine from my browser.

Unfortunately your browser, and electron are very different things so they will not always have the same capabilities.

**Comment by Roadhog360** [comment]
I see, I had no idea they were copied in different ways. Is there any way I could manually turn off the restriction so I can find other formats that still work that are declared as not copy-able?

**Comment by rauenzi** [comment]
Here are the docs for Electron's clipboard module, you can see all the image related functions only accept their internal NativeImage format: https://www.electronjs.org/docs/api/clipboard#clipboardwritebufferformat-buffer-type-experimental

You can see that the NativeImage for Electron only supports `png` and `jpeg` here: https://www.electronjs.org/docs/api/native-image#supported-formats

So it seems that they are correctly labelled not copy-able unfortunately.

**Comment by rauenzi** [comment]
I tested trying to copy the raw buffers to the clipboard, tried forcing a MIME type alongside it as well, it seems none of it worked unfortunately. I will improve the png/jpeg detection for the next update though.
