### ISSUE TITLE
[Feature] [HideDisabledEmojis] Hide emoji preview in chat

### ISSUE THREAD

**Issue by dexman545** [rauenzi/BetterDiscordAddons#203]
**Which plugin/theme is this about?**
HideDisabledEmojis

**Is your feature request related to a problem? Please describe.**
With the new chat bar, emojis can be previewed in the message.
Currently, even emojis you cannot use are previewed and shown as if you can use them.

**Describe the feature you'd like**
Please make unusable emojis not preview in the chat bar, and instead be in their text format like when they are sent.

**Additional context**
![image](https://user-images.githubusercontent.com/4873274/73617507-77575800-45ed-11ea-8b3b-05dbf1afcd50.png)

**Comment by rauenzi** [comment]
I'm not 100% sure what you mean and the image provided doesn't help

**Comment by dexman545** [comment]
Discord's new chat bar lets you write out emoji, and instead of turning into :smile: they now preview the emoji, like this.* The preview will show emoji users cannot use, like gif emojis when you aren't nitro, or emojis from other servers, which the plugin already hides from the selector menu.


*
![image](https://user-images.githubusercontent.com/4873274/74109961-146a4180-4b56-11ea-80c7-1f5c303c09a1.png)

**Comment by rauenzi** [comment]
They don't even show in auto complete, so I won't be adding this
