### ISSUE TITLE
[Bug] BDContextMenu (sometimes not appearing)

### ISSUE THREAD

**Issue by MasicoreLord** [rauenzi/BetterDiscordAddons#205]
**Describe the Bug**
BDContext menu sometimes stops injecting into the settings context menu

**To Reproduce**
Not 100% sure how, as it seems to happen randomly (have to re-enable the plugin to get it back)
I guess you could reproduce it by switching channels/guilds (servers), till it no longer appears.  (it may involve visiting the user settings too, but haven't had it happen everytime I done that)
**Expected Behavior**
Appears in the settings context menu every time.

**Screenshots**
https://i.imgur.com/vO1YdRh.png

**Discord Version**
Stable 53877 (65210f2)

No console logs/errors appear when it fails to inject into the context menu or even when the plugin "crashes" (starts to fail re-injecting the bdcontextmenu)

**Comment by rauenzi** [comment]
I've been waiting to respond to see if I could recreate this and I have been unable to. Has this been continuing to occur?
