### ISSUE TITLE
Hello[

### ISSUE THREAD

**Issue by Jukisan** [rauenzi/BetterDiscordAddons#206]
**Which plugin/theme is this about?**

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

**Additional context**

**Comment by Jukisan** [comment]
**Which plugin/theme is this about?**


**Is your feature request related to a problem? Please describe.**


**Describe the feature you'd like**


**Additional context**

**Comment by rauenzi** [comment]
This has no information...
