### ISSUE TITLE
[Bug] autoplay gifs doesn't work anymore

### ISSUE THREAD

**Issue by jack652** [rauenzi/BetterDiscordAddons#207]
**Which plugin/theme is this about?** autoplaygifs
 it doesn't play gifs anymore

**Describe the Bug**
 it doesn't play gifs without having to hover over the icon anymore (even after restarting the plugin and redownloading it) and shows an error in the console when i try to start it (see screenshot)

**To Reproduce**
 just look at gifs icons

**Expected Behavior**
 gifs icons should play without having to hover over them

**Screenshots**

![Capture d’écran (4787)](https://user-images.githubusercontent.com/48365199/74185113-4d82de80-4c48-11ea-8f10-f45876610b57.png)

**Discord Version**
 stable

**Additional Context**

**Comment by jack652** [comment]
?

**Comment by Technetium1** [comment]
I can confirm this is a bug. He'll get around to fixing it @jack652
