### ISSUE TITLE
[Bug] BetterFormatRedux

### ISSUE THREAD

**Issue by Ashteroide** [rauenzi/BetterDiscordAddons#217]
BetterFormatRedux
Version 2.3.8

When loading upside down or any, it fills the outer areas of it with at least 100 & or % instead of just 4 or 5, how can I fix this in the code?
P.S. Found the real amount of % or &, it uses 872 of them all together which freezes Discord

**Comment by NotUrmom** [comment]
mine doesnt fill the outer parts at all, just on one side

**Comment by rauenzi** [comment]
This was a conflict with another plugin that should be fixed, please let me know if it's still an issue and reopen.
