### ISSUE TITLE
[Feature] [StatusMembers] see invisible members

### ISSUE THREAD

**Issue by StreamHi5** [rauenzi/BetterDiscordAddons#222]
Hello!

Is it possible to make a plugin to see "invisible" members or freinds?
or have the number of invisible members in our discord like this
https://i.imgur.com/GYUshYB.png

Ty guys for BetterDiscord!

**Comment by williamjcm** [comment]
It's not possible. The "invisible" status basically stops the client from sending presence updates to the servers, so there's no way for other clients to identify people who are invisible.

**Comment by rauenzi** [comment]
What @williamjcm said is correct, it is not possible as the information is not available.
