### ISSUE TITLE
"META was not found"

### ISSUE THREAD

**Issue by GiovanniSeradof** [rauenzi/BetterDiscordAddons#223]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
Receiving an error when putting plugin in the BD plugin folder in a "Content Errors" modal window.

**To Reproduce**
1. Download BetterFormattingRedux.plugin.js.
2. Drag file into BetterDiscord "plugins" folder with Discord client open.
3. Pop-up window appears titled "Content Errors"; view screenshot below without doing anything in Discord.
4. Plugin does not show in Plugins list in Discord, but the file is still in the plugins folder.

**Expected Behavior**
1. After dragging the "BetterFormattingRedux.plugin.js" file into the "plugins" folder in Discord, a small window in the bottom center should show something like "BetterFormattingRedux has started" and the features of the plugin should appear in their appropriate places.

**Screenshots**
https://cdn.discordapp.com/attachments/584236575777488906/702883745711259698/unknown.png

**Discord Version**
Stable 58583 (b7763a5)
BBD 0.3.4 (65bf2ab)

**Additional Context**
N/A

**Comment by rauenzi** [comment]
GitHub is having issues downloading files right now. You will need to wait for GitHub to fix itself.

**Comment by GiovanniSeradof** [comment]
> GitHub is having issues downloading files right now. You will need to wait for GitHub to fix itself.

I've been having this issue with this plugin for over a month now though. Is there another library or plugin necessary to support this one's functionality?

**Comment by rauenzi** [comment]
Getting this error means you have downloaded the file wrong.

**Comment by GiovanniSeradof** [comment]
What is the proper way of downloading the files then? I clicked the "Download" hyperlinked title on the plugin page and it went to "Just a moment while we check your browser" then it downloaded the .js file in my downloads folder.

**Comment by LerpCat** [comment]
me too, i really want this fixed, infact this was 3 years ago and still nobody has fixed it

**Comment by cybector** [comment]
> 

Not shocked , i'm working on a fix for it now for a plugin i am developing.

**Comment by rauenzi** [comment]
Running into this error means you've downloaded the plugin wrong, there is nothing wrong with the plugin.

**Comment by t1mbra** [comment]
How to get rid of this ADDON ERROR? I;ve already uninstalled everything still the error shows up after discord launched

![Image](https://github.com/user-attachments/assets/f0093d79-249f-4cd8-bc05-96b3ab422d85)
