### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheREALDownloader** [rauenzi/BetterDiscordAddons#226]
**Which plugin/theme is this about?**

HideDisabledEmojis
**Describe the Bug**

FREQUENTLY USED with a weird shadow (i'll send a screen
**To Reproduce**

HideDisabledEmojis only needs to be active, the emoji UI will put this weird set up all the time
**Expected Behavior**

To see the difference we only need to disable it and open emoji menu, it's not there anymore
**Screenshots**

![image](https://user-images.githubusercontent.com/64555536/80639097-ce8c8d80-8a61-11ea-8402-70ad1aa1fa1c.png)

**Discord Version**

**Additional Context**

I'm using a special theme that i'll paste here, both the plug-in and the theme need to be active, I hope my theme isn't broken :/

https://cdn.discordapp.com/attachments/310473536646938625/705142540734693467/02-theme.theme.css

**Comment by rauenzi** [comment]
This is the themes fault.
