### ISSUE TITLE
[Bug] BDContextMenu

### ISSUE THREAD

**Issue by Glaived** [rauenzi/BetterDiscordAddons#229]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
There are no more options in the context menu

**To Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1835170/81136584-483de300-8f5c-11ea-86eb-51eddb355abc.png)

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
This has been fixed.

**Comment by Glaived** [comment]
Same again

**Comment by Glaived** [comment]
https://github.com/rauenzi/BetterDiscordAddons/issues/236
