### ISSUE TITLE
[Bug] StatusEverywhere - Broken display

### ISSUE THREAD

**Issue by Glaived** [rauenzi/BetterDiscordAddons#230]
**Which plugin/theme is this about?**
StatusEverywhere

**Describe the Bug**
Broken display

**To Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1835170/81137013-7b34a680-8f5d-11ea-8ead-309da58fa1ee.png)

**Discord Version**
Stable

**Additional Context**

**Comment by orblazer** [comment]
That its caused by the class `wrapper-3t9DeA` on the avatar div. I search how i can fix that

**Comment by EnderBro123** [comment]
Sane issue.

**Comment by Huddlect** [comment]
d5a2440 fixed the issue for me.

**Comment by rauenzi** [comment]
Yup forgot to close the issues.
