### ISSUE TITLE
[Bug] [ZeresPluginLibrary] Compilation Error

### ISSUE THREAD

**Issue by Stig124** [rauenzi/BetterDiscordAddons#233]
**Which plugin/theme is this about?**

ZeresPluginLibrary
**Describe the Bug**

The bug is a compilation error by BD, 
`toString() radix argument must be between 2 and 36`
**To Reproduce**

I only opened my Discord the bug wasn't present before
**Expected Behavior**

That it just compiles correctly, and works
**Screenshots**

https://i.imgur.com/Pp6PnUF.png
**Discord Version**

Canary 60400
**Additional Context**

Already tried to re-inject BD, same issue

**Comment by MasicoreLord** [comment]
Known issue by the developer, be patient.  Also there's likely more issues, as it's the same update that changed the right click context menus.  Using stable in the meantime is recommended, but if they break it before then, just be patient. @Stig124

**Comment by rauenzi** [comment]
This is the wrong repository, and the issue was fixed.
