### ISSUE TITLE
[Bug] [BetterFormattingRedux] Extreme Excess of Wrappers Placed When Using Toolbar

### ISSUE THREAD

**Issue by colto1000** [rauenzi/BetterDiscordAddons#234]
**Which plugin/theme is this about?**
ImageToClipboard

**Describe the Bug**
When using the toolbar to format highlighted text (in input text box), an extreme amount of wrappers are put around the text. Instead of `it` being turned into `%%it%%`, there are at least 100 `%`s around `it`. See Screenshots for an example of this. This is consistent with any of the formatting options in the toolbar, but the popup menu when highlighting text works properly.

**To Reproduce**
Highlight some text in the input text box, move to the `^` to open the toolbar, and select any formatting option.

**Expected Behavior**
The correct number of wrappers should be placed around the text. For example, if bold-ing `test`, it should be turned into `**test**` and _**not**_ `******************test******************` (but with more `*`s).

**Screenshots**
![image](https://user-images.githubusercontent.com/33501061/82271548-ad6edc80-993d-11ea-931a-61ed19e518a4.png)

**Discord Version**
Stable

**Additional Context**
_N/A_

**Comment by rauenzi** [comment]
This is a plugin conflict that does not exist in the rewrite.

**Comment by colto1000** [comment]
> 
> 
> This is a plugin conflict that does not exist in the rewrite.

I'll have to look into this then! Seems one of my newer plugins has been making Discord laggy. Thanks, man!
