### ISSUE TITLE
Plugin doesn't work on Channels - Permission Viewer [Bug] 

### ISSUE THREAD

**Issue by AyalX** [rauenzi/BetterDiscordAddons#235]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
The plugin works but when I right click a channel it doesn't show the permission view option
I have tried to check for updates, re-adding the plugin, restart but still it doesn't work
I suspect this problems is caused by some discord UI update.

**Screenshots**
https://i.imgur.com/EBqx11F.gifv - GIF

**Discord Version**
BetterDiscord Stable Latest Version

**Comment by rauenzi** [comment]
Yep broke last night, haven't had a chance to do anything yet.

**Comment by AyalX** [comment]
Oh okay, thank you for replaying, your plugin is amazing and I hope you manage to fix this.

**Comment by rauenzi** [comment]
Now fixed
