### ISSUE TITLE
[Bug] EmoteSearch

### ISSUE THREAD

**Issue by whayn** [rauenzi/BetterDiscordAddons#237]
**Which plugin/theme is this about?**
EmoteSearch

**Describe the Bug**
The pop-up does not appairs when type /es (my emoji)

**To Reproduce**
Type is (your emoji)

**Expected Behavior**
A popup is supposed to open

**Screenshots**
![ezgif-4-bd8d070a0e9d](https://user-images.githubusercontent.com/64968114/82567854-42f8af00-9b7e-11ea-82a8-62f08d829f0d.gif)

**Discord Version**
Stable

**Additional Context**
nothing

**Comment by KeafyIsHere** [comment]
I have the same problem 😢

**Comment by rauenzi** [comment]
This is no longer valid since it was removed from BD. This will likely be integrated to the official plugin when its ready.
