### ISSUE TITLE
[Bug] EmojiUtilites Favorite/Blocklist don't work on Emojipicker

### ISSUE THREAD

**Issue by MarioLowee** [rauenzi/BetterDiscordAddons#239]
**Which plugin/theme is this about?**
EmojiUtilites v0.0.8

**Describe the Bug**
The favorite and blacklist fuctions don't work on the Emojipicker menu. When trying to add/block a emoji via the context menu, the picker menu close up and the buttons do nothing.

**To Reproduce**
To reproduce, try to add/block a emoji via the Emojipicker menu

**Expected Behavior**
It should be add/block the emoji like in the previous version

**Screenshots**

![2020-05-22_11-51-20](https://user-images.githubusercontent.com/48120340/82656079-6b86b480-9c23-11ea-8cda-9a8bf395d46d.gif)

**Discord Version**
Tested via Stable and PTB

**Additional Context**

**Comment by rauenzi** [comment]
This should be fixed with the latest version of the library,  can you confirm if that fixes it?

**Comment by MarioLowee** [comment]
It's fixed.

Thank you
