### ISSUE TITLE
[Bug] Quick mute buttons beeing duplicated

### ISSUE THREAD

**Issue by Darkissou** [rauenzi/BetterDiscordAddons#241]
**Which plugin/theme is this about?**
QuickMuteChannels

**Describe the Bug**
Buttons to mute channels are being duplicated

**To Reproduce**
It seems to appear randomly, as I didn't saw the duplicated buttons directly after I installed the plugin

**Expected Behavior**
Buttons appearing only once

**Screenshots**
![image](https://user-images.githubusercontent.com/57590802/83960283-7da15d80-a887-11ea-8c70-6afb88d76226.png)

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
I have no such plugin, I think you are looking for https://github.com/Strencher/BetterDiscordStuff
