### ISSUE TITLE
[Feature] Exclude channels/servers from BlurNSFW's action

### ISSUE THREAD

**Issue by Darkissou** [rauenzi/BetterDiscordAddons#242]
**Which plugin/theme is this about?**
BlurNSFW

**Is your feature request related to a problem? Please describe.**
It's not very convenient having to disable the plugin to not getting blurred images in X channel when you could just add a feature to exclude those channels from the blur

**Describe the feature you'd like**
Just add an option to exclude images in servers and/or channels from getting blurred

**Additional context**

**Comment by rauenzi** [comment]
You can do this now using the context menu.
