### ISSUE TITLE
[Bug][PermissionViewer] No More Permissions Menu for Voice Channels

### ISSUE THREAD

**Issue by Tibsi** [rauenzi/BetterDiscordAddons#243]
**Which plugin/theme is this about?**
PermissionViewer

**Describe the Bug**
When right clicking on a voice channel the permission menu doesn't appear anymore. It still works for text channels.

**To Reproduce**
Right click on any voice channel.

**Expected Behavior**
In the past the same Permissions menu would allow you to see the permissions for Voice channels.

**Discord Version**
Stable 61327 (dd367d1)
BBD 0.3.4 (32e6212)
Host 0.0.306
Injector 0.4.1
Windows 10 64-Bit (10.0.18363)

**Comment by AyalX** [comment]
Same issue here
