### ISSUE TITLE
[Bug][TransientMaterial] TransientMaterial is totally broken

### ISSUE THREAD

**Issue by Julaaaan** [rauenzi/BetterDiscordAddons#244]
**Which plugin/theme is this about?**

Transient Material
**Describe the Bug**

It just doesnt work, there is no transparency
**To Reproduce**

Just enable the theme
**Expected Behavior**

i expected the background to be transparent so i can see the picture that i set.
**Screenshots**

![unknown](https://user-images.githubusercontent.com/65832836/84907786-e7094380-b0b3-11ea-9be2-e6ad601f779c.png)

**Discord Version**

Stable
**Additional Context**

I really dont know what i did wrong, can you guys ploease help me and make it work? It looks so beautiful and a really want it to work

**Comment by Darkissou** [comment]
_Can I have those wallpapers?_

**Comment by Julaaaan** [comment]
right here https://i.redd.it/46qt9c4cagg11.png

**Comment by rauenzi** [comment]
It is broken, I do not know when I will get around to fixing it.

**Comment by Julaaaan** [comment]
maybe it helps to say thet i got the newest stable version,
------------------------------
Stable 62142 (4011855)
BBD 0.3.4 (32e6212)
Host 0.0.306
Injector 0.4.1
Windows 10 64-Bit (10.0.19041)

**Comment by rauenzi** [comment]
No that's entirely irrelevant, the theme itself is and has been broken.

**Comment by Julaaaan** [comment]
I wanted to ask if there are any updates, because i would really like to see this working

**Comment by rauenzi** [comment]
Discontinued
