### ISSUE TITLE
[Bug][AccountDetailsPlus] The status picker still appears when the user popout opens

### ISSUE THREAD

**Issue by DorCoMaNdO** [rauenzi/BetterDiscordAddons#245]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
The status menu appears below the user popout, often causing the popout to close when attempting to hover over it with the cursor.

**To Reproduce**
Have any of the user popout settings enabled, open the popout by clicking the username or profile picture, depending on the settings enabled.

**Expected Behavior**
I've not used the plugin before but according to the demo gif the intended behavior seems to block the status picker from showing up when the user popout is meant to show.

**Discord Version**
Stable

**Additional Context**
This also happens when I've changed the status picker settings to open the user popout instead (so left click opens the status picker as it does by default, right click, which normally does nothing, to open the popout), the status picker still opened upon right clicking despite changing `showStatusPicker` to `showUserPopout` in the `contextmenu` events, so the issue seems to be in `showUserPopout`.

**Comment by rauenzi** [comment]
Is this still an issue? Seems to work better with latest version of plugin and library.

**Comment by DorCoMaNdO** [comment]
Yeah it still is, the status menu still opens behind the user popout, and it usually still causes the popup to close. The issue still seems to be part of `showUserPopout` as switching the behavior to open the popout on right click (instead of the status picker) causes the status picker to open.
