### ISSUE TITLE
[Bug] EmojiUtilities bug

### ISSUE THREAD

**Issue by Narko4tacey** [rauenzi/BetterDiscordAddons#246]
**Which plugin/theme is this about?**

EmojiUtilities
**Describe the Bug**

When i click on Favorite Emoji it closes the emoji menu and doesn't add emoji to favorite
**To Reproduce**

**Expected Behavior**

**Screenshots**

https://gyazo.com/34af25eef8a1f7283b5f44160f38eb8c
**Discord Version**

**Additional Context**

**Comment by Glaived** [comment]
**Discord Version**
Stable

**Comment by rauenzi** [comment]
Duplicate of #239
