### ISSUE TITLE
[Bug] DoNotTrack Process Monitor Block not working anymore

### ISSUE THREAD

**Issue by LokeYourLord** [rauenzi/BetterDiscordAddons#247]
**Which plugin/theme is this about?**
DoNotTrack v.0.0.6 by Zerebos

**Describe the Bug**
The bug is easy to reproduce, the plugin is supposed to stop Discord from seeing all Processes running on your Computer and stop Sentry from collecting data, but this clearly doesn't happen anymore because when the plugin was working before, Discord did not see when I was having Games running, however now Discord again started showing me that Games are being seen by it in the "Game Activity" Tab and also in the Main Window by showing me that I can Stream the Game that is currently running.

**To Reproduce**
Install Plugin -> Enable "DoNotTrack" -> Run a Game or Custom Software added in the Game Activity List -> See Game being picked up by the Discord Sentry, showing the Game both as Streamable and being shown in the Game Activity List

**Expected Behavior**
Discord Sentry not collecting data and seeing the Processes currently running on my OS.

**Screenshots**
No Screenshots needed, I would assume so at least.

**Discord Version**
Stable 62028 (89ee84d)
BBD 0.3.4 (32e6212)
Host 0.0.306
Injector 0.4.1
Windows 10 64-Bit (10.0.18363)

**Additional Context**
None

**Comment by rauenzi** [comment]
Can you try at this out again? It seems to be blocking things here. I don't see the game pop up in the console or in the UI. Also make sure you have that setting of DNT enabled.

**Comment by Lightningblade** [comment]
Same here. Setting is enabled. Does it happen if you start discord while in a game?

**Comment by LokeYourLord** [comment]
> 
> 
> Same here. Setting is enabled. Does it happen if you start discord while in a game?

No it happens even before that.

**Comment by Lightningblade** [comment]
So it shows a game before you start a game?

**Comment by LokeYourLord** [comment]
> 
> 
> So it shows a game before you start a game?

Oh no it just shows a game even though the "Stop Process Monitor" option is enabled, no matter if the Plugin is enabled and the other option also enabled, Discord just sees my game processes anyways.

**Comment by Lightningblade** [comment]
Oh ok. For me it only happens when I start discord while a game is open. The plugin probably doesn't load and stop the process quickly enough. But it disables the process monitoring, so even if i close the game afterwards it still shows the game.

**Comment by Lightningblade** [comment]
@rauenzi Not exactly, #186 is that the event of not playing the game anymore doesn't happen since the monitoring is not working (due to plugin). My problem is that the game is found / shown in the first place.

**Comment by rauenzi** [comment]
Shown in the first place when starting Discord is not an error, Discord starts up before BD so it detects what it currently running. I can't do anything about that. So you end up stuck on playing once the plugin kicks in which is #186

**Comment by rauenzi** [comment]
@LokeYourLord @Lightningblade Any confirmation of either?

**Comment by Lightningblade** [comment]
Well, yes if you can't inject / stop the monitor at startup, then that will be the issue that I expressed in this thread.

**Comment by rauenzi** [comment]
Correct, I cannot stop it before Discord starts it, that is not something that I can fix.

**Comment by Idknothing** [comment]
Can you try add DiscordSentry.close() method in your js?
