### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Bannanna999** [rauenzi/BetterDiscordAddons#25]
Not working on the new update 
It wont appear in plugins and sometimes I get a meta error

**Comment by intrnl** [comment]
No description provided.
Why?

**Comment by Bannanna999** [comment]
accidentally pressed enter. Then I edited it

**Comment by rauenzi** [comment]
This doesn't even say which plugin

**Comment by SamTheGr8est** [comment]
More like this issue isn't working. smh

**Comment by Bannanna999** [comment]
Better Formatting Redux
