### ISSUE TITLE
[Bug] [BetterRoleColors] Crashing on Start

### ISSUE THREAD

**Issue by HenriqueGomez** [rauenzi/BetterDiscordAddons#250]
**Which plugin/theme is this about?**
Hey all! So, BetterRoleColors started crashing today. Don't know if it is related to the latest Discord updates.

**Describe the Bug**
When Discord starts and I join any server, the app crashes when it is enabled.

**To Reproduce**
For me, just enable the plugin.

**Expected Behavior**
Discord should open.

**Discord Version**
Stable

**Additional Context**
I found a solution but I wanted to report it anyway because I don't know if the way I fixed it can cause any issues.
If you go to the Plugin, comment the line `this.promises = {state: {cancelled: false}, cancel() {this.state.cancelled = true;}};`.
This should fix the issue.

**Comment by shinji257** [comment]
I came here to report this and thank you for the solution.  I'll apply this to my local copy until the dev comes up with their own fix.

**Comment by SunRaysFalls** [comment]
I can confirm the crash at start too and with the Comment Out method I managed to have it enabled and not crashing. The crash is related to the member list changed discord made with today update most likely as it was reverted back to default discord theme.

**Comment by Flamebullet** [comment]
Commenting the line this.promises = {state: {cancelled: false}, cancel() {this.state.cancelled = true;}}; does work but it will remove the color when viewing user's profile. 
The temporary fix that I found is to just disable Memberlist Headers in the module setting of the plugin. When this setting is disabled viewing the user's profile will still show the color and not crash discord

**Comment by SunRaysFalls** [comment]
> 
> 
> Commenting the line this.promises = {state: {cancelled: false}, cancel() {this.state.cancelled = true;}}; does work but it will remove the color when viewing user's profile.
> The temporary fix that I found is to just disable Memberlist Headers in the module setting of the plugin. When this setting is disabled viewing the user's profile will still show the color and not crash discord
Just wanted to edit my previous message to state the same thing lol

**Comment by HenriqueGomez** [comment]
> Commenting the line this.promises = {state: {cancelled: false}, cancel() {this.state.cancelled = true;}}; does work but it will remove the color when viewing user's profile.
> The temporary fix that I found is to just disable Memberlist Headers in the module setting of the plugin. When this setting is disabled viewing the user's profile will still show the color and not crash discord

Also worked. Thanks :)
