### ISSUE TITLE
[Bug] BetterRoleColors Crashing after downloading the plugin library

### ISSUE THREAD

**Issue by NotToBlame** [rauenzi/BetterDiscordAddons#251]
**Which plugin/theme is this about?**
Plugin: BetterRoleColors v0.8.11+ ZeresPluginLibrary v1.2.18

**Describe the Bug**
Causing Discord to crash when joining any server chat (DM's are fine)

**To Reproduce**
1. Launch Discord with only BetterRoleColors.plugin.js
2. When the "Library Missing" window appears, click Download Now
2.5 Go to friends list or a DM conversation before restarting so you don't crash immediately when doing the next step
3. Restart Discord
4. Click on any server and it will crash (Clicking on any DM conversation is fine

**Expected Behavior**
To open the Discord server I click on and to view chat messages

**Screenshots**
![RW2Cv2dXnb](https://user-images.githubusercontent.com/36744014/86128179-f091a300-bad8-11ea-97ca-ee74a5b77c2e.gif)

**Discord Version**
Stable 62531

**Additional Context**
No other plugins or themes were enabled

**Comment by DJ53118** [comment]
Hello! 

I have this issue as well and it was reported here as well [https://github.com/rauenzi/BetterDiscordAddons/issues/250], as long with that person making a similar report he also put how to fix it in his report, and I can confirm that the solution he gave fixes it.

**Comment by NotToBlame** [comment]
@DJ53118 Thank you for mentioning this, this was posted as I was collecting information for my post so didn't see it beforehand. I can confirm that this fix does so will quote it here for anyone else having this issue that may have found my report first

> **Additional Context**
> I found a solution but I wanted to report it anyway because I don't know if the way I fixed it can cause any issues.
> If you go to the Plugin, comment the line `this.promises = {state: {cancelled: false}, cancel() {this.state.cancelled = true;}};`.
> This should fix the issue.
