### ISSUE TITLE
[Bug] BetterRoleColors - Discord crash on server open.

### ISSUE THREAD

**Issue by TheTrashinger** [rauenzi/BetterDiscordAddons#252]
**Which plugin/theme is this about?**
BetterRoleColors v0.8.11 by Zerebos

**Describe the Bug**
When BetterRoleColors is activated, and i try to open a Server/Guild - Discord crashes instantly.
When the Server is already open and i active the Plugin then it does not crash instantly. The crash comes when i click on a Member in the VoiceChat and it trys to load the colors and roles.
---
I have started Discord and it automatically went to the normal Dashboard. Were it was still fine, but Discord crashes instantly if i open an Server/Guild. First i have deactivated every Plugin i have, after this Discord worked again. As next step i activated every plugin alone and discord went unstable again when BetterRoleColors was activated. 
Furthermore i deactivated every other plugin except BetterRoleColors and it still was unstable.
It seems to crash, when it loads the roles or the colors. in the VoiceChat.

**To Reproduce**
1.variant:
 Start Discord -> Make sure BetterRoleColors is activated -> Try to join a Server/Guild -> Crash.

2. variant:
 Start Discord ->  Try to join a Server/Guild -> Make sure BetterRoleColors is activated  -> Click on a User which has no Color -> Crash.

**Expected Behavior**
The Expected Behavior would be, that all users have Colors expected on there highest rank in the VoiceChat.

**Screenshots**
I made 2 short Videos to for better understanding.
1. variant: https://youtu.be/JXltMQydLUg

2. variant: https://youtu.be/3VA0HBPcDxs

**Discord Version**
Stable 62531 (624ac8f)
BBD 0.3.4 (32e6212)
Host 0.0.306
Injector 0.4.1
Windows 10 64-Bit (10.0.18363)

**Additional Context**
None ^^

**Comment by TheTrashinger** [comment]
#250 
Okay while i wrote my issue. someone already did it ;D

**Comment by iSukola** [comment]
Seconding this, same issue and same reproduction!
