### ISSUE TITLE
[Bug] AccountDetailsPlus doesn't work anymore

### ISSUE THREAD

**Issue by jack652** [rauenzi/BetterDiscordAddons#260]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
the user pannel popout doesn't appear anymore when i click on my username at the bottom

**To Reproduce**
click on your username at the bottom

**Expected Behavior**
the user pannel popout should appear

**Discord Version**
stable

**Additional Context**
worked fine yesterday

**Comment by rauenzi** [comment]
Can you tell me your version of the plugin and version of the library?
