### ISSUE TITLE
[Bug] HideDisabledEmojis not working

### ISSUE THREAD

**Issue by Joxan1337** [rauenzi/BetterDiscordAddons#262]
**Which plugin/theme is this about?**
 **HideDisabledEmojis**

**Describe the Bug**
 **Just didnt work now!**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**
**### Stable**

**Additional Context**

**Comment by rauenzi** [comment]
Are you still experiencing this? I have not been able to recreate the issue, the plugin is consistently hiding the disabled emojis in the emoji picker.
