### ISSUE TITLE
[Feature] New Addon for discord.bio

### ISSUE THREAD

**Issue by barbiehunter** [rauenzi/BetterDiscordAddons#266]
**Which plugin/theme is this about?**
New Plugin/Theme, because i think it would be nice

**Describe the feature you'd like**
Under the profile an advertisement like e.g. at Spotify and co. with the information from the Bio. Find that this can be a nice little extra feature.

**Additional context**
I got the idea, because a buddy of mine did it himself but at Powercord, and he doesn't want to do it for Betterdiscord.

**Comment by rauenzi** [comment]
Sorry, I think you're better off asking someone else to implement this. I'm actually looking to maintain *less* plugins than I am currently. Sorry about that. Perhaps you'd be better off asking someone like DevilBro (mwittrien on github).
