### ISSUE TITLE
[Other] Button does not download right file

### ISSUE THREAD

**Issue by GhostJumper** [rauenzi/BetterDiscordAddons#267]
The download Button does not download the newest BetterFormattingRedux.plugin.js file.

location | md5sum
------------ | -------------
download button | d6177937fec9cfe7fbcdb3f51641a427
file in repo | a11697169a5c4382765ed15225e115fd 

Edit: It does download the newest File, but with a different line ending.

**Comment by rauenzi** [comment]
I just downloaded them fresh and got the same md5 checksum for both matching the one you got for the download button. Are you sure GitHub didn't serve you an old version or your cache kicked in when accessing the file in repo? Or possibly accidentally downloaded the wrong file?

![Results](https://i.imgur.com/QfF6wFt.png)

**Comment by GhostJumper** [comment]
Nope. Just cleared my caches and tried again.
![Result](https://user-images.githubusercontent.com/34964243/90487785-36fb9980-e13b-11ea-8451-99b04bae1ea4.PNG)

**Comment by rauenzi** [comment]
Oh if you're obtaining it through git and not by downloading it through raw files it's possible the line endings are changed. Have you tried doing a diff between the files?

**Comment by GhostJumper** [comment]
Yeah. The only difference seem to be the line endings.
The Download Button downloads in LF.
The Repo Cloning downloads in CR LF.

Loading the LF file wont work with Discord (for me).

---

img explanation:
I first converted everything to CR LF, then to LF

![Capture](https://user-images.githubusercontent.com/34964243/90519943-fd418780-e168-11ea-92c8-a5402b65f4e0.jpg)

**Comment by rauenzi** [comment]
What happens when you try to load the LF file? I just tested it myself and had no issues.

**Comment by GhostJumper** [comment]
Seems to have been a problem on my side. There is no issue loading the file after I tried again.
Sry for wasting your time, but now we know that there seems to be a change in line endings. XD
