### ISSUE TITLE
[Feature][StatusEverywhere] Option to turn off in DMs

### ISSUE THREAD

**Issue by Arkteus** [rauenzi/BetterDiscordAddons#270]
Hi Zerebos,
Already a huge thank you for all your plugins !!
Could you add an option on "StatusEverywhere" to turn off status in DMs as they are not very useful there unlike multi-chat on a server ...
It may not be technically easy to develop, so don't worry too much about it first.
Yours truly,
Arteus # 7681

**Comment by rauenzi** [comment]
I have considered this and decided not to implement this.
