### ISSUE TITLE
Won't load in Discord [Stable]

### ISSUE THREAD

**Issue by AstreaI** [rauenzi/BetterDiscordAddons#271]
AccountDetailsPlus [Tried on a Mac AND Windows Device]

When enabled within Discord, it does not appear to work when you press your Profile Picture/Username - Both options tried. It also won't change to your nickname in a server, if it was enabled. Tried to re-install, no difference.

**Comment by rauenzi** [comment]
This has been fixed with the latest version of the library (there was an update just now). Please test with that and let me know!
