### ISSUE TITLE
[Bug] PermissionsViewer don't show name roles (users) in channel window

### ISSUE THREAD

**Issue by kirill-782** [rauenzi/BetterDiscordAddons#272]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
If open window view permission, then instead role name show role id. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7936957/90135114-da832d80-dd7a-11ea-9409-95381d6f397a.png)

**Discord Version**
Stable

**Comment by da19961** [comment]
Confirmed bug... I was gonna report it myself actually...

**Comment by kirill-782** [comment]
I did a little investigation by mistake. The problem turned out to be a changed type of overridden rights. Previously, it was "role", but now there is a number 0

**Comment by kirill-782** [comment]
> Confirmed bug... I was gonna report it myself actually...

https://github.com/kirill-782/BetterDiscordAddons/blob/master/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

try this version

**Comment by da19961** [comment]
Yeah it seems that changing "displayRoles[role].type" from "role" to "0" fixes the problem

**Comment by enescglyn** [comment]
Able to reproduce. Also when looking at channel's permission it shows the role's id without a color instead of their name with a color

**Comment by Drflash55** [comment]
This issue has been fixed with the new update.
![image](https://user-images.githubusercontent.com/13694448/90360559-0a0b9180-e02a-11ea-95d3-ff6cc663a5bf.png)

**Comment by rauenzi** [comment]
Oops this should have been auto-closed.
