### ISSUE TITLE
[Feature] Unset Overwrites added to Category/Channel Modals

### ISSUE THREAD

**Issue by TheDireMaster** [rauenzi/BetterDiscordAddons#274]
**Which plugin/theme is this about?**
PermissionViewer

**Describe the feature you'd like**
I'd like unset overwrite permissions to show up in category/channel modals

Example below:
![image](https://user-images.githubusercontent.com/10566724/90649473-aef8bb00-e232-11ea-9358-b1e87fe412fd.png)

**Comment by rauenzi** [comment]
Why? Anything that isn't explicitly allowed or denied is unset. So by knowing what is allowed/denied, you know what is unset.
