### ISSUE TITLE
[Bug] ServerSearch plugin has to be reloaded on discord startup

### ISSUE THREAD

**Issue by tinbolw** [rauenzi/BetterDiscordAddons#275]
I am on PTB Version 65385 on MacOS. Whenever Discord starts up, the ServerSearch plugin is not there and it has to be disabled and reenabled before it is visible.

On startup: 
![before discord reload](https://user-images.githubusercontent.com/36116384/90650971-5c4adf00-e1f1-11ea-8ae1-d97e9f087667.jpeg)
: 

After mod is reloaded:
![after reload](https://user-images.githubusercontent.com/36116384/90651012-6c62be80-e1f1-11ea-8566-f379fc31c113.jpeg)

**Comment by rauenzi** [comment]
This is due to it not properly checking/waiting for the elements to be in place.

**Comment by rauenzi** [comment]
This has been fixed in the latest version!

**Comment by HawksAreNeat** [comment]
Sorry for reopening this but it now loads up then instantly "crashes" causing you to disable then re-enable it again
