### ISSUE TITLE
[Bug] [BetterRoleColors] App crashes when viewing user info in Lightcord

### ISSUE THREAD

**Issue by asorel1942** [rauenzi/BetterDiscordAddons#276]
**Which plugin/theme is this about?**

BetterRoleColors
**Describe the Bug**

While the plugin is activated, clicking on a user's profile picture or name to see user info in a server results in the program crashing.
**To Reproduce**

Run Lightcord, enable plugin, attempt to click on user's name or profile picture in server. 
**Expected Behavior**

For the server info popup to appear.
**Screenshots**

**Discord Version**

Lightcord, BD, and OS versions are as follows:
![image](https://user-images.githubusercontent.com/33983895/90711648-42e87800-e26f-11ea-8b9e-9d93151fcaa0.png)

**Additional Context**

**Comment by asorel1942** [comment]
After going into the settings for the plugin, disabling the Username and Enable Fallback options under the Popout section removed the issue; leaving Nickname on did not cause crashes. Whatever the issue is, it has to do with how colored usernames are being treated in the popout specifically.

**Comment by rauenzi** [comment]
This issue is known, however do note that I do not support lightcord and in the future will not accept issues from those using it.

**Comment by rauenzi** [comment]
This crash should be fixed (although the colors are not), can you confirm?

**Comment by asorel1942** [comment]
I can confirm, yes. No longer crashing with those options enabled, although colors don't appear, as you say.

**Comment by asorel1942** [comment]
Crash issue appears to be happening again when the color username option is enabled.

**Comment by rauenzi** [comment]
This does not seem to be happening on BD, is it happening for you still?

**Comment by asorel1942** [comment]
Cannot say for certain as I have the option turned off, and am not currently able to turn it on due to being unable to change settings for the plugin. Once your plugin library updates and I am able to modify settings, I will let you know.

**Comment by rauenzi** [comment]
The update for the library was just pushed out

**Comment by asorel1942** [comment]
Didn't register on my end until just now, apologies. The new version of the plugin is giving me a (This plugin might be dangerous (Account Stealer/Virus) error, which I believe is an  issue with Lightcord and not your plugin.

**Comment by asorel1942** [comment]
Update pushed through, as of version 1.2.27 of the plugin library and 0.8.13 of BetterRoleColors, activating the color username option still results in a crash of Lightcord upon activating the user popup for a user with an unchanged nickname.

**Comment by rauenzi** [comment]
Are you on Discord stable? Popouts are currently working for me just fine. ![image](https://user-images.githubusercontent.com/6865942/101224552-ef067100-365c-11eb-81e1-c5a827077000.png)

**Comment by asorel1942** [comment]
As I said in the OP, I'm using Lightcord.

**Comment by rauenzi** [comment]
As far as I can tell, Lightcord still pulls in Discord's code, but I don't know what stream. This seems to be a Lightcord only issue anyways and Lightcord is not a supported platform for my plugins.
