### ISSUE TITLE
[Bug] [Role Members] Switching to "Mark As Read" option after some time

### ISSUE THREAD

**Issue by BitCrack** [rauenzi/BetterDiscordAddons#279]
**Which plugin/theme is this about?**
Role Members

**Describe the Bug**
After opening the context menu by right-clicking on the server's name and hovering over "Role Members" option or any role in that tab, after some time it'll change back to "Mark As Read" and close the "Role Members" tab.

**To Reproduce**
Same as above.

**Expected Behavior**
Of course it shouldn't switch back to "Mark As Read" without me even hovering above that option.

**Screenshots**
https://gyazo.com/0b9d53b9e3f3a0f3bd59d0d096fc9168

**Discord Version**
PTB

**Additional Context**
I use "MaterialCons v1.0" and "MinimalCord v1.0.0"

**Comment by rauenzi** [comment]
It seems to only happen on occasion and I'm uncertain what causes it.

**Comment by rauenzi** [comment]
This should be fixed with the newer versions of the library.
