### ISSUE TITLE
[Bug] EmojiUtilities - Some favorites don't display

### ISSUE THREAD

**Issue by The24Kings** [rauenzi/BetterDiscordAddons#280]
**Which plugin/theme is this about?**
EmojiUtilities
**Describe the Bug**
When favoriting an emoji they sometimes don't display properly in the list, even though they are favorited. Un-favoriting them and adding them back makes the emoji at the end not display and break

**To Reproduce**
Adding emojis until they dont display properly (i have 36)

**Expected Behavior**
keeps adding new favorite emojis to the list

**Screenshots**
<img width="150" alt="Annotation 2020-08-25 230239" src="https://user-images.githubusercontent.com/8305099/91266967-2c3a9900-e727-11ea-954e-4b40dd3c3c0b.png">
<img width="221" alt="Annotation 2020-08-25 230240" src="https://user-images.githubusercontent.com/8305099/91266969-2cd32f80-e727-11ea-8473-a4901c19c2b9.png">

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Are you still seeing this? I am not having this issue.
