### ISSUE TITLE
[Bug][RoleMembers] not working on mentions

### ISSUE THREAD

**Issue by VerstreuteSeele** [rauenzi/BetterDiscordAddons#281]
Either im too dumb or it doesnt work at all with mentions. tried hovering over it, clicking... restarted discord a few times, reloaded / redownloaded the plugin too. Nothing seems to work

**Comment by rauenzi** [comment]
Yes it is known not working with mentions right now.

**Comment by marshallgwentz** [comment]
Is there a fix or workaround for this issue yet? I'm presently attempting to cross-reference member lists between a few different servers and was hoping to use this plugin. If there's also another way to use the plugin, that would suffice.

**Comment by rauenzi** [comment]
Why was this closed?
