### ISSUE TITLE
Permissionsviewer v0.1.15 Permissions in popups do disappear after opened once 

### ISSUE THREAD

**Issue by MrZeroLord** [rauenzi/BetterDiscordAddons#286]
Permissionsviewer v0.1.15

Permissions in popups do disappear after opened once. needs a reload to see it once more  

Just click on someone's profile 

Please do fix it so it shows it always.

https://cdn.discordapp.com/attachments/543620396369444905/757660576855097454/n57cPhq7F5.gif

Stable 67364 BBD 0.3.5

**Comment by MrZeroLord** [comment]
Second bug:
https://cdn.discordapp.com/attachments/543620396369444905/757705182489608262/ArFXS0FBPA.gif
just switches what I am hovering over randomly.... idk y

**Comment by rauenzi** [comment]
As for the first issue, can you try disabling all other plugins affecting that popout and reloading, then see if the issue persists?

**Comment by MrZeroLord** [comment]
Its StatusEverywhere v0.4.9 by you

regarding the second bug, its also occurring without other plugins

**Comment by MrZeroLord** [comment]
> As for the first issue, can you try disabling all other plugins affecting that popout and reloading, then see if the issue persists?

Are you able to reproduce now with StatusEverywhere?

**Comment by rauenzi** [comment]
No I am not, I use StatusEverywhere and PermissionsViewer normally and have still not run into that issue. I would guess it's a conflict with the plugins by DevilBro due to conflicting patches.

**Comment by rauenzi** [comment]
Have you tried testing this without the other plugins?
