### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kibbenkat** [rauenzi/BetterDiscordAddons#288]
**Which plugin/theme is this about?**

SendButton
**Describe the Bug**

will not send current message
**To Reproduce**

type message, click the button, will not send
**Expected Behavior**

type message, click button, sends message
**Screenshots**

**Discord Version**

Stable
**Additional Context**

**Comment by rauenzi** [comment]
I just tested SendButton and it is still working for me. Can you try turning off other plugins that affect textarea/messages, then reloading?
