### ISSUE TITLE
[Bug] AutoPlayGifs doesn't auto play gifs anymore

### ISSUE THREAD

**Issue by hydratioNx99** [rauenzi/BetterDiscordAddons#289]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
Status, Emotes (and Emote List) aswell as Gifs just don't get auto played...

**To Reproduce**
Idk it just doesn't work

**Expected Behavior**
Auto play the gifs

**Screenshots**
/

**Discord Version**
Stable 68558 (3fa0352)
BBD 0.3.5
Host 0.0.308
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Additional Context**
/

**Comment by rauenzi** [comment]
Why did you close this just to open a new one?

**Comment by hydratioNx99** [comment]
cuz I thought I could change the label
