### ISSUE TITLE
[Suggestion] Server "Files"

### ISSUE THREAD

**Issue by ThaumicTom** [rauenzi/BetterDiscordAddons#29]
Hey rauenzi,
I have a suggestion for you. Can you make this plugin real (see link) or connect it with this one?
[https://i.imgur.com/iUAMWe4.png](url)

Thanks!

**Comment by Inve1951** [comment]
the closest to it atm is [DevilBro's Server Folders](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders) ;)

**Comment by rauenzi** [comment]
Yeah I would bug DevilBro to make his more like that. Those folders are a hell of an undertaking because discord's code interferes heavily

**Comment by xstefen** [comment]
theres also [Guild Separators by Zerthox](https://github.com/Zerthox/BetterDiscord-Plugins/blob/master/plugins/GuildSeparators.plugin.js) to handle the "Dividers" look

**Comment by ThaumicTom** [comment]
DevilBro's Server Folders bug for me but thanks.
