### ISSUE TITLE
[Bug] AutoPlayGifs doesn't work

### ISSUE THREAD

**Issue by hydratioNx99** [rauenzi/BetterDiscordAddons#290]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
Status, Emotes (and Emote List) aswell as Chat gifs just don't get auto played...

**To Reproduce**
Idk it just doesn't work

**Expected Behavior**
Auto play the gifs

**Screenshots**
/

**Discord Version**
Stable 68558 (3fa0352)
BBD 0.3.5
Host 0.0.308
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Additional Context**
/

**Comment by rauenzi** [comment]
Do you have this enabled in settings?

![image](https://i.imgur.com/2hGMqpf.png)

**Comment by lamo-git** [comment]
I am having this issue aswell but I do not have the option that you listed.
I have these instead.
![image](https://user-images.githubusercontent.com/66180365/104674734-23d10380-56b2-11eb-815f-e3c791a18936.png)

**Comment by rauenzi** [comment]
The screenshot I gave was a Discord setting, not a setting of the plugin.

**Comment by rauenzi** [comment]
Fixed by https://github.com/rauenzi/BetterDiscordAddons/pull/441
