### ISSUE TITLE
[Bug] AccountDetailsPlus v0.10 causes PermissionsViewer v0.1.16 to break

### ISSUE THREAD

**Issue by upauld4** [rauenzi/BetterDiscordAddons#291]
**Which plugin/theme is this about?**
AccountDetailsPlus v0.10 (ADP), PermissionsViewer v0.1.16 (PV)

**Describe the Bug**
After launching discord and BBD starting the aforementioned plugins, PV will work as expected, unless the ADP user popout is opened before first clicking on a server member, opening the popout showing the roles and permissions of that member. Not doing so will result in the permissions no longer being shown in any popouts, though PV will still function, allowing the user view permissions through the menus.

**To Reproduce**
Have ADP and PV installed and enabled, then launch discord, go to a server and open the ADP popout.

**Discord Version**
Stable 68815 (fdca70b)
Windows 10 64-Bit (10.0.18362)
BBD 0.3.5

**Comment by rauenzi** [comment]
I am able to reproduce this, but not sure why this is the case off the top of my head.

**Comment by JadeMin** [comment]
i have same issue.

**Comment by JadeMin** [comment]
The problem is solved. Thank you
