### ISSUE TITLE
[Bug] [ImageToClipBoarrd] Will not compile

### ISSUE THREAD

**Issue by asorel1942** [rauenzi/BetterDiscordAddons#292]
Receive "window.require is not a function" error.
![image](https://user-images.githubusercontent.com/33983895/96360706-51c39d80-10ed-11eb-9980-49ea3d43b5e9.png)

**Comment by rauenzi** [comment]
This is a Lightcord-specific issue and I do not support Lightcord.

**Comment by mirsella** [comment]
@asorel1942 replace window.require with require in the js file
