### ISSUE TITLE
[Bug] [BRC] "not working"

### ISSUE THREAD

**Issue by FalconNotFound** [rauenzi/BetterDiscordAddons#293]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
It just doesn't work, I tried reinstalling the plugin, i restarted discord, reinstalled BetterDiscord and it still just doesn't work.

**To Reproduce**

**Expected Behavior**
I expected it to work as normally as it would.

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by cmd430** [comment]
can't reproduce on my end, everything working fine

**Comment by rauenzi** [comment]
Can you provide additional information such as errors, Discord version number, BD version, other plugins, etc?

**Comment by lugia19** [comment]
I'm also experiencing this.
Discord version is Stable 72338 (0d4212c), BBD is 0.3.5

It's very inconsistent - I've had it work sometimes, then not work once I restart discord. 
I've also tried disabling every single other plugin, and that did nothing. I also tried reinstalling BBD.
