### ISSUE TITLE
[Bug] [HideMutedServers] Completely broken

### ISSUE THREAD

**Issue by DaxterOnyx** [rauenzi/BetterDiscordAddons#294]
**Which plugin/theme is this about?**

Hide Muted servers v1.1.1

**Describe the Bug**

The servers is remove of folders

**To Reproduce**

Set muted servers in a folders and hide muted servers, the muted servers become hided but is set a the top of the server list.

**Expected Behavior**

Stay in the folders where is set them

**Screenshots**

**Discord Version**

Stable

**Additional Context**

I use Better folders v2.2.2 by Zerthos

**Comment by JulioA8** [comment]
Any chance of this getting fixed anytime soon? Or has it become to complicated?

**Comment by rauenzi** [comment]
This plugin has been discontinued
