### ISSUE TITLE
[Bug] Favorites not showing up

### ISSUE THREAD

**Issue by ec3566** [rauenzi/BetterDiscordAddons#295]
**Which plugin/theme is this about?**
EmojiUtilities

**Describe the Bug**
Not working, Favorites does not show up in emoji menu.
The emojis remain favorited, as right clicking a previously favorited emoji, it shows "Remove Favorite" instead of "Favorite Emoji"
Blacklisted emojis still show up at the bottom

**To Reproduce**
Start Discord

**Expected Behavior**
Favorites show up

**Screenshots**

![image](https://user-images.githubusercontent.com/47432136/97374773-8672ea00-188f-11eb-8bd7-7ace59bfd974.png)

**Discord Version**
Stable

**Comment by stephiebunnie** [comment]
Im having the same issue as well, I tried to restart also couldnt get my favorite list to return

**Comment by cmd430** [comment]
also having the same issue, Seems the emoji picker isnt using the `getCategories()` method returned by `DiscordModules.EmojiStore` so the patch works but doesn't actually show up in the picker, i.e when running `ZeresPluginLibrary.DiscordModules.EmojiStore.getByCategory("favorites")` in the console the favorites are shown

**Comment by rauenzi** [comment]
Can you try reloading your Discord client? It seems to be working again for me.

**Comment by cmd430** [comment]
> 
> 
> Can you try reloading your Discord client? It seems to be working again for me.

Confirmed working again for me

**Comment by ec3566** [comment]
Seems to be working again
Was not working previously even after reloading though

**Comment by cmd430** [comment]
This issue has come back for me again

**Comment by ec3566** [comment]
Yup, its back

**Comment by stephiebunnie** [comment]
Ya fav list gone again

**Comment by rauenzi** [comment]
It looks like Discord is in the process of adding their own favorite system internally, so calling the category "favorites" was conflicting with their internal stuff.
