### ISSUE TITLE
Role color not working in voice channel [Bug] 

### ISSUE THREAD

**Issue by Masono03** [rauenzi/BetterDiscordAddons#298]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
As the ticket title says colors are not working in voice channel.

**To Reproduce**
just run discord canary newest version

**Expected Behavior**
role colors working everywhere except voice channel

**Screenshots**
(dunno how to enter one but i have one i can show on discord)

**Discord Version**
Canary newest version

**Additional Context**
only noticed today but i think it was already not working yesterday

**Comment by Huddlect** [comment]
Also occurs in the stable version for me

**Comment by Ace4415** [comment]
Mine isn`t working too

**Comment by Twizzer** [comment]
Confirmed.

**Comment by rauenzi** [comment]
These types of comments are not helpful.
