### ISSUE TITLE
[Issue] Wrong Margin in TransientMaterial

### ISSUE THREAD

**Issue by ThaumicTom** [rauenzi/BetterDiscordAddons#30]
Hey, it's me, the second time.
In you theme "TransientMaterial" there is an margin error.
As it can be seen here: https://i.imgur.com/EVxUwjc.png, over the Name is only just a small margin, while beneath, the margin is acceptable. Please do the upper margin so long as the bottom does.

**Comment by rauenzi** [comment]
To be honest, I completely forgot about TM. Did you set the variable --tm-solo to 1?

**Comment by ThaumicTom** [comment]
Nope. I downloaded it and it happened, Im only into css not js, so I don't know stuff.

**Comment by rauenzi** [comment]
that *is* a css thing. put this into customcss

```css
:root {
 --tm-solo: 1;
}
```

**Comment by ThaumicTom** [comment]
Okay, thanks.
