### ISSUE TITLE
[Bug] BetterRoleColor don't work in voice

### ISSUE THREAD

**Issue by tofonek** [rauenzi/BetterDiscordAddons#300]
**Which plugin/theme is this about?**
BetterRoleColor

**Describe the Bug**
Color don't work in voice

**To Reproduce**

**Expected Behavior**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/46074679/98937930-6c6c1500-24e7-11eb-9db8-ecd6cad14c87.png)

**Discord Version**
Latest

**Additional Context**

**Comment by rauenzi** [comment]
Duplicate of #298
