### ISSUE TITLE
[Bug] BetterRoleColors Broken for voice channels

### ISSUE THREAD

**Issue by randomman254** [rauenzi/BetterDiscordAddons#301]
**Which plugin/theme is this about?**
BetterRoleColors v0.8.12

**Describe the Bug**
BetterRoleColors no longer shows role colors for users in a voice channel, with or without the `!important` tag.

**To Reproduce**
View any voice channel with users in it.

**Expected Behavior**
The users names should match their highest role's color.

**Screenshots**
[Example](https://i.imgur.com/tiJ1Wis.png)

**Discord Version**
Stable

**Comment by Leo40Git** [comment]
Related console error:
![here](https://media.discordapp.net/attachments/333116127204999171/776726887169916928/unknown.png)
Discord recently changed the channel list's classes, that probably caused this.

**Comment by cojicos** [comment]
From what I've seen (I tried to look and see if I could fix it myself but I couldn't so...) this thing doesn't work: 
`const VoiceUser = WebpackModules.find(m => typeof(m) === "function" && m.List);`

I don't know how the BetterDiscord API works so I couldn't figure out more. Hope this helps.

**Comment by Strencher** [comment]
A fix for that is available in [#302 ]

**Comment by rauenzi** [comment]
The above was merged
