### ISSUE TITLE
[Bug] Hide Muted Servers not working on Canary

### ISSUE THREAD

**Issue by yannawrgit** [rauenzi/BetterDiscordAddons#304]
**Which plugin/theme is this about?**
HideMutedServers

**Describe the Bug**
The Button is there, but it doesn't hide servers anymore.

**To Reproduce**
Install the plugin, make sure it's enabled, right click on a server, click on hide muted servers, nothing happens.

**Expected Behavior**
It should hide muted servers, but it doesn't.

**Screenshots**
none

**Discord Version**
Canary

**Additional Context**
none

**Comment by rauenzi** [comment]
This no longer works on stable either. Duplicate of #294
