### ISSUE TITLE
[Bug]BetterRoleColors "typing..." and profile menu is not colored 

### ISSUE THREAD

**Issue by Alpha-Beta1** [rauenzi/BetterDiscordAddons#306]
**Which plugin/theme is this about?**
 BetterRoleColors

**Describe the Bug**
 I just notice. I deleted plugin (for download again) is not colored anyway 

**Expected Behavior**
 Umm... Colored typing bar?..

**Screenshots**
 A clear and concise description of what you expected to happen
![ss](https://user-images.githubusercontent.com/75079250/100355129-46c02f00-3002-11eb-8086-56e27230b694.png)
![betterrolecolors](https://user-images.githubusercontent.com/75079250/100466342-d092f980-30e1-11eb-809c-84f12f00e22a.png)

**Discord Version**
 Stable 72376 (75e36d9)
BBD 0.3.5
Host 0.0.308
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Additional Context**
 -

**Comment by rauenzi** [comment]
Both of those are currently working for me. The only thing not colored currently are the user modals. Is this still an issue for you?
