### ISSUE TITLE
[Bug] Doesn't Works

### ISSUE THREAD

**Issue by Jakemessi** [rauenzi/BetterDiscordAddons#307]
**Which plugin/theme is this about?**
Better Formating Redux

**Describe the Bug**
It doesn't work I click on one of the options and nothing happens

**To Reproduce**
Click on one of the ways to format the writing

**Expected Behavior**
.... Format the text
**Screenshots**

**Discord Version**
stable

**Additional Context**

**Comment by rauenzi** [comment]
Duplicate of #311
