### ISSUE TITLE
[Bug] BetterRoleColors opening settings returns error

### ISSUE THREAD

**Issue by Gibbu** [rauenzi/BetterDiscordAddons#308]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
When opening the settings menu it returns only the collapsible headers.

**To Reproduce**
Click the settings button on BetterRoleColors

**Expected Behavior**
Return settings options

**Screenshots**
![gif](https://user-images.githubusercontent.com/20338746/100406647-792d6300-30ba-11eb-9cb2-2f47c502dc99.gif)
![image](https://user-images.githubusercontent.com/20338746/100406648-79c5f980-30ba-11eb-8f45-76e973e3c13c.png)

**Discord Version**
Stable 72376 (75e36d9)
BBD 0.3.5
Host 0.0.307
Injector 0.6.2
Windows 10 64-Bit (10.0.19041)

**Comment by Alpha-Beta1** [comment]
confirmed. my BetterRoleColors plugin has this error too

**Comment by asorel1942** [comment]
I have the same issue.

**Comment by rauenzi** [comment]
This will be fixed when the library updates

**Comment by Gibbu** [comment]
Indeed it has. Cheers mate.
