### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by itaintraf** [rauenzi/BetterDiscordAddons#309]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
On click of formatting option, nothing is produced

**To Reproduce**
Click on any of the formatting options

**Expected Behavior**
Text should be surrounded with the respective formatting option

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Duplicate of #311 (duping forward due to convo)
