### ISSUE TITLE
BetterFormattingRedux doesnt work 

### ISSUE THREAD

**Issue by Fxrmer** [rauenzi/BetterDiscordAddons#311]
**Which plugin/theme is this about?**
BetterFormatingRedux

**Describe the Bug**
When I highlight the text and click on one of the options, nothing happens.

**Expected Behavior**
It's expected to do what the formatting is. For example, put it in a codeblock when I highlight the text I want to put in the code block and press on the codeblock option.

**Discord Version**
Stable

**Comment by irockdude554** [comment]
same thing is happening to me on both of my machines

**Comment by HououinKyouma89** [comment]
same here.
works when typing wrappers manually.

PLUS:
first 2 options in settings not available.
![Xq5MywtLLN](https://user-images.githubusercontent.com/38899076/100516288-15bb3800-3183-11eb-8b14-f2b584e3549f.gif)

**Comment by Fxrmer** [comment]
> same here.
> works when typing wrappers manually.
> 
> PLUS:
> first 2 options in settings not available.
> ![Xq5MywtLLN](https://user-images.githubusercontent.com/38899076/100516288-15bb3800-3183-11eb-8b14-f2b584e3549f.gif)

typing the wrappers manually doesn’t seem to work for me.

**Comment by HououinKyouma89** [comment]
oh sorry, my mistake, ill make an own issue then later.

**Comment by Fxrmer** [comment]
> oh sorry, my mistake, ill make an own issue then later.



> same here.
> works when typing wrappers manually.
> 
> PLUS:
> first 2 options in settings not available.
> ![Xq5MywtLLN](https://user-images.githubusercontent.com/38899076/100516288-15bb3800-3183-11eb-8b14-f2b584e3549f.gif)



> same thing is happening to me on both of my machines

It works now. The first two settings still don't show up but I don't mind lol.

**Comment by rauenzi** [comment]
Is the issue with the buttons still occurring? I am unable to reproduce.

**Comment by enzomtpYT** [comment]
The bug is still occuring
