### ISSUE TITLE
[Bug] The plugins sometimes working sometimes not

### ISSUE THREAD

**Issue by hoaaiww** [rauenzi/BetterDiscordAddons#312]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
The plugin isn't working. It isnt showing up

**To Reproduce**
-

**Expected Behavior**
-

**Screenshots**
https://gyazo.com/1ea7ec1ebe0aa5cb6d837ae6c64afa7d

**Discord Version**
Stable

**Additional Context**
-

**Comment by rauenzi** [comment]
The issue with not showing up has been fixed in the latest commit.
