### ISSUE TITLE
BetterFormattingRedux Toolbar & Settings

### ISSUE THREAD

**Issue by HououinKyouma89** [rauenzi/BetterDiscordAddons#313]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
- Toolbar buttons dont work; it works when manually typing the wrapper.
- first 2 options in settings not available.

**Screenshots**
![M4MbquX27r](https://user-images.githubusercontent.com/38899076/100519323-7c4a5100-3197-11eb-9e6e-76dc8064de70.gif)

![Xq5MywtLLN](https://user-images.githubusercontent.com/38899076/100519313-73597f80-3197-11eb-9cb2-67eece02ee29.gif)

**Discord Version**
Stable

**Comment by BrokenHaiku** [comment]
Confirmed here too. 

Reinstalled Discord (29 Sept version).
Reinstalled Bandaged DB
Turned off all other plugins and deleted the config file for BetterFormattingRedux

Problem persists.

**Comment by rauenzi** [comment]
Settings issue is known and will be fixed with the next library update. However I cannot recreate the issue when clicking the buttons. Can you get a screenshot of any errors in the console?
