### ISSUE TITLE
[Bug] Zoom scaling is reset when clicking the welcome button using ZeresPluginLibrary on LightCord

### ISSUE THREAD

**Issue by AkechiShiro** [rauenzi/BetterDiscordAddons#315]
**Which plugin/theme is this about?**
[ZeresPluginLibrary](https://betterdiscordlibrary.com/plugins/ZeresPluginLibrary
)

**Describe the Bug**
**[On LightCord](https://github.com/Lightcord/Lightcord) (a Linux unofficial client not the Discord official client)**, when this plugin is enabled, clicking a specific type of button reset the zoom/scaling of the interface.

**To Reproduce**
Go to 'Parameters'
Click on 'Appearance'
Change "Zoom level" to "150%" using slider.
Click on "Welcome button" or any DM tchat you have.
See error.

**Expected Behavior**
Does not change the scaling of the interface, the scaling setting should be preserved when the plugin is active.

Disabling the plugin does indeed solve the issue meaning it's not a bug within the client but related to the plugin.

**Screenshots**

**Discord Version**
```
Initializing Lightcord.
Version: 0.0.308
releaseChannel: stable
commit: 55208fd4d39f04605353b516dcb097a8ea01ce63
```

**Additional Context**
Here is the [issue I reported](https://github.com/Lightcord/Lightcord/issues/116) on the official GitHub or LightCord.

**Comment by rauenzi** [comment]
Confirmed with some others that this is not being reproduced on Discord + BetterDiscord. Lightcord is not a supported platform for my plugins or library.

In the future, when submitting issues about the library, please use the correct repository (https://github.com/rauenzi/BDPluginLibrary)

**Comment by AkechiShiro** [comment]
Okay I understand, I apologize for not having submitted to the correct repo. I used the [link for reporting an issue](https://github.com/rauenzi/BetterDiscordAddons/issues) on the [official website of plugins for BetterDiscord](https://betterdiscordlibrary.com/plugins/ZeresPluginLibrary) maybe it links to the wrong page? Is it written anywhere that you only support the official Discord client or is there a list of supported Discord clients ? (maybe I missed this info and it was somewhere)

**Comment by rauenzi** [comment]
> official website of plugins for BetterDiscord

The website you linked is *not* the official website for BetterDiscord.

> Is it written anywhere that you only support the official Discord client or is there a list of supported Discord clients ?

On the README of this repo it says:

> A series of plugins and themes for BetterDiscord.

BetterDiscord is a client mod for Discord, it does not support custom things like Lightcord. The copy of BetterDiscord they ship is unofficial. Since BetterDiscord only supports being a mod for the Discord client, that's what my plugins support as well.
