### ISSUE TITLE
[Feature]  Better Formating - Codeblocks

### ISSUE THREAD

**Issue by Dschogo** [rauenzi/BetterDiscordAddons#316]
**Which plugin/theme is this about?**
BFRedux

**Is your feature request related to a problem? Please describe.**
Problem: Betterformating works inside codeblocks and messes with everything

**Describe the feature you'd like**
maybe an option to just ignore codeblocks or a quick toggle in the hover menu (for the complete plugin)

**Comment by rauenzi** [comment]
The plugin should already ignore codeblocks, it currently still does for me.
![DiscordCanary_NtGR5lNXUK](https://user-images.githubusercontent.com/6865942/101996223-69a74000-3c9e-11eb-8082-c51036f825fa.png)
![DiscordCanary_k3V8IvNUVc](https://user-images.githubusercontent.com/6865942/101996224-6a3fd680-3c9e-11eb-9b59-156da99d3e1a.png)

**Comment by Dschogo** [comment]
Weird know it also works for me. Didnt checked in the last week. Maybe some update of a library fixed it (or some reinstall i did last week) Dunno.
