### ISSUE TITLE
[Bug] BetterRoleColors crash when clicking on a profile

### ISSUE THREAD

**Issue by Lunyyx** [rauenzi/BetterDiscordAddons#317]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
When I try to click on a profile with this plugin, my Discord instantly crash... But it's in a certain case that I don't really know, because it worked fine before

**To Reproduce**
1. Activate the plugin
2. Click on a profile
3. Crash...

**Expected Behavior**
I except that the profile appear

**Screenshots**
https://i.imgur.com/kSU5SSd.gif

**Discord Version**
Stable 73801 (c8242ba)
Lightcord 0.1.4 (a205515)
BBD 0.3.5 (lightcord)
Host 0.0.308
Windows 10 64-Bit (10.0.19041)

**Additional Context**
No

**Comment by rauenzi** [comment]
> Lightcord 0.1.4 (a205515)

Closing.

**Comment by Lunyyx** [comment]
> > Lightcord 0.1.4 (a205515)
> 
> Closing.

Why ? Lightcord is a problem ?

**Comment by rauenzi** [comment]
To me, yes. It is an unofficial platform not supported by BD and not supported by my plugins.
