### ISSUE TITLE
[Bug] StatusEveryWhere displays the user's status offline.

### ISSUE THREAD

**Issue by JadeMin** [rauenzi/BetterDiscordAddons#320]
**Which plugin/theme is this about?**
StatusEverywhere v0.4.9

**Describe the Bug**
StatusEveryWhere displays the user's status offline until you directly view the user's profile modal on a large server.

**To Reproduce**
On large servers, profiles of users that are not loaded from the member list (estimated) are displayed offline.
When the profile modal appears by directly clicking the user's avatar or nickname, it is then displayed normally.

**Expected Behavior**
The user's status should be displayed without directly looking at the user's profile modal.

**Screenshots**
I was trying to captured with a large server member list, but it seems like breaking their privacy
There seems to be no other way to capture it.

**Discord Version**
Stable 73806 (0c3eadc)
BD 1.0.0 (850d0cc)
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Additional Context**

**Comment by rauenzi** [comment]
This is not something I can do much about without mass loading a ton of members which can be considered API spam and not something I want to add to the plugin.
