### ISSUE TITLE
[Feature] Collapse Gifs (or any image really)

### ISSUE THREAD

**Issue by Drexl** [rauenzi/BetterDiscordAddons#321]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the feature you'd like**
Collapse images, like in Slack or RocketChat

**Comment by rauenzi** [comment]
Can you be a lot more specific, this is very unclear what you are asking for.

**Comment by Drexl** [comment]
Here is a visual example. My mouse cursor wasn't captured in the recording, but I think you'll get the idea. 
Additionally, a /collapse command to collapse/expand all images would also be nice.

https://user-images.githubusercontent.com/2714403/104467429-2b39c500-556b-11eb-9eab-4c7bc2d3859e.mp4

**Comment by rauenzi** [comment]
I think this is a good suggestion, but perhaps for a different plugin. I would suggest bringing this to a plugin dev that is taking new plugin ideas at this time
