### ISSUE TITLE
[Feature] [Remove Minimum Size] Text box enhancements on small small window sizes

### ISSUE THREAD

**Issue by Drexl** [rauenzi/BetterDiscordAddons#322]
**Which plugin/theme is this about?**
Remove Minimum Size

**Is your feature request related to a problem? Please describe.**
At narrow window sizes the text input box becomes quite tall, largely defeating the benefits of having the window narrow in the first place.

**Describe the feature you'd like**
Prevent the text box from growing in height when not typing, perhaps clamping it's max height even then and adding a scroll bar. Collapse the user controls to just the avatar, providing more room for the text box. Then, either A: disallow those controls from being drawn until a set window width is reached (👎) or B: Those controls are placed at the bottom of the pop-up window that appears when clicking the user avatar (👍).

**Comment by rauenzi** [comment]
This is something that a specialized theme (or at least snippet) could help with, but is out of scope for what the plugin is trying to accomplish (just remove the hard limit).  Maybe a challenge that @Tropix126 would tackle?
