### ISSUE TITLE
[Bug] colors of text not loading

### ISSUE THREAD

**Issue by ThunderBG** [rauenzi/BetterDiscordAddons#323]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Since yesterday the colors of text is default and not colored according to the role color

**To Reproduce**

**Expected Behavior**
Should be colored

**Screenshots**
I don't know how to put screenshots here

**Discord Version**
Stable

**Additional Context**

**Comment by stokic11** [comment]
![image](https://user-images.githubusercontent.com/44114548/103880359-4cb52f80-50d9-11eb-88d3-f1676fff6026.png)
Same problem since yesterday (just providing the ss since he didnt)

**Comment by fghsgh** [comment]
This is an issue with BetterDiscord, not BetterRoleColors, and has already been fixed in the latest update.
