### ISSUE TITLE
[Bug] Clicking on profile pictures crashes Discord

### ISSUE THREAD

**Issue by minhngoc25a** [rauenzi/BetterDiscordAddons#324]
**Which plugin/theme is this about?**

StatusEverywhere

**Describe the Bug**

The bug causes Discord to crash.

**To Reproduce**

1. Click on any profile picture in channels or DMs, not in the user list
2. You will be presented with Discord crash screen

**Discord Version**

Stable

**Comment by fghsgh** [comment]
Same issue. Clicking on a username still works though to open exactly the same dialog though.

**Comment by EpicPenguino** [comment]
i also have this issue

**Comment by nekoma0** [comment]
i have this issue as well, have you guys check if it's related to plugins? i manage to fix the crash by disabling a plugin called "StatusEverywhere v0.4.9" by Zerebos

**Comment by oliver802** [comment]
Me 2

**Comment by JadeMin** [comment]
i have the same problem.

**Comment by JadeMin** [comment]
For me this problem has been solved. Who else?

**Comment by Strencher** [comment]
Yes it was fixed by an update for [ZeresPluginLibrary](https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js).

**Comment by JadeMin** [comment]
> Yes it was fixed by an update for [ZeresPluginLibrary](https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js).

thank you!
