### ISSUE TITLE
[Bug] server search

### ISSUE THREAD

**Issue by master3395** [rauenzi/BetterDiscordAddons#325]
**Which plugin/theme is this about?**

ServerSearch v0.1.4 by Zerebos

**Describe the Bug**

Clicking the search button makes the icon bold, but no popup appears.

**To Reproduce**

It happens every time on stable discord, more stats below.
Stable 74266 (98f1cc3)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Expected Behavior**

Pop up a search box, where you can list all servers, and once searching it shows only the searched server.
**Screenshots**

![image](https://user-images.githubusercontent.com/4199669/104108733-45537900-52c7-11eb-9258-5028e9663d4c.png)

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
