### ISSUE TITLE
[Bug] [AutoPlayGifs] Gif server icons don't play in collapsed folders

### ISSUE THREAD

**Issue by TechniKris** [rauenzi/BetterDiscordAddons#327]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
Servers that have animated icons, are put in a folder and appear as the thumbnail/preview of the folder when it's collapsed, their collapsed-folder previews won't animate unless the user hovers over the folder

**To Reproduce**
1. Create a folder
2. Make sure one of the first 4 servers in the folder have animated icons
3. Collapse the folder

**Expected Behavior**
Servers appearing in the collapsed folder should animate at all times when the window is active.

**Screenshots**
![servers](https://user-images.githubusercontent.com/30842158/105063926-99efb480-5a7c-11eb-8ab9-0748b25c698d.gif)

**Discord Version**
Stable

**Additional Context**
All autoplay features are enabled in the plugin's settings menu

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
