### ISSUE TITLE
[Bug] RoleMembers completely broken when checking roles with a large amount of members

### ISSUE THREAD

**Issue by PaulCubes** [rauenzi/BetterDiscordAddons#328]
When using the feature to check how many members have a specific role on a server, if a large amount of people have it (i think around 100+), the members list shows transparent on the left side, instead of the right, and you cannot scroll and its bugged.

Screenshot: 
![image](https://user-images.githubusercontent.com/77691976/105075791-e80fb280-5a92-11eb-89f8-ba49af826eba.png)

**Comment by Ulexos** [comment]
Depending on the role it also either does not show any members whatsoever, or the popup is underneath the text channel, like so:
![image](https://user-images.githubusercontent.com/16191795/110207367-5661d600-7e83-11eb-946c-84f6536de0da.png)

**Comment by rauenzi** [comment]
Please check if this is still an issue with the latest version

**Comment by Ulexos** [comment]
it's still an issue, this screen shot f. ex. is of the bugged out list that shows when selecting the role with the most members on it on a server with 222k+ joined users
![image](https://user-images.githubusercontent.com/16191795/115128918-80a9c600-9fe1-11eb-98c5-9230b85b146e.png)

**Comment by rauenzi** [comment]
What version number of the plugin are you on?

**Comment by Ulexos** [comment]
> What version number of the plugin are you on?

ver. v0.1.13

**Comment by rauenzi** [comment]
Try manually redownloading the plugin. What version of the library are you using?

**Comment by Ulexos** [comment]
ZeresPluginLibrary is on v1.2.29

**Comment by rauenzi** [comment]
Try redownloading the plugin, and test it in isolation (no other plugins enabled, no themes, no custom css). I cannot recreate this issue even in severs with the same scale of users that you indicated.

**Comment by Ulexos** [comment]
huh. after uninstalling my current version and redownloading the plugin the list now does not do the weird overlap with the text channels anymore
...but i noticed that the list of members in there seems to be limited aka. does not show all server members with the chosen role, only a couple hundred of it, is that working as intended/limited or restricted by how discord works?
that amount of members in the role member list from the plugin also seems to increase as i scroll down the member list on the right side and reopen the role members menu

**Comment by rauenzi** [comment]
> is that working as intended/limited or restricted by how discord works?

It is the latter, Discord does not load in all members of a large server, and the plugin does not and will not force load them.
