### ISSUE TITLE
Send Button seems to break reactions

### ISSUE THREAD

**Issue by Vitoire** [rauenzi/BetterDiscordAddons#330]
Hey there!

This is something I started realizing since yesterday, when I thought I was blocked by someone, because my reaction would magically vanish instantly after applying it to a message. Since my alt account that was logged into my browser was able to add reactions just fine, I went on a search to see what plugins could cause this issue and found out that it seems to be the Send Button plugin. Once enabled, reactions would vanish, but this is entirely clientside. Once disabled, the reaction shows up the way it should.

It seems that this only occurs when the plugin "RemoveBlockedMessages" by the creator DevilBro is also activated. I am not sure why this weird thing is happening, but it's a bug and I am thus reporting it.

I am on Windows 10 Professional 64-bit, Discord Stable Build.

**Comment by rauenzi** [comment]
It sounds like an issue with the other plugin. SendButton does not do anything with reactions and does not touch any related components.

**Comment by Vitoire** [comment]
Thanks for the response, albeit a tad bit late. The issue has since been resolved and there was indeed conflicting jumbomumbo with
