### ISSUE TITLE
[Feature] Implement tracking prevention features from ecureDiscord.js.

### ISSUE THREAD

**Issue by Atrate** [rauenzi/BetterDiscordAddons#332]
**Which plugin/theme is this about?**
DoNotTrack

**Describe the feature you'd like**
The DoNotTrack plugin has a couple of useful features, but could be made more functional by introducing additional tracking protection features as seen in: https://gitlab.com/leogx9r/DiscordCrypt/-/blob/master/scripts/secureDiscord.js .

Stripping headers and URLs, disabling permissions as well as filtering hostnames Discord connects to could do wonders for privacy.

**Comment by Farcrada** [comment]
While this would be an amazing addition, this relies on being executed at the core (see installation notes). Somewhere the plugin library doesn't have access to. In short this is not possible to do with a plugin and this plugin would be the closest we can get.

At the end of the day everything's possible, but at what point can you still call it a plugin and at what point does it become a modification of the program?

**Comment by rauenzi** [comment]
As said above, these are no longer possible for a plugin
