### ISSUE TITLE
[Bug] BDContextMenu

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#333]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
Just... doesn't work

**To Reproduce**
Try to use it

**Expected Behavior**
Adds BD shortcuts to the settings context menu

**Screenshots**
![image](https://user-images.githubusercontent.com/63931154/106061043-28a3a780-60f5-11eb-8d63-e204b7392d83.png)

![BDCM](https://user-images.githubusercontent.com/63931154/106060821-d5c9f000-60f4-11eb-8acd-4896af5e5937.png)

**Discord Version**
Stable 75317 (3736dd9)
Host 0.0.309

**Comment by rauenzi** [comment]
Can you confirm if this is still the case with the latest version?

**Comment by dav1312** [comment]
All good! 
Don't forget to bump the version if possible, had to manually update most of your plugins

**Comment by rauenzi** [comment]
The most recent change to several of the plugins were not actually changes to the plugins but to the install script and will only be useful to new users so no version change/update notice.

The only ones actually getting a change (that needed updating) were BRC, BlurNSFW, DNT, HideDisabledEmojis, PV, and ServerSearch. And looking at the commit all the transpiled files (aside from PV got the version bump correctly).

For this one specifically, this was actually fixed ages ago, the change for this plugin today was just removing dead code that is no longer needed for the new version of BD and only executed when being used with the old version.
