### ISSUE TITLE
[Feature] Rearrange Favorite Emotes

### ISSUE THREAD

**Issue by CowsertheKoopahog** [rauenzi/BetterDiscordAddons#334]
**Which plugin/theme is this about?**
EmojiUtilities

**Is your feature request related to a problem? Please describe.**
In order to rearrange the order of favorited emotes or add a new emote in-between already favorited, you have to remove the existing favorites until you get to the emotes you wish to remain the same, then manually readd the favorites.

**Describe the feature you'd like**
The ability to sort favorite emotes in a drag/drop manner, either in the settings or in the emotes menu itself.

**Comment by rauenzi** [comment]
This plugin has been discontinued
