### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Dschogo** [rauenzi/BetterDiscordAddons#336]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the feature you'd like**
Add a List with all users which have the view access to the channel (with search) and if you click a user it show the exact permissions for him with channel overwrites (in brackets?) + rightclick users for modal options.

**Additional context**
Should be self explaining

**Comment by rauenzi** [comment]
How does this differ from #335 ?

**Comment by Dschogo** [comment]
How did github made a second issue / request out of an edit? Iam confused

**Comment by Dschogo** [comment]
Gonna close this cause of weird duplication bug
