### ISSUE TITLE
[Bug] inside of zerus public library for the free nitro emojis the doesn't works  I've pressed crtl+R many times but still not fix pls help me

### ISSUE THREAD

**Issue by ILOVEPRODIGY** [rauenzi/BetterDiscordAddons#337]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by rauenzi** [comment]
There is no such free nitro emoji feature in any one of my plugins or library.

**Comment by ILOVEPRODIGY** [comment]
But there is? Sent from Mail for Windows 10 From: ZackSent: February 4, 2021 8:05 PMTo: rauenzi/BetterDiscordAddonsCc: ILOVEPRODIGY; AuthorSubject: Re: [rauenzi/BetterDiscordAddons] [Bug] inside of zerus public library for the free nitro emojis the doesn't works I've pressed crtl+R many times but still not fix pls help me (#337) There is no such free nitro emoji feature in any one of my plugins or library.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rauenzi** [comment]
Nope, there is no such feature.

**Comment by ILOVEPRODIGY** [comment]
Can I pls send you an screenshot? Sent from Mail for Windows 10 From: ZackSent: February 4, 2021 8:07 PMTo: rauenzi/BetterDiscordAddonsCc: ILOVEPRODIGY; AuthorSubject: Re: [rauenzi/BetterDiscordAddons] [Bug] inside of zerus public library for the free nitro emojis the doesn't works I've pressed crtl+R many times but still not fix pls help me (#337) Nope, there is no such feature.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ILOVEPRODIGY** [comment]
I think tis cracked because I saw it on youtube  Sent from Mail for Windows 10 From: ZackSent: February 4, 2021 8:07 PMTo: rauenzi/BetterDiscordAddonsCc: ILOVEPRODIGY; AuthorSubject: Re: [rauenzi/BetterDiscordAddons] [Bug] inside of zerus public library for the free nitro emojis the doesn't works I've pressed crtl+R many times but still not fix pls help me (#337) Nope, there is no such feature.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
