### ISSUE TITLE
[Bug] Conflicts with Material Design Theme

### ISSUE THREAD

**Issue by YellowBanana508** [rauenzi/BetterDiscordAddons#338]
Hello, I am using the google material design theme but this plugin conflicts with the typing message. It overlaps the arrow. Is it possible to change the arrow's position like making it a bit upward? Thanks :)

![Untitled](https://user-images.githubusercontent.com/71059201/107033099-d3ddec00-67da-11eb-930a-a5a3f3e42d29.png)

**Comment by Tropix126** [comment]
This is more an issue with the theme than the plugin.

**Comment by YellowBanana508** [comment]
> This is more an issue with the theme than the plugin.

cant i just make a custom css and push the arrow upward?
can u gimme the css cuz i dont know

**Comment by maicol07** [comment]
Actually the bug is about font colors:
![immagine](https://user-images.githubusercontent.com/9463142/111512702-5352c980-8750-11eb-92bd-940ad78e2d23.png)

**Comment by rauenzi** [comment]
This is something the theme will have to make compatible rather than the plugin.
