### ISSUE TITLE
[Bug] PermissionsViewer New Use Slash Commands perm

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#341]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
The plugin is not able to load which roles have that perm properly (it shows that is disabled for all of them even tho it isn't)

**To Reproduce**
Check role perms of a role that has that perm enabled

**Expected Behavior**
When a role has that perm, it displays it in the user popout and in role perms with ✔️

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This has been fixed in the latest version!

**Comment by dav1312** [comment]
Please don't forget to bump the version to `0.1.17` !

**Comment by rauenzi** [comment]
Oddly enough I had, but git still committed the previous transpiled version https://github.com/rauenzi/BetterDiscordAddons/commit/726f015e791852d6ef85a2c0236c90cec04aa87b#diff-140420239c9589e8a1f3588b7be005f5e5cd6199a1493549e459fdebd236468c
