### ISSUE TITLE
[Feature] Remove blur from BlurNSFW when an image is focused

### ISSUE THREAD

**Issue by heynohs** [rauenzi/BetterDiscordAddons#342]
**Which plugin/theme is this about?**
BlurNSFW

**Is your feature request related to a problem? Please describe.**
When you click on an image to enlarge it you still need to keep your mouse on the image for it to not blur the image.

**Describe the feature you'd like**
Add an option for images to unblur when clicking on and enlarging them.

**Additional context**
https://imgur.com/WchydQY **(SFW)**

**Comment by rauenzi** [comment]
The latest version of BlurNSFW now has this as a setting (defaulting to enabled)!
