### ISSUE TITLE
ZeresPluginLibrary Crashing Discord

### ISSUE THREAD

**Issue by CrossedLemur** [rauenzi/BetterDiscordAddons#343]
**Which plugin/theme is this about?**
ZeresPluginLibrary

Using ZeresPluginLibrary causes Discord to crash as soon as loaded on startup

Version: Latest, Stable. The bug started when I updated

Removing ZeresPluginLibrary from the plugins folder to forcefully disable it stops the issue, thus why I am led to believe it is a bug in ZeresPluginLibrary

**Comment by rauenzi** [comment]
Try removing all plugins other than that library. Also this is not the repository for that library.
