### ISSUE TITLE
[Bug] HideDisabledEmojis not working

### ISSUE THREAD

**Issue by Lapidearum** [rauenzi/BetterDiscordAddons#344]
**Which plugin/theme is this about?**
HideDisabledEmojis

**Describe the Bug**
Plugin is not functioning. Unusable emojis and emojis blacklisted using EmojiUtilities are displayed in gray, at the end of the server's list or search results if applicable.

**To Reproduce**
Install HideDisabledEmojis and log in with an account that does not have Discord Nitro. Alternatively, install HideDisabledEmojis and EmojiUtilities and blacklist an emoji.

**Expected Behavior**
Unusable emojis should not be not visible in the emoji menu. Blacklisted emojis  should only be visible in the emoji menu under the Blacklist subcategory.

**Discord Version**
Stable

**Comment by maxoku** [comment]
Will that be fixed? It's a very essential add-on.

**Comment by rauenzi** [comment]
Yes it will, I will be getting back to all my plugins soon, but I have been working on BetterDiscord itself in the meantime.

**Comment by maxoku** [comment]
Oki, thanks for answering.

**Comment by rauenzi** [comment]
This has been fixed in the latest version!

**Comment by maxoku** [comment]
Yey it works, thanks for fixing :D
