### ISSUE TITLE
[Feature] [StatusEverywhere] Option to disable status on 'WhoReacted'-plugin avatars beside reacts

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [rauenzi/BetterDiscordAddons#346]
**Which plugin/theme is this about?**
StatusEverywhere

**Is your feature request related to a problem? Please describe.**
The [WhoReacted](https://github.com/jaimeadf/BetterDiscordPlugins/tree/main/WhoReacted) plugin adds tiny versions of user's avatars next to reacts, underneath messages; they're already small, and they become nearly entirely covered when StatusEverywhere adds statuses on top of them:

<img width="334" alt="Screen Shot 2021-03-17 at 16 19 05" src="https://user-images.githubusercontent.com/200/111539979-87bc8a80-873c-11eb-8542-4db3c828235a.png">

**Describe the feature you'd like**
Integration between these two excellent plugins would be fantastic — either just never showing status on reactions'-avatars, or adding an option as to whether or not to show them!

**Comment by rauenzi** [comment]
Due to my own time management issues I am starting to offload some of my plugins starting with StausEverywhere. You can find the new maintained version by @Strencher here: https://betterdiscord.app/plugin/StatusEverywhere
