### ISSUE TITLE
BetterRoleColors 0.6.0 not showing boxed roles 

### ISSUE THREAD

**Issue by squabblez** [rauenzi/BetterDiscordAddons#35]
In the preview picture under "**Colored Popouts & Modals**" It shows that you can have boxed role colours. On my discord, it does not show the boxed roles. Is there an option to put them on or is this some sort of bug? Plz fix asap.

**Comment by rauenzi** [comment]
That preview is using Beard's Material Design Theme for discord, and was taken in a previous version of discord. It's not a feature of the plugin
