### ISSUE TITLE
[Bug] ServerSearch doesn't work

### ISSUE THREAD

**Issue by HRudyPlayZ** [rauenzi/BetterDiscordAddons#350]
**Which plugin/theme is this about?**
ServerSearch

**Describe the Bug**
ServerSearch doesn't work anymore.
And before it completely broke, it used to not load when BetterDiscord started and required to disable and renable the plugin.

**To Reproduce**
Use ServerSearch, at least on Discord Stable 0.0.309.

**Expected Behavior**
The plugin would work and display the search button.

**Discord Version**
Stable 0.0.309

**Comment by TheEvasion** [comment]
Same with me.

**Comment by Mrlemon14** [comment]
same with me

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
