### ISSUE TITLE
[Bug] New BBD update breaks DoNotTrack 

### ISSUE THREAD

**Issue by Farcrada** [rauenzi/BetterDiscordAddons#352]
**Which plugin/theme is this about?**
DoNotTrack

**Describe the Bug**
On start this error occurs: `Uncaught (in promise) TypeError: Cannot read property 'getCurrentWebContents' of undefined`
Which would be related to: https://github.com/rauenzi/BetterDiscordAddons/blob/9a7cfde951c5d85a6afedc504e62c4d59b13ba3b/Plugins/DoNotTrack/DoNotTrack.plugin.js#L67

**Discord Version**
- Stable
- The new BBD version.

**Comment by Farcrada** [comment]
Addendum: Commenting this line out will resolve the issue.

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
