### ISSUE TITLE
[Bug] BetterRoleColors no longer coloring name in Account Details

### ISSUE THREAD

**Issue by asorel1942** [rauenzi/BetterDiscordAddons#353]
**Which plugin/theme is this about?**

Better Role Colors
**Describe the Bug**

The user's username is no longer colored according to role in the Account Details preview in the lower-left of the Discord window (It is still colored in the popout after clicking on Account Details, but the preview remains the default white).

**To Reproduce**

Install BetterRoleColors and observe the Account Details section

**Expected Behavior**

For the Account Details username to be colored
**Screenshots**

![image](https://user-images.githubusercontent.com/33983895/113316169-0a684c80-92dc-11eb-865b-95e1384112f0.png)

**Discord Version**

![image](https://user-images.githubusercontent.com/33983895/113316227-17853b80-92dc-11eb-9f53-f4e0fd488f54.png)

**Additional Context**

So far, have attempted:

- Disabling and re-enabling BetterRoleColors
- reloading Discord
- Disabling my installed theme (dark null), then reloading Discord
- Marking role colors as !important in plugin settings, then reloading Discord

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
