### ISSUE TITLE
rolemembers plugin only showing online members per role

### ISSUE THREAD

**Issue by Kraken12112** [rauenzi/BetterDiscordAddons#355]
Used to show all members.

**Comment by rauenzi** [comment]
This plugin actually never force loaded offline members and it's not something I plan to add.

**Comment by Kraken12112** [comment]
The plugin used to show all members of a role regardless of online or
offline status and you can even see it in the gif you provided on the
website https://i.imgur.com/rGT9Fbl.gif. Also when selecting the top role,
the list appears to show up behind the client so you're unable to see it

**Comment by rauenzi** [comment]
The offline members will still show on smaller servers where Discord loads offline members. This plugin never force loaded offline members.

**Comment by Kraken12112** [comment]
f
