### ISSUE TITLE
[Bug] BetterFormattingRedux not working.

### ISSUE THREAD

**Issue by GooUckd** [rauenzi/BetterDiscordAddons#356]
**Which plugin/theme is this about?**
This plugin is about formatting text.

**Describe the Bug**
I noticed there is no bar/button to bring up the formatting thing.

**To Reproduce**
Download the plugin and turn it on.

**Expected Behavior**
I expected a bar to be able to format text.

**Screenshots**
With theme.
![image](https://user-images.githubusercontent.com/62660100/113493379-6e129580-94e7-11eb-8b6b-e873d287ecfc.png)
Without theme.
![image](https://user-images.githubusercontent.com/62660100/113493390-88e50a00-94e7-11eb-9d26-1d224d1b4c5e.png)

**Discord Version**
Stable.

**Additional Context**
I tried turning off the theme too. Same result.
![image](https://user-images.githubusercontent.com/62660100/113493398-9f8b6100-94e7-11eb-9cd5-2797503dc717.png)
That is how it should have looked like. (From the website.)
https://betterdiscordlibrary.com/plugins/BetterFormattingRedux

**Comment by rauenzi** [comment]
Have you tried disabling and reenabling it? Are there errors in console?

**Comment by GooUckd** [comment]
> Have you tried disabling and reenabling it? Are there errors in console?

I did disable and reenable it.
I will check the console.

**Comment by GooUckd** [comment]
Actually.. How do I find the console..?

**Comment by rauenzi** [comment]
ctrl+shift+i

**Comment by GooUckd** [comment]
> ctrl+shift+i

![image](https://user-images.githubusercontent.com/62660100/113493491-58ea3680-94e8-11eb-8553-db499956159e.png)
Hope that's enough info?

**Comment by GooUckd** [comment]
![image](https://user-images.githubusercontent.com/62660100/113493500-6bfd0680-94e8-11eb-8530-0bf27a072990.png)
Also this if it's needed..?

**Comment by rauenzi** [comment]
Look for big chunks of red. Can you screenshot your versions at the bottom left of settings? And also screenshot the plugin listing of BFRedux to show the version and that it's enabled?

**Comment by GooUckd** [comment]
> Look for big chunks of red. Can you screenshot your versions at the bottom left of settings? And also screenshot the plugin listing of BFRedux to show the version and that it's enabled?

![image](https://user-images.githubusercontent.com/62660100/113493526-a8c8fd80-94e8-11eb-9d66-e22404db5ecc.png)

![image](https://user-images.githubusercontent.com/62660100/113493537-b5e5ec80-94e8-11eb-9949-6b91b32e3ff1.png)
I hope the 2nd one is what you are asking for.

**Comment by GooUckd** [comment]
![image](https://user-images.githubusercontent.com/62660100/113493632-c2b71000-94e9-11eb-8f6f-cfa8e0d4b672.png)
Found some 404 stuff. Theres more than 2.

**Comment by GooUckd** [comment]
Um.. Hello?

**Comment by GooUckd** [comment]
I got it working. I just hit shift + R or ctrl + R by accident and it works.
