### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by Kikoszzz** [rauenzi/BetterDiscordAddons#358]
It's not working...

**Comment by UltimateBoi** [comment]
same

**Comment by rauenzi** [comment]
This gives me no information. It doesn't even tell me what "it" is...

**Comment by UltimateBoi** [comment]
> This gives me no information. It doesn't even tell me what "it" is...

basically when we right click, it dosent show in the menu at all

**Comment by UltimateBoi** [comment]
oops and i forgot to add its the BDContext menu plugin
