### ISSUE TITLE
BetterRoleColors 0.6.0 boxed roles are not appearing

### ISSUE THREAD

**Issue by squabblez** [rauenzi/BetterDiscordAddons#36]
On my beards material theme which you also have on. It shows you have boxed roles under "**Colored Popouts & Modals**" I've downloaded the plugin and it seems to not appear in my roles. Is there an option for me to enable it? Or is this some sort of bug? Reply back ASAP.

**Comment by rauenzi** [comment]
As I said before it was on a previous version of discord, discord has changed how the roles were displayed so they do not look like that anymore even with beard's theme. The theme may be updated to change the look but it is not an issue with the plugin.

As an aside please try to avoid opening issues for things that aren't issues. This would be better off asked in my server or beards server.

**Comment by squabblez** [comment]
Oh sorry about that, I thought my issue didn't go in the first time lol! And yes I will avoid issues that aren't issues, sorry about that once again. Anyways I completely understand. 

Good Day.
