### ISSUE TITLE
[Feature] status almost everywhere 

### ISSUE THREAD

**Issue by Shuridirty** [rauenzi/BetterDiscordAddons#361]
add an option to take off where the status shows

**Comment by rauenzi** [comment]
Can you be more specific? It sounds like what you want defeats the purpose of the plugin.

**Comment by Shuridirty** [comment]
> Can you be more specific? It sounds like what you want defeats the purpose of the plugin.

I want to have the feature to take off the status in specific places. Let's say I don't like the status in a voice channel i could go into settings and take it off there

**Comment by rauenzi** [comment]
This is something I have considered and do not intend to add.
