### ISSUE TITLE
[Bug] AutoPlayGifs Not Working On Message Chat

### ISSUE THREAD

**Issue by sonitaaaaa** [rauenzi/BetterDiscordAddons#363]
AutoPlayGifs not working on Chat, Guilds

**Comment by misterpyrrhuloxia** [comment]
I'm having the same problem. Most, if not, all gifs don't autoplay anymore.

**Comment by masteroflosers** [comment]
Same problem here as well. I imagine it might be an error with discord itself but it still hasn't been fixed.

**Comment by rauenzi** [comment]
Fixed at latest level
