### ISSUE TITLE
PermissionsViewer [Bug] 

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#365]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
permissions option on the right click missing on profile and in the chat

**Discord Version**
newest one app-1.0.9001

**Comment by rauenzi** [comment]
Duplicate of #351

**Comment by BlueStarBRS** [comment]
@rauenzi 
> Duplicate of #351

and still not working
![image](https://user-images.githubusercontent.com/25110093/116816441-389ead80-ab62-11eb-91f8-da3abe7c38d0.png)

**Comment by rauenzi** [comment]
You already posted that on the other one.
