### ISSUE TITLE
StatusEverywhere [Bug] 

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#366]
**Which plugin/theme is this about?**
StatusEverywhere -_-

**Describe the Bug**
its just nothing happens

**To Reproduce**
load it and you see its dont work

**Expected Behavior**
show status in chat

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/114176580-9fea8880-993b-11eb-86b3-c01ca47de819.png)

**Discord Version**
app-1.0.9001 & new BDiscord update

**Additional Context**
i disabled my theme´s but it stiill dont work
btw with the editusers plugin on the voice channels users who are edited show as offline maybe wehn the chat get fixed (what i hope) then the bug is then on that too

**Comment by UltimateBoi** [comment]
Can you send me that read all messages plugin, my discord is: Ult!mate#1450

**Comment by UltimateBoi** [comment]
try putting it into a theme

**Comment by BlueStarBRS** [comment]
> try putting it into a theme
How?

**Comment by rauenzi** [comment]
Can you try disabling all other plugins? There are other plugins (and libraries) that try to edit the avatar component and can interfere.

**Comment by UltimateBoi** [comment]
Also its the same with me

**Comment by silverxd** [comment]
> Can you try disabling all other plugins? There are other plugins (and libraries) that try to edit the avatar component and can interfere.

Doesn't unfortunately fix the issue. I've attached some more images below.
![image](https://user-images.githubusercontent.com/57298235/115206086-e8a3fd80-a102-11eb-91f3-c8c585a10146.png)
![image](https://user-images.githubusercontent.com/57298235/115206088-e9d52a80-a102-11eb-90b5-e1209acb1231.png)

**Comment by GoldenChrysus** [comment]
Also reproducing with every other plugin (aside from ZeresPluginLibrary) and theme disabled.

**Comment by BlueStarBRS** [comment]
and still not fixed ?

**Comment by UltimateBoi** [comment]
ye its not rip

**Comment by UltimateBoi** [comment]
![image](https://user-images.githubusercontent.com/63293118/117045078-037f9000-ad07-11eb-914f-01dc603f1f94.png)
i just want to point out this???!

**Comment by silverxd** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/63293118/117045078-037f9000-ad07-11eb-914f-01dc603f1f94.png)
> i just want to point out this???!

:D
![image](https://user-images.githubusercontent.com/57298235/117302733-a3aef380-ae84-11eb-8f94-f3c6f96d4f22.png)

**Comment by Osyruu** [comment]
Check on the [Zere's Place Discord](https://discord.com/channels/292141134614888448/333116127204999171/840021561229705237) :p

**Comment by Dyskal** [comment]
> Check on the [Zere's Place Discord](https://discord.com/channels/292141134614888448/333116127204999171/840021561229705237) :p

can you give a link to the server please ?

**Comment by Osyruu** [comment]
Huh, well, I can't do a server invite.
Otherwise, you need to wait Zerebos to push the code to fix it..

**Comment by SwiftWinds** [comment]
This plugin was actually working for me a few days ago, but the latest Discord updates appear to have broken some of them (now, it only appears in reactions, since I have WhoReacted plugin installed). I'll try deleting all other plugins and themes to try to isolate the issue and see if it still doesn't work.

**Comment by SwiftWinds** [comment]
OK I just tried uninstalling everything (all themes and plugins) and adding back just StatusEverywhere:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/12981958/119794432-61c60b80-be8c-11eb-9a28-17295d31abab.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/12981958/119794294-40651f80-be8c-11eb-8d6c-e6a96ea7bf08.png">

But it still doesn't work:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/12981958/119794396-5b379400-be8c-11eb-827f-9ba3ea61cadf.png">

**Comment by SwiftWinds** [comment]
If you want any debugging info or anything, I can provide it! Thanks for your awesome work on BetterDiscord and many of its most amazing plugins!

**Comment by UltimateBoi** [comment]
Please fix this, it's probably discord just changed the class, so it will be simple enough to fix, thanks rauenzi!

**Comment by rauenzi** [comment]
> 
> 
> Please fix this, it's probably discord just changed the class, so it will be simple enough to fix, thanks rauenzi!

Thank you for your insight, this is, however, quite incorrect.

**Comment by UltimateBoi** [comment]
> > Please fix this, it's probably discord just changed the class, so it will be simple enough to fix, thanks rauenzi!
> 
> Thank you for your insight, this is, however, quite incorrect.

sorry.

**Comment by nexioss** [comment]
i have tha same issue with the plugin not working

**Comment by BlueStarBRS** [comment]
@rauenzi  finally fixed ?

**Comment by Masono03** [comment]
doesnt work for me either. im on newest canary. tried disabling my theme and all other plugins and still doesnt work.

**Comment by Osyruu** [comment]
There's a new version by clicking [here](https://betterdiscord.app/plugin/StatusEverywhere).

**Comment by rauenzi** [comment]
Due to my own time management issues I am starting to offload some of my plugins starting with StausEverywhere. You can find the new maintained version by @Strencher here: https://betterdiscord.app/plugin/StatusEverywhere
