### ISSUE TITLE
BDContext menu [Bug] 

### ISSUE THREAD

**Issue by UltimateBoi** [rauenzi/BetterDiscordAddons#367]
**Which plugin/theme is this about?**

BDContext Menu

**Describe the Bug**

It basically dosent show when i right click anywhere, not just in normal places like messages.

**Expected Behavior**

Its meant to show a Copy Selector inside the context menu of discord when i right click.

**Discord Version**

Stable

**Additional Context**

Could you fix this please, i am trying to make a theme and it is helpful if i can just copy it straight from the context menu, Thanks!

**Comment by rauenzi** [comment]
> Its meant to show a Copy Selector inside the context menu of discord when i right click.

That's not what this plugin does, sorry.

**Comment by UltimateBoi** [comment]
thats what it did do for like 5 months bruh

**Comment by rauenzi** [comment]
No it did not, you are mistaking an old BetterDiscord feature called "Copy Selector" with this plugin.
