### ISSUE TITLE
[Bug] AccountDetailsPlus user popout does not work automatically

### ISSUE THREAD

**Issue by KowalskiYukio** [rauenzi/BetterDiscordAddons#369]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
The user popout feature won't work unless you tweak the settings for the plugin or restart the plugin.

**To Reproduce**
1. Start or restart discord
2. Click on your own profile picture

**Expected Behavior**
The user popout should show up automatically without having to tweak the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/30660412/114575006-589e2800-9cac-11eb-81e9-75ce4b2e70eb.png)

**Discord Version**
Stable 82117 (58a452e)
BD 1.0.0 (stable)

**Comment by rauenzi** [comment]
I cannot recreate this, can you remove the plugin's config file and reload?

**Comment by KowalskiYukio** [comment]
it works now thanks

**Comment by KowalskiYukio** [comment]
actually now it doesn't work again even after I deleted the config file. The popout would only work once and then it would be gone the next time I try it.

![21-04-19 10 21 03](https://user-images.githubusercontent.com/30660412/115173143-3156b900-a0f9-11eb-81ed-7c34db11928d.gif)

**Comment by BlackLightX** [comment]
I have that same problem. What should I do?

**Comment by jimnoname** [comment]
I can reproduce this issue while https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls/ is also enabled. Do you happen to use it aswell?

**Comment by rauenzi** [comment]
Try removing all plugins except for this and the library and see if the issue persists.

**Comment by KowalskiYukio** [comment]
> I can reproduce this issue while https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls/ is also enabled. Do you happen to use it aswell?

Yes I do. And now that you mention it, I tried disabling the spotify controls plugin and now AccountDetailsPlus works
