### ISSUE TITLE
[Bug] PermissionViewer display error

### ISSUE THREAD

**Issue by minhngoc25a** [rauenzi/BetterDiscordAddons#370]
**Which plugin/theme is this about?**

PermissionViewer

**Describe the Bug**

It's weird how the window is presented right now

**Screenshots**

![image](https://user-images.githubusercontent.com/33834488/114654921-66d45e80-9d15-11eb-87b1-090271aeacb8.png)

**Discord Version**

Stable

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
