### ISSUE TITLE
[Bug] PermissionsViewer: Dev console shows error for some users

### ISSUE THREAD

**Issue by guihkx** [rauenzi/BetterDiscordAddons#375]
**Which plugin/theme is this about?**
PermissionsViewer v0.1.17

**Describe the Bug**
For some users, the PermissionsViewer plugin shows the following error on the dev console:

```console
[Patcher] Could not fire after callback of componentDidMount for PermissionsViewer TypeError: Cannot read property 'permissions' of undefined
    at t.popoutMount (<anonymous>:491:48)
    at Object.callback (<anonymous>:518:61)
    at t.<anonymous> (<anonymous>:1919:51)
    at Ru (18fb3893c96106f45fa4.js:2)
    at t.unstable_runWithPriority (18fb3893c96106f45fa4.js:2)
    at zi (18fb3893c96106f45fa4.js:2)
    at Nu (18fb3893c96106f45fa4.js:2)
    at cu (18fb3893c96106f45fa4.js:2)
    at 18fb3893c96106f45fa4.js:2
    at t.unstable_runWithPriority (18fb3893c96106f45fa4.js:2)
    at zi (18fb3893c96106f45fa4.js:2)
    at Ji (18fb3893c96106f45fa4.js:2)
    at Qi (18fb3893c96106f45fa4.js:2)
    at fu (18fb3893c96106f45fa4.js:2)
    at Cn (18fb3893c96106f45fa4.js:2)
    at HTMLDocument.r (a690b1b2464598278477.js:2)
_log @ VM519:1726
```

**To Reproduce**
Since this error is only triggered for some users, `hammy#2400`'s profile can trigger it (he's a moderator on BD's Discord).

**Expected Behavior**
The error not to be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/626206/115172496-c925ba00-a09b-11eb-887c-bb37cd47d738.png)

Additionally, no permissions are shown on the user's popup:

![no permissions](https://user-images.githubusercontent.com/626206/115171979-a8109980-a09a-11eb-8b5f-640778dffebe.png)

**Discord Version**
Stable (Linux) - 0.0.14

**Additional Context**
I was able to get rid of that error with the following change:

```diff
diff --git a/Plugins/PermissionsViewer/PermissionsViewer.plugin.js b/Plugins/PermissionsViewer/PermissionsViewer.plugin.js
index 37caf8f..3ea0114 100644
--- a/Plugins/PermissionsViewer/PermissionsViewer.plugin.js
+++ b/Plugins/PermissionsViewer/PermissionsViewer.plugin.js
@@ -487,6 +487,7 @@ module.exports = (() => {
 
                 for (let r = 0; r < userRoles.length; r++) {
                     const role = userRoles[r];
+                    if (!(role in guild.roles)) continue;
                     perms = perms | guild.roles[role].permissions;
                     for (const perm in DiscordPerms) {
                         const permName = strings[perm] || perm.split("_").map(n => n[0].toUpperCase() + n.slice(1).toLowerCase()).join(" ");
```

Though I'm not 100% sure of its accuracy, it seems to work:

![fix](https://user-images.githubusercontent.com/626206/115172750-4e10d380-a09c-11eb-8884-4adecc90a68b.png)

**Comment by dav1312** [comment]
I can reproduce it
Happens with hammy#2400, prox#2112 and Arashiryuu#3000
It's been happening for a very long time actually, not an issue of the last update


When clicking the user popout
![image](https://user-images.githubusercontent.com/63931154/117548603-26c37b80-b036-11eb-8435-27f6a6a15697.png)

When doing right click > permissions
![image](https://user-images.githubusercontent.com/63931154/117548614-38a51e80-b036-11eb-91ad-21ab1becba9e.png)
