### ISSUE TITLE
[Feature] Normalize classes

### ISSUE THREAD

**Issue by narcolepticinsomniac** [rauenzi/BetterDiscordAddons#377]
Any possibility 'normalize classes' option could be brought back as a plugin? I realize the feature wasn't perfect, but with the right combinators, these selectors were a hundred times more reliable than Discord's jenky random strings.

**Comment by rauenzi** [comment]
I do not intend (and would not recommend) to bring this back as a plugin. At the beginning the class normalizer was useful but now it just creates a series of generic selectors that may inadvertently affect an area that was unintended.

**Comment by TimonKanters-TomTom** [comment]
@rauenzi is there a recommended alternative approach for more detailed theming than the main theming mechanism offers?

Keeping a large style sheet stable across Discord updates is much easier with normalised classes (when using parent selectors to avoid the generic-ness of some selectors) than keeping the generated tags in-sync. The lack of this functionality makes it more attractive to stay on an older version of BetterDiscord.

**Comment by rauenzi** [comment]
Contrary to what seems to be popular belief, Discord's class names are not re-rolled very often. And usually when they are there is also a structural HTML change to go along with it (or at the very least changed css properties) which would require some changes to the theme's css even with normalized classes.

My recommendation would be to do it that way with the actual class names. This is what I do in my themes, and if a class really is purely re-rolled it is a simple search and replace (or use a regex selector if speed is not a necessity).


There is a plan in place to add additional _utility_ classes to certain elements. These would be to add additional information to themes or provide a clear and stable semantic name. It would not be a true replacement of normalized classes.

**Comment by narcolepticinsomniac** [comment]
The plan for utility classes sounds great. I just don't understand why you felt the need to remove normalized classes without offering a better alternative. 

IIRC, the feature already had a warning that themes shouldn't rely on normalized classes, which makes sense - they were far from perfect, particularly for proper complete themes to rely on. As the other user stated, for minor user css adjustments, when normalized classes were used in conjunction with the right combinators, they were far more reliable.

> Contrary to what seems to be popular belief, Discord's class names are not re-rolled very often.

This hasn't been my experience at all. Discord is constantly, arbitrarily switching selectors. The normalized classes styling worked for a long time with minor adjustments, whereas without them, practically the entire style would break, at least several times a year.

Anyway, this was a deal-breaker for me. A friend of mine wrote [a powercord plugin for normalized classes](https://github.com/Gusted/powercord-normalized-classes), so I switched to that. Simple text replace to switch the prefix from `da-` to `nc-`, and voila - the user css I've been using for years works again.

**Comment by TimonKanters-TomTom** [comment]
For reference, I found [this post](https://github.com/rauenzi/BetterDiscordApp/issues/750#issuecomment-831939508) very helpful on understanding the change and alternatives that can be used.
