### ISSUE TITLE
AccountDetailsPlus - Doesn't work on reload

### ISSUE THREAD

**Issue by ImmortalZypther** [rauenzi/BetterDiscordAddons#38]
In [AccountDetailsPlus](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus), reloading Discord causes the plugin to stop working.
It starts working again if you turn the plugin off and on again in the Better Discord plugin menu. 
I'm not an expert on this, but it may be fixed if you add a small delay to the load time of the plugin.

**Comment by rauenzi** [comment]
This will only happen if you reload a server and switch to DMs, always reload in DMs
