### ISSUE TITLE
[Feature] BFRedux -- match background to themes

### ISSUE THREAD

**Issue by asorel1942** [rauenzi/BetterDiscordAddons#380]
**Which plugin/theme is this about?**

BFRedux
**Is your feature request related to a problem? Please describe.**

When a custom theme is enabled, the background color of the BFRedux toolbar remains the same grey of the default theme. Would it be possible to add an option to make the toolbar's background match the enabled theme?

**Comment by rauenzi** [comment]
No, it's up to the theme to add support for different plugins.
