### ISSUE TITLE
[Other] Minimum size deprecated?

### ISSUE THREAD

**Issue by TheChilliPL** [rauenzi/BetterDiscordAddons#381]
Seems like the minimum size removal plugin is &ldquo;deprecated&rdquo;, it says that BandagedBD now has it integrated, but I have probably the newest version (BD 1.0.0, injector 0.6.0) and can't find any option to do that. I remember that the plugin stopped working after updating the injector.

**Comment by dav1312** [comment]
You don't have the latest version (1.1.0)
Download BD again => https://betterdiscord.app/

**Comment by rauenzi** [comment]
See the above comment.
