### ISSUE TITLE
[Bug] PermissionsViewer No Theme

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordAddons#386]
The permission viewer doesn't take the look of a theme if set, e.g. if you click on the channel permissions, there you don't have the theme

**Comment by dav1312** [comment]
Yeah it would be better to change to discord variables instead of fixed colors

**Comment by rauenzi** [comment]
@siltentassasin you mean it doesn't match the look of your betterdiscord theme?
