### ISSUE TITLE
Pin/unpin EmojiUtilities menu

### ISSUE THREAD

**Issue by seppl-de** [rauenzi/BetterDiscordAddons#387]
First of all, I am not a programmer, but I was advised to make this request "here". I thank you for this nice plugin. But I also have a request. I would like have a EmojiUtilities Pin menu. It happens to me very often that I want to share several emojis, but then the menu closes immediately. It would be nice if you could program that at some point, if you have the time and mood. thanks

**Comment by rauenzi** [comment]
You should be able to keep the menu open by holding shift on your keyboard while clicking on emojis

**Comment by seppl-de** [comment]
THANK U VERY MUCH!
