### ISSUE TITLE
[Feature] Role Members

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordAddons#389]
Is it possible to make, that the role members plugin can open the role users list, if you click on the role mention? Not only in the server context menu.

And I think an option to disable it in the server context menu would also be great, because I e.g. would prefer if it is just by the role mentions and only optional in the context menu

**Comment by vovklosev** [comment]
Discord stopped working after updating.

**Comment by rauenzi** [comment]
Duplicate of #281
