### ISSUE TITLE
not an issue, but suggestion

### ISSUE THREAD

**Issue by GenesisAria** [rauenzi/BetterDiscordAddons#39]
for improved upside down text:

`this.upsideDownList = " ¡\"#$%⅋,)(*+'-˙/0Ɩ2Ɛᔭ59L86:;>=<¿@∀ꓭꓛꓷƎℲꓨHIſꓘꓶWNOԀQЯSꓕꓵΛMX⅄Z]\\[^‾,ɐqɔpǝɟɓɥᴉ̣ſʞlɯuodbɹsʇnʌʍxʎz}|{";`

i randomly dug up some more close resembling letters.

**Comment by Inve1951** [comment]
the uppercase Y and the sign next to % are broken on discord's default font

**Comment by GenesisAria** [comment]
the uppercase y and % i did not change, so it would have been broken already.

**Comment by rauenzi** [comment]
I'll have to look more into this since some letter did stop working in discord's font for some reason
