### ISSUE TITLE
[BUG/formating issue] Server Search 

### ISSUE THREAD

**Issue by fbievan** [rauenzi/BetterDiscordAddons#390]
(Before it was formatted fine on my previous installation of windows, not sure whats changed)  Just some formatting bug, prob specific to me. (It just really irritates me seeing it out of place 
![image](https://user-images.githubusercontent.com/17110707/117922112-95633c00-b2b7-11eb-8189-b4d02b1fbf62.png)
Not much else to say
Likely something wrong on my part, idk though (Just thought i would mention this here)

**Comment by ThatFlySamurai** [comment]
same issue with mine.

**Comment by fbievan** [comment]
> 
> 
> same issue with mine.

well its not just me, i just installed it even on arch, it did not work, its probably global

**Comment by asportnoy** [comment]
+1. There are also times where the button disappears completely but I don't know if that's related.

**Comment by rauenzi** [comment]
In the future, please use the issue templates/
