### ISSUE TITLE
Status Everywhere

### ISSUE THREAD

**Issue by vovklosev** [rauenzi/BetterDiscordAddons#391]
I do not know if anyone has written about it, but I will. No icons online or offline. There are no icons at all.
https://media.discordapp.net/attachments/812741347680321537/842059077168267264/unknown.png

**Comment by vovklosev** [comment]
![Discord_UinvSxrSjO](https://user-images.githubusercontent.com/49845983/118001345-55e82e80-b34f-11eb-8418-7dcf978dae60.png)

**Comment by Osyruu** [comment]
Check https://discord.com/channels/292141134614888448/333116127204999171/840021561229705237 :p

**Comment by Osyruu** [comment]
#366 duplicated
