### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DMax-YT** [rauenzi/BetterDiscordAddons#392]
**Which plugin/theme is this about?**
BetterFormatingRedux plugin 

**Describe the Bug**
I have toolbar in channels, where  haven't permissions to send messages

**To Reproduce**
1. Go to channel, where you haven't able to write

**Expected Behavior**
Toolbar shouldn't shows.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/13312994/118035170-8a6de180-b373-11eb-8921-f89b1b4f2058.png)

**Discord Version**
PTB

**Additional Context**
No

**Comment by rauenzi** [comment]
This is intended and normal component operation.
