### ISSUE TITLE
[Bug] Use links to the new website

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#394]
**Which plugin/theme is this about?**
I checked a few of them at random and all of them had this issue.

**Describe the Bug**
The download link to your library in the plugins use the old website (e.g [BetterRoleColors](https://github.com/rauenzi/BetterDiscordAddons/blob/726f015e791852d6ef85a2c0236c90cec04aa87b/Plugins/BetterRoleColors/BetterRoleColors.plugin.js#L50))

**Expected Behavior**
Change it to the new link: https://betterdiscord.app/Download?id=9

**Comment by rauenzi** [comment]
This has been done now
