### ISSUE TITLE
[Feature] Make user pings in style of normal pings

### ISSUE THREAD

**Issue by Thedoczek** [rauenzi/BetterDiscordAddons#395]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the feature you'd like**
Make user pings in style of normal pings, so text will be white with transparency 0.8 and background will be set to transparency 0.3.
On hover, background transparency 1.0 (no transparency), no change at text transparency.
When pinging roles, they behave like @everyone, so they just don't change.

****
![obraz](https://user-images.githubusercontent.com/69758777/118394570-bb853500-b645-11eb-8727-f98fce9cad03.png)
![obraz](https://user-images.githubusercontent.com/69758777/118394562-ac05ec00-b645-11eb-9d9c-c0814da14c32.png)

**Comment by rauenzi** [comment]
Mentions will be reworked as a part of #397
