### ISSUE TITLE
[Feature] - Rolemembers - copy id in server roles list

### ISSUE THREAD

**Issue by Dschogo** [rauenzi/BetterDiscordAddons#400]
**Which plugin/theme is this about?**
RoleMembers

**Describe the feature you'd like**
Rightclicking a role in the roles list (the one which appears on rightclicking a server or the server name) should copy the role id. 

Think that pretty easy to implement.

**Comment by rauenzi** [comment]
This was implemented but instead of right click, you must hold control. It will even give you a little toast to let you know the ID was copied.

**Comment by XxUnkn0wnxX** [comment]
@rauenzi I don't think this works on mac..
I tried holding Control & it doesn't copy anything or give me a toast


https://user-images.githubusercontent.com/2242880/129772761-2475a70e-98b1-450a-b3bf-bb2f5676c078.mp4

**Comment by rauenzi** [comment]
Have you tried holding command?

**Comment by XxUnkn0wnxX** [comment]
@rauenzi still not working, I've tried Command, Option, Control

https://user-images.githubusercontent.com/2242880/129781806-9019ab17-8a35-4e19-ab96-4a0e4219be52.mp4

**Comment by Dschogo** [comment]
@XxUnkn0wnxX what version are you running? (latest is 0.1.14). Works fawlessly for me

**Comment by XxUnkn0wnxX** [comment]
> @XxUnkn0wnxX what version are you running? (latest is 0.1.14). Works flawlessly for me

![Screen Shot 2021-08-18 at 8 16 43 pm](https://user-images.githubusercontent.com/2242880/129881442-04528190-606d-4e26-a193-475632ef8f42.jpg)
latest one.

Discord ver:
Stable 93958 (486a541)
BetterDiscord 1.2.1
Host 0.0.263 OS X 11.0.0 (20.6.0)

**Comment by luongthomas** [comment]
I'm experiencing the same issue as XxUnkn0wnxX, after clicking the role, the users list does not show up
RoleMembersv0.1.14by Zerebos
BetterDiscord 1.2.4

Stable 103508 (42e6c51)
BetterDiscord 1.2.4
Host 0.0.264 OS X 10.15.7 (20.6.0)
