### ISSUE TITLE
[Bug] [AccountDetailsPopup] Channels' names overlay popup background

### ISSUE THREAD

**Issue by Tudi20** [rauenzi/BetterDiscordAddons#401]
**Which plugin/theme is this about?**
AccountDetailsPopup

**Describe the Bug**
The user popup's background is behind the server's channels' names to be shown.

**Expected Behavior**
The user popup's background obscuring the channels' names.

**Screenshots**

![kép](https://user-images.githubusercontent.com/13798839/119497395-cf771800-bd64-11eb-97b5-ff6457399c49.png)

**Discord Version**
Stable

**Additional Context**
Maybe it's a conflict somewhere?

**Comment by AdriGeeK03** [comment]
same for me :/ 
![image](https://user-images.githubusercontent.com/50402620/119617198-da33ba80-be01-11eb-8af1-59f759a83302.png)

**Comment by AdriGeeK03** [comment]
It seems to be fixed now.
