### ISSUE TITLE
[Bug] [AccountDetailsPlus] On certain themes the popup is cut off

### ISSUE THREAD

**Issue by Tudi20** [rauenzi/BetterDiscordAddons#402]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
On certain themes (those that put the server list to the top) the account popup is cut off on the side. (Since Discord isn't programmed to auto-align inside the app horizontally - it does auto-align vertically).

**To Reproduce**
Grab https://betterdiscord.app/theme/Horizontal%20Server%20List and enable it.
Click on your user details for the popup.

**Screenshots**
![kép](https://user-images.githubusercontent.com/13798839/120015899-35bd9e00-bfe4-11eb-9d83-1747d453a4e5.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This is something themes can generally fix by adding support for this plugin
