### ISSUE TITLE
[Bug] PermissionsViewer

### ISSUE THREAD

**Issue by rossiscool123** [rauenzi/BetterDiscordAddons#406]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
Cannot see permissions for individual channels anymore, voice channels and categories work though.

**To Reproduce**
Right click a text channel and you wont see the permissions option.

**Expected Behavior**
A permissions tab to appear when I right click a text channel.

**Screenshots**
https://i.imgur.com/gSICQNi.png
https://i.imgur.com/eB7Zmwy.png

**Discord Version**
Stable

**Comment by rauenzi** [comment]
This function is still working for me, however you are using unsupported and potentially incompatible plugins which I do not support.

**Comment by Mijyuoon** [comment]
I can reproduce this without any other plugins being enabled.

**Comment by rossiscool123** [comment]
Yeah same, disabled all my plugins and it still doesn't work. :)

**Comment by dav1312** [comment]
@rauenzi This issue appears without any other plugins or themes. Please reopen it.
