### ISSUE TITLE
[Feature] Save my favorites somewhere

### ISSUE THREAD

**Issue by NanoCats** [rauenzi/BetterDiscordAddons#409]
**Which plugin/theme is this about?**
EmojiUtilities 

**Is your feature request related to a problem? Please describe.**
 It really blows chunks to find that an emote that I use a lot is just gone one day

**Describe the feature you'd like**
My solution is that every emote that you right click → favorite is stored somewhere, anywhere, and if you try to use it and the plugin determines that it's gone, it warns you that it is in fact gone, but you can probably easily upload it to a server of your own  

**Additional context**
nah that's it dude, I'd suggest backing up ALL emotes, but that would probably be too far. :v

**Comment by rauenzi** [comment]
All your favorites (identifiers) are already stored in the plugin folder under `EmojiUtilities.config.json`

**Comment by NanoCats** [comment]
By "save" I mean as PNGs or whatever, won't they still be like, gone, if the server removes them?

**Comment by rauenzi** [comment]
This plugins has been discontinued
