### ISSUE TITLE
[Bug] AutoPlayGifs not working anymore

### ISSUE THREAD

**Issue by MaximeDawn** [rauenzi/BetterDiscordAddons#410]
**To Reproduce**
Launch Discord with autoplaygifs enabled. Doesn't work.

**Expected Behavior**
Launch Discord with autoplaygifs enabled. Works.

**Screenshots**
It sends this error a few times per minute.
![image](https://user-images.githubusercontent.com/20993007/120918047-b3536f00-c6b2-11eb-87a8-8d1c3d733e4a.png)

**Discord Version**
Stable 86917 (ace8ac3)

**Comment by MemeBard** [comment]
Plugin also no longer in the Repo(If it ever was)
Download link here: https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AutoPlayGifs doesnt work
seems like its no longer supported?

**Comment by rauenzi** [comment]
I didn't add it to the website because it was broken by the time the website went up. It's not that it's unsupported per se, but my time is spread thin and I don't know when I'll be able to get to it.

**Comment by misterpyrrhuloxia** [comment]
Same problem for me. The only gifs that autoplay properly for me are server icons and animated emojis that are part of a person's Discord status.

**Comment by rauenzi** [comment]
Fixed by https://github.com/rauenzi/BetterDiscordAddons/pull/441
