### ISSUE TITLE
[Bug] [Autoplaygif] dont auto play profiles anymore

### ISSUE THREAD

**Issue by AMTitan** [rauenzi/BetterDiscordAddons#414]
**Which plugin/theme is this about?**
Autoplaygif

**Describe the Bug**
it does not autoplay profile pictures anymore

**Comment by hauntingly** [comment]
Having the same issue as well.

**Comment by misterpyrrhuloxia** [comment]
I'm having the same problem too.

**Comment by SigurdNorris** [comment]
Me too

**Comment by dav1312** [comment]
@hauntingly @misterpyrrhuloxia @SigurdNorris 
Saying "Me too" or "Same" or similar things **doesn't provide any additional information** about the issue.
**Please avoid doing that.**

**Comment by misterpyrrhuloxia** [comment]
> **Please avoid doing that.**
Why? How is it a problem to have people comment saying they have the same issue?

**Comment by rauenzi** [comment]
It provides no additional information and ends up cluttering the issue. If you have the same problem but no additional information to add, react with a :+1: to the original issue.

**Comment by Damyray** [comment]
Aye so did you disable being able to download it since its bugged right now?

**Comment by Vatis002** [comment]
Ayo, I downloaded it today because I had same problems as you all since yesterday. It has launched normally, all settings are on "on". It is working only with GIFs in server's avatars on server list. The friends GIF avatars on friends list, list of people on servers and GIF avatars in chat aren't working. Hope it will help somehow, greetings!

**Comment by Damyray** [comment]
> Ayo, I downloaded it today because I had same problems as you all since yesterday. It has launched normally, all settings are on "on". It is working only with GIFs in server's avatars on server list. The friends GIF avatars on friends list, list of people on servers and GIF avatars in chat aren't working. Hope it will help somehow, greetings!

Did you click the link to download it? Cause it don't work for me

**Comment by Vatis002** [comment]
> 
> 
> > Ayo, I downloaded it today because I had same problems as you all since yesterday. It has launched normally, all settings are on "on". It is working only with GIFs in server's avatars on server list. The friends GIF avatars on friends list, list of people on servers and GIF avatars in chat aren't working. Hope it will help somehow, greetings!
> 
> Did you click the link to download it? Cause it don't work for me

Well, I downloaded the whole code and found the right file for this plugin.

**Comment by AMTitan** [comment]
If you have nothing to say that is helpful then don't reply

**Comment by rauenzi** [comment]
Fixed by https://github.com/rauenzi/BetterDiscordAddons/pull/441
