### ISSUE TITLE
Send button not showing [Bug] 

### ISSUE THREAD

**Issue by KK-Designs** [rauenzi/BetterDiscordAddons#415]
**Which plugin/theme is this about?**
sendButton

**Describe the Bug**
When i download the send button plugin it doesn't show up idk why

**To Reproduce**
Install the plugin

**Expected Behavior**
The Send button is supposed to show up in type bar

**Screenshots**
N/A

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by rauenzi** [comment]
Can you show that it is installed? How about enabled?

**Comment by KK-Designs** [comment]
Its enabled for sure i manually enable it its still enabled rn

**Comment by rauenzi** [comment]
Can you show some screenshots of this? That would help alleviate concerns such as versions

**Comment by KK-Designs** [comment]
no send button
![image](https://user-images.githubusercontent.com/71038229/121124305-8e0d5080-c7d9-11eb-8f5d-3c0743f8886c.png)

**Comment by rauenzi** [comment]
Try disabling your theme, it is still working for me 
![image](https://user-images.githubusercontent.com/6865942/121125029-da658a00-c7f3-11eb-83ca-1a131522b1ef.png)

**Comment by KK-Designs** [comment]
yeah it is the theme, maybe try making it compatible with others?

**Comment by rauenzi** [comment]
It is generally compatible, but in some cases--such as this one--the theme needs to adjust it to fit, not the other way around.
