### ISSUE TITLE
[Bug] [DoNotTrack]

### ISSUE THREAD

**Issue by AsheIsAmazing** [rauenzi/BetterDiscordAddons#417]
**Which plugin/theme is this about?**
DoNotTrack.

**Describe the Bug**
When the Stop Process Monitor setting is turned on and discord is restarted, the process monitor will be running again. This can be alleviated by turning the setting off and on again each time discord is restarted. 

**To Reproduce**
Turn the Stop Process Monitor setting on, exit discord, then launch it. The Process Monitor will be active again.

**Expected Behavior**
The Process Monitor should turn off once the plugin is loaded.

**Screenshots**
![example](https://user-images.githubusercontent.com/86018647/122272317-c4f30d00-cf23-11eb-8355-9a7951ef2192.png)

**Discord Version**
Stable.

**Comment by PikminRed** [comment]
I'm still seeing this problem as well.

**Comment by nullKomplex** [comment]
Still identically broken with the latest update.
