### ISSUE TITLE
RadialStatus circle leftover on avatar

### ISSUE THREAD

**Issue by slashiee** [rauenzi/BetterDiscordAddons#42]
Ever since a recent Discord update, there's a circle leftover on all avatars.
![2018-02-24_18-15-52](https://user-images.githubusercontent.com/15317421/36637350-33f6ba4c-198f-11e8-8545-9e07cbb8edf6.png)
![2018-02-24_18-18-59](https://user-images.githubusercontent.com/15317421/36637351-356151e4-198f-11e8-8603-84ce100a4fbb.png)
![2018-02-24_18-19-24](https://user-images.githubusercontent.com/15317421/36637353-3fc42aa8-198f-11e8-994d-40ea21d2a9e3.png)

I'm sure you're fully aware of this, but nobody has made an issue on this yet.

**Comment by rauenzi** [comment]
I'm a bit behind on updating my themes but I will get around to this

**Comment by Inve1951** [comment]
this should fix it, just add it to your custom css for now
```CSS
.mask-2vyqAW {
  -webkit-mask: none !important;
}
```

**Comment by TadEro** [comment]
thank you for the CSS, though it would be cool not to do it

**Comment by rauenzi** [comment]
Thanks for closing, I forgot to do it myself
