### ISSUE TITLE
[Bug] Emoji selector category filter not jumping to correct category

### ISSUE THREAD

**Issue by Hype365** [rauenzi/BetterDiscordAddons#421]
**Which plugin/theme is this about?**
EmojiUtilities and HideDisabledEmojis

**Describe the Bug**
When having both plugins enabled concurrently, the category selector on the left side doesn't show the correct categories. Whichever one you select will show the category after it instead.

**To Reproduce**
Install and enable both plugins concurrently
Open emoji selector
Select a category from the left side
Look at what category it scrolled to

**Expected Behavior**
Emoji category filters to show correct categories when selected.

**Screenshots**
Just EmojiUtilities enabled: https://i.imgur.com/uzi5cPr.png
Just HideDisabledEmojis enabled: https://i.imgur.com/1wFAA5x.png
Both plugins enabled: https://i.imgur.com/G3TRlRL.png

**Discord Version**
Stable

**Comment by rauenzi** [comment]
The other plugin was discontinued
