### ISSUE TITLE
[Bug][BetterRoleColors] The colors of user roles are not displayed correctly in voice channels when back navigation

### ISSUE THREAD

**Issue by HMLarsen** [rauenzi/BetterDiscordAddons#422]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
The colors of user roles are not displayed correctly in voice channels when back navigation.

**To Reproduce**
1. Enter in the server clicking in the icon server, the roles color are shown properly.
2. Enter in another server (clicking in its icon).
3. Back to server cited in item 1 with back navigation ("ALT + <" or buttons in the mouse, like back in the browser history).
4. The roles color will not be shown correctly.

**Expected Behavior**
The roles color be shown correctly in voice channels when accessing any server, by any shortcut and not only click in its icon.

**Screenshots**
Correctly roles color when accessing the server.
![image](https://user-images.githubusercontent.com/24483593/122978134-8b2f6580-d36c-11eb-9af1-9e75646278b0.png)

Incorrectly roles color when accessing the server with other shortcuts (like "ALT + <" navback).
![image](https://user-images.githubusercontent.com/24483593/122978293-bc0f9a80-d36c-11eb-91d8-860de66ddf3b.png)

**Discord Version**
Stable 88296 (985e864)
BetterDiscord 1.1.1
Host 1.0.9002
Windows 10 64-Bit (10.0.19043)

**Comment by rauenzi** [comment]
This should be fixed
