### ISSUE TITLE
[Bug] PermissionsViewer

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#424]
**Which plugin/theme is this about?**
PermissionsViewer 

**Describe the Bug**
Show in popouts setting doesn't work
Doesn't display the permissions in the modal

**Screenshots**
![image](https://user-images.githubusercontent.com/63931154/123434052-5ae60200-d5cc-11eb-8a3c-2f6280373bd7.png)
![image](https://user-images.githubusercontent.com/63931154/123434113-6afde180-d5cc-11eb-92f7-4ab2260d351c.png)

![image](https://user-images.githubusercontent.com/63931154/128791520-6e32928e-a5a6-43b6-9e24-58dc4e463635.png)

**Discord Version**
All

**Comment by Tharki-God** [comment]
its because discord updates user popouts

**Comment by PatrickSantoZZ** [comment]
same here.

**Comment by dav1312** [comment]
> same here.

@PatrickSantoZZ Please avoid low quality comments like those, if you have the same issue just react with 👍 to the issue
