### ISSUE TITLE
[Bug] PLUGIN/STATUSEVERYWERE

### ISSUE THREAD

**Issue by nexioss** [rauenzi/BetterDiscordAddons#425]
**Describe the Bug**
dont work at all.

**To Reproduce**
just installe the plugin and acivate it.

**Expected Behavior**
adding the statue directly on the chat.

**Screenshots**
![Capturnge](https://user-images.githubusercontent.com/86494178/123524236-1f7d2d80-d6c9-11eb-8cd1-1900863944bf.PNG)

**Discord Version**
Stable 88806 (ec5c1a3)

**Additional Context**
none

**Comment by dav1312** [comment]
Duplicate of #366

**Comment by rauenzi** [comment]
See above
