### ISSUE TITLE
[Bug] RoleMembers crash

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#426]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
Discord crashes when clicking a member

**To Reproduce**
Role members > role > click user

**Screenshots**
![image](https://user-images.githubusercontent.com/63931154/123550670-f44d1980-d76e-11eb-85b9-c6f1183f0241.png)

**Discord Version**
All

**Comment by QbDesu** [comment]
Should be fixed now with the latest update of ZeresPluginLibrary (Ctrl+R to force checking for updates)
