### ISSUE TITLE
[Bug] [RoleMembers] List of members is not complete

### ISSUE THREAD

**Issue by Sevenyx** [rauenzi/BetterDiscordAddons#429]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
Plugin is not displaying all members belonging to that role.
At times, it only displays online members possessing the role.
At other times, it displays a mixture of online and a few offline members, but the offline members incorrectly appear as online in the preview list.
In either case, the list is neither accurate nor complete.

**To Reproduce**
Use the plugin as advertised.

**Expected Behavior**
View a list of members in a server that have a particular role, not just those that are online, and have them correctly displayed as online or offline.

**Screenshots**
n/a

**Discord Version**
Stable

**Additional Context**
n/a

**Comment by TheEvasion** [comment]
Same for me.

**Comment by dav1312** [comment]
> Same for me.

@TheEvasion Please avoid low quality comments like those, if you have the same issue just react with 👍 to the issue

**Comment by rauenzi** [comment]
This is a limitation by Discord. I can only show the list of users that Discord has loaded in. Typically Discord avoids loading offline users when possible.

It is theoretically possible to force Discord to load all members but that causes increased memory usage and increased API usage so I will not be adding that to the plugin.
