### ISSUE TITLE
TransientMaterial doesn't show background on user profiles in streamer mode

### ISSUE THREAD

**Issue by slashiee** [rauenzi/BetterDiscordAddons#43]
TransientMaterial disabled:
![2018-04-08_17-00-33](https://user-images.githubusercontent.com/15317421/38474075-61fd2d0a-3b4e-11e8-856e-0a7af4c6a76b.png)

TransientMaterial enabled:
![2018-04-08_16-45-22](https://user-images.githubusercontent.com/15317421/38474077-640da64c-3b4e-11e8-9335-f6d50aef8407.png)

**Comment by rauenzi** [comment]
Hmmm I may have messed that up on beard's theme as well. Will look into it after dinner
