### ISSUE TITLE
[Feature] Add github gui please!!

### ISSUE THREAD

**Issue by ironboy36** [rauenzi/BetterDiscordAddons#431]
Please add a github text gui I would thank you very much if you add a github text gui onto discord 
![Screen Shot 2021-07-05 at 3 47 14 AM](https://user-images.githubusercontent.com/77495097/124436832-6790f580-dd44-11eb-9bd6-f7e1ab6bf611.png)

**Comment by rauenzi** [comment]
I think this is an interesting suggestion, but I'm not taking on new plugins at this time
