### ISSUE TITLE
[Bug] Permissions Viewer - Show In Popouts

### ISSUE THREAD

**Issue by MuhaGX** [rauenzi/BetterDiscordAddons#432]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by MuhaGX** [comment]
![image](https://user-images.githubusercontent.com/70599137/124471416-08c09000-ddc7-11eb-92a2-73f13a8afc8c.png)

**Comment by MuhaGX** [comment]
Why is the role permission not showing

**Comment by MuhaGX** [comment]
Why is the role permission not showing?

**Comment by dav1312** [comment]
Duplicate of #424
