### ISSUE TITLE
[Bug] AutoPlayGifs Bug

### ISSUE THREAD

**Issue by sonitaaaaa** [rauenzi/BetterDiscordAddons#434]
**Which plugin/theme is this about?**
**AutoPlayGifs Plugin**

**Describe the Bug**
Does not auto play on Memberlist, Chat

**Expected Behavior**
It should play gif on Chat, Memberlist

**Screenshots**
![image](https://user-images.githubusercontent.com/40225192/125186079-7b5fbe80-e252-11eb-86a8-e60d1ddc8ba4.png)

**Discord Version**
Stable 89709 (8d00f68)
BetterDiscord 1.2.0

**Additional Context**
None

**Comment by dav1312** [comment]
## Please check if this is already an open issue before opening a new one.

![image](https://user-images.githubusercontent.com/63931154/125202262-12d50980-e273-11eb-97a5-0ddd332124b4.png)

**Comment by sonitaaaaa** [comment]
oh right, I forgot. Thanks
