### ISSUE TITLE
[Bug] ZeresPluginLibrary Update Crashes Discord

### ISSUE THREAD

**Issue by SexyNippleKiller** [rauenzi/BetterDiscordAddons#435]
**Which plugin/theme is this about?**
ZeresPluginLibrary

**Describe the Bug**
Crashes discord when updating to latest Version(1.2.31)

**Comment by anthony1x6000** [comment]
You figure out what was causing it? Same thing is happening to me

**Comment by rauenzi** [comment]
Reinstall BD
