### ISSUE TITLE
[Bug] RoleMembers completely broken

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordAddons#439]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
Neither mentions (issue #281) nor the context menu work

**Screenshots**
Context menu issue
![image](https://user-images.githubusercontent.com/63931154/126044153-31bedfff-522d-4af7-8ede-7cec00ad4d5e.png)

![image](https://user-images.githubusercontent.com/63931154/126044133-3589da5d-ece2-4a1e-b9f2-c7376764ef34.png)

**Discord Version**
Stable and Canary

**Comment by PatrickSantoZZ** [comment]
same here

**Comment by PatrickSantoZZ** [comment]
Yes RoleMembers Plugin isnt working at all anymore. 
Its not working since around 5 days. So i cant really say exacly which update broke it.

**Comment by TheEvasion** [comment]
Same for me.

**Comment by dav1312** [comment]
> Same for me.

@TheEvasion Please avoid low quality comments like those, if you have the same issue just react with 👍 to the issue

**Comment by Leanny** [comment]
The problem seems to be that `Pill` cannot be grabbed properly anymore (so `patchRoleMention` will crash). As a workaround you can delete line 134 (`this.patchRoleMention()`) and the plugin will load + give you the context menu when you click on a guild

**Comment by acendvgnt** [comment]
Discord is experimenting with role pop-outs on their own it seems. 
![image](https://user-images.githubusercontent.com/85397982/126167442-4b0ced26-c910-4cb9-9d51-4835867229bb.png)
Their pop-out has no search function but it's basically the same as this plugin just without the server context menu. Thought y'all ought to know.

**Comment by Divoret** [comment]
> Discord is experimenting with role pop-outs on their own it seems.
> ![image](https://user-images.githubusercontent.com/85397982/126167442-4b0ced26-c910-4cb9-9d51-4835867229bb.png)
> Their pop-out doesn't have a search function but it's basically the same as what this plugin does just without the server context menu. Thought y'all ought to know.

How do I use the role pop outs? I have the discord experiments plugin, and I can see it. But when I select "treatment 1", what do I do then? How do i then use it?

**Comment by dav1312** [comment]
> How do I use the role pop outs? I have the discord experiments plugin, and I can see it. But when I select "treatment 1", what do I do then? How do i then use it?

@Divoret Just click on a role mention (e.g. @ everyone)

**Comment by Divoret** [comment]
> > How do I use the role pop outs? I have the discord experiments plugin, and I can see it. But when I select "treatment 1", what do I do then? How do i then use it?
> 
> @Divoret Just click on a role mention (e.g. @ everyone)

thanks, it worked. Only problem is, the role has to be mentioned in the discord server for me to click on it and check. :(
