### ISSUE TITLE
BetterFormattingRedux No arrow

### ISSUE THREAD

**Issue by waykai** [rauenzi/BetterDiscordAddons#442]
Whenever i use the plugin it just dosent work. I use other plugins and they work fine but when i use the BetterFormattingRedux it just dosent work the slightest. The arrow is gone.
![Skärmbild 2021-07-21 071146](https://user-images.githubusercontent.com/47532455/126434359-c0c6b294-b7b8-4968-a55a-58e4460698b9.png)

**Comment by rauenzi** [comment]
This is an issue with your theme
