### ISSUE TITLE
[Bug] [BetterFormattingRedux] The GUI doesn't work but 

### ISSUE THREAD

**Issue by BuyMyMojo** [rauenzi/BetterDiscordAddons#443]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
The GUI doesnt work on the messages at all (with and without theme) but the wrapper option still works just fine

**To Reproduce**
install it I think?

**Expected Behavior**
the GUI to apply wrapper?

**Screenshots** (Have a gif instead)
![GuiNoWork](https://user-images.githubusercontent.com/46948241/126752629-2f94f1df-c626-4c95-9e7a-d4fc9e1a0d8f.gif)

**Discord Version**
Stable 90699 (baa844b)
BetterDiscord 1.2.0
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

**Additional Context**
Tried in both DM and on servers

**Comment by waykai** [comment]
This is also happening to me i tried reinstalling but that didnt work. Even without gui still dosent work

**Comment by adi170-alt** [comment]
same...

**Comment by Quower** [comment]
same

**Comment by HvidGut** [comment]
Same dude

**Comment by GmeX1** [comment]
Same

**Comment by Wolf11221** [comment]
same

**Comment by BlueStarBRS** [comment]
same

**Comment by rauenzi** [comment]
Fixed at latest version
