### ISSUE TITLE
[Feature] Please add seperatetely toggleable options for showing status

### ISSUE THREAD

**Issue by raffel080108** [rauenzi/BetterDiscordAddons#446]
**Which plugin/theme is this about?**

StatusEverywhere
**Is your feature request related to a problem? Please describe.**

Not really, I just have a request for custumizability
**Describe the feature you'd like**

I would like, that you have the option to toggle on and off where statuses are visible seperately from each other.

**Comment by rauenzi** [comment]
Due to my own time management issues I am starting to offload some of my plugins starting with StausEverywhere. You can find the new maintained version by @Strencher here: https://betterdiscord.app/plugin/StatusEverywhere
