### ISSUE TITLE
PermissionsViewer not working

### ISSUE THREAD

**Issue by fabsch2003** [rauenzi/BetterDiscordAddons#449]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
The plugin loads, but the ability for viewing user's and role's permissions don't work anymore

**To Reproduce**
Just try to view a channels permissions or a user's / role's permissions

**Expected Behavior**
You can see the permissions

**Screenshots**
![image](https://user-images.githubusercontent.com/64209114/127988588-8426a6bd-ac69-4c74-bb7c-121c4a1961cd.png)

**Discord Version**
Stable, PTB, Canary

**Additional Context**
All plugins are up-to-date, including BDFDB and ZeresPluginLibrary

**Comment by acendvgnt** [comment]
Duplicate of #424

**Comment by rauenzi** [comment]
Please see above
