### ISSUE TITLE
[Other] How to install?

### ISSUE THREAD

**Issue by B2SF2W** [rauenzi/BetterDiscordAddons#450]
Hello yes im new to this whole github thing, how do i install this on my betterdiscord?

**Comment by MorsHs** [comment]
Go To Discord Settings and Click the Plugin Tab
Next is click "Open Plugin Folder" and Drag the Plugin to that folder and it should work.

Sometimes the search button will be gone if u restart discord and you can enable it again by turning off/on the plugin again

**Comment by rauenzi** [comment]
Please see the above
