### ISSUE TITLE
Weird grouping in the way the context item is added

### ISSUE THREAD

**Issue by Farcrada** [rauenzi/BetterDiscordAddons#452]
https://github.com/rauenzi/BetterDiscordAddons/blob/38cd17c7e8dad92775aa754d493755b6a119585b/Plugins/PermissionsViewer/PermissionsViewer.plugin.js#L561

https://github.com/rauenzi/BetterDiscordAddons/blob/38cd17c7e8dad92775aa754d493755b6a119585b/Plugins/PermissionsViewer/PermissionsViewer.plugin.js#L571

This creates a conflicts depicted and mentioned here: https://github.com/Echological/MentionChannels-BD/issues/2
I have a suspicion this is related, but I might be entirely wrong: https://github.com/rauenzi/BDPluginLibrary/issues/92 ( I probably am).

**Comment by rauenzi** [comment]
I read a bit about this (and the other issue you had opened) while I was at work today and I just want to note to you and I guess @Echological that the type `Text` is not valid. `text` however is as per the docs.

That said I do think this is more likely a collision with PV than an issue with the library creating a sub menu for an invalid type input.

**Comment by rauenzi** [comment]
With how radically the context menus have changed please reopen if the collision still occurs
