### ISSUE TITLE
[Bug] Status everywhere not displaying on some elements 

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#453]
**Which plugin/theme is this about?**
Statuséverywhere plugin

**Describe the Bug**
status is not showing on my self and not on answer boxes on my self

**To Reproduce**
answer someone and you will see how this happening and this bug o self its just happens over and over after a time

**Expected Behavior**
i see my self online and thats the statuses dont load slow sometimesin chat

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/128930432-0314d337-0ab0-4435-93e3-348ac8e50c66.png)

**Discord Version**
latest one

**Comment by rauenzi** [comment]
Due to my own time management issues I am starting to offload some of my plugins starting with StausEverywhere. You can find the new maintained version by @Strencher here: https://betterdiscord.app/plugin/StatusEverywhere

**Comment by BlueStarBRS** [comment]
wow what a fixthx now i must make a bug report again... bruh


just for the log:

if you are adk and go back to online (auto afk) you are not seeing your self online so this is a bug too like  the bug above.
