### ISSUE TITLE
PFPs dont auto play

### ISSUE THREAD

**Issue by itsben69** [rauenzi/BetterDiscordAddons#455]
gif profile pictures dont autoplay in dms or servers altho emotes and profile pics in members and server icons do auto play

**Comment by rauenzi** [comment]
What version of the plugin are you using? Most of the ones you mentioned are animated for me

**Comment by Hoopticoupe** [comment]
i am not sure if another plugin is overriding the avatars, but they dont play in the chat for me. all others options work. latest version

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
