### ISSUE TITLE
[Bug] The search buttons are multiplying

### ISSUE THREAD

**Issue by DhruvMitna** [rauenzi/BetterDiscordAddons#456]
**Which plugin/theme is this about?**
Server Search

**Describe the Bug**
Whenever I click the server search button, 2 more buttons appear on the server sidebar and 1 button is added everytime I switch servers.

**To Reproduce**
1. Click the server search button or switch to another server.

**Expected Behavior**
The expected behaviour is that it should be used to search for a particular server in your server list. It does that, but it also adds 2 extra search buttons, and after a couple of uses, you have to scroll a lot to open a server.

**Screenshots**
![ScreenShot_20210811080103](https://user-images.githubusercontent.com/75002001/128961053-a23db775-8906-42fb-af41-64f06dd3317e.png)

**Discord Version**
Stable

**Additional Context**
This started happening after the latest update where it fixed the icon.

**Comment by Strencher** [comment]
Can you try this version out? https://github.com/Strencher/BetterDiscordAddons/blob/patch-3/Plugins/ServerSearch/ServerSearch.plugin.js It's a version that should fix the issue.

**Comment by DhruvMitna** [comment]
![ScreenShot_20210811083843](https://user-images.githubusercontent.com/75002001/128963552-7f345d32-b676-4adb-af5b-c7c8e0c72094.png)
