### ISSUE TITLE
[Bug] [BetterFormattingRedux] - leet & thicc auto toggles to false on refresh

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [rauenzi/BetterDiscordAddons#460]
@rauenzi 
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
The Leet & thicc toggles in toolbar keep turning off on every discord refresh or restart.

**To Reproduce**
just toggle to On/True & Refresh discord

**Expected Behavior**
to stay On/True after refresh

**Screenshots**
Video: https://www.dropbox.com/s/d282spe21uuekcg/Formatng-AutoFalse.mp4?dl=0 (to big to upload on github)
![Screen Shot 2021-08-18 at 6 34 04 pm](https://user-images.githubusercontent.com/2242880/129865957-34620729-f736-4575-b864-22f28c8ecf24.jpg)
Keeps turning off in the toolbar & settings every time I refresh or restart discord.

**Discord Version**
Stable

**Comment by omega1084** [comment]
Getting this as well.

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
