### ISSUE TITLE
[Bug] RoleMembers not working AGAIN. Maybe something new changed in Discord?

### ISSUE THREAD

**Issue by Divoret** [rauenzi/BetterDiscordAddons#462]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
RoleMembers only displays the context menu, but doesn't show the members even when you click on a role. I think something changed in Discord again or something that broke RoleMembers AGAIN. Please fix this pls

**To Reproduce**
Download latest version of role members, go to a server, right click the servers, click on role members, now the roles will display, but when you click on any role, nothing happens. It doesn't show the members of that role because nothing happens. This seems to be a new error, because a week ago or so rolemembers was working, and not suddenly it isn't. Maybe something in discord changed slightly again?

**Expected Behavior**
I expected the rolemembers to show the roles AND the people in the roles. Pls fix. thx in advance

**Discord Version**
Discord Stable Version or the normal version basically

**Comment by yungsamd17** [comment]
Doesn't work for me either

**Comment by spadesjack** [comment]
same

**Comment by Spacelag** [comment]
same

**Comment by rauenzi** [comment]
Comments like this are not helpful, in the future add a 👍 to the original issue if you are also experiencing it and have nothing further to add to the discussion.

**Comment by ViktoriaLuise** [comment]
seems to be an issue with DiscordClasses.Popouts.popout.add not being a function, which is causing the error. At least that's what the debug says

**Comment by someone19204** [comment]
> **Which plugin/theme is this about?**
> RoleMembers
> 
> **Describe the Bug**
> RoleMembers only displays the context menu, but doesn't show the members even when you click on a role. I think something changed in Discord again or something that broke RoleMembers AGAIN. Please fix this pls
> 
> **To Reproduce**
> Download latest version of role members, go to a server, right click the servers, click on role members, now the roles will display, but when you click on any role, nothing happens. It doesn't show the members of that role because nothing happens. This seems to be a new error, because a week ago or so rolemembers was working, and not suddenly it isn't. Maybe something in discord changed slightly again?
> 
> **Expected Behavior**
> I expected the rolemembers to show the roles AND the people in the roles. Pls fix. thx in advance
> 
> **Discord Version**
> Discord Stable Version or the normal version basically

by the way, left clicking on roles (when in chat) does not work aswell

**Comment by jack652** [comment]
doesn't work for me either

**Comment by StupidRepo** [comment]
> Comments like this are not helpful, in the future add a 👍 to the original issue if you are also experiencing it and have nothing further to add to the discussion.

We've aded 38 :+1:'s now. Hurry up and fix it.

**Comment by bossev** [comment]
> > Comments like this are not helpful, in the future add a 👍 to the original issue if you are also experiencing it and have nothing further to add to the discussion.
> 
> We've aded 38 👍's now. Hurry up and fix it. It's been so long.

47 👍s now - still nothing...

**Comment by rauenzi** [comment]
Comments like these also don't help. A fix is being released this weekend.

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
