### ISSUE TITLE
permissionsviewer user popout bug

### ISSUE THREAD

**Issue by someone19204** [rauenzi/BetterDiscordAddons#463]
**Which plugin/theme is this about?**
permissionsviewer

**Describe the Bug**
user permissions in popouts dont show

**To Reproduce**
1. go to a server 2. LMB click on an user

**Expected Behavior**
it would show total permissions of the user

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/88501829/130964087-f8b26df0-5ad8-472b-896f-63b88352cd8a.png)

**Discord Version**
stable

**Additional Context**
probably discord updated popouts again

**Comment by notpbj** [comment]
bump cause I'm having the same issue

**Comment by someone19204** [comment]
got fixed
