### ISSUE TITLE
[Feature] PermissionsViewer administrator checkbox idea

### ISSUE THREAD

**Issue by Whywhywhyyyy** [rauenzi/BetterDiscordAddons#464]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the feature you'd like**
Could all the checkboxes in the permissions list be ticked if the user has administrator permissions, might just help with people who didn't notice when the administrator checkbox was ticked. 

**Additional context**
Thank you for all the mods you made, hope you have a great day :)

**Comment by rauenzi** [comment]
I don't think this is a good idea, it's important to accurately represent the configuration.
