### ISSUE TITLE
Discord still tracks what Games are played.

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [rauenzi/BetterDiscordAddons#465]
DoNotTrack v0.07
Plugin activated yet Discord still tracks what games are played.
Everything on Discord is up to date Libraries etc.

![Screenshot 2021-09-03 171401](https://user-images.githubusercontent.com/31579027/132028441-34d4612d-1b00-4f32-b0c8-64b5cc8d3e37.png)

![Screenshot 2021-09-03 171605](https://user-images.githubusercontent.com/31579027/132028613-6f31f2e6-40b7-4d7c-af5a-287094b2ce4f.png)

**Comment by Hate9** [comment]
Same here. I'm on Linux, idk about the OP.

**Comment by arrowgent** [comment]
you can sandbox discord with tools like firejail to prevent application tracking
