### ISSUE TITLE
[Bug] ServerSearch doesn't work

### ISSUE THREAD

**Issue by Maruhai** [rauenzi/BetterDiscordAddons#466]
**Which plugin/theme is this about?**
ServerSearch v0.1.8

**Describe the Bug**
The Search button doesn't do anything.

**To Reproduce**
Click on the search button.

**Expected Behavior**
The Search popup list appears.

**Screenshots**

**Discord Version**
Stable 96967 (648fbd8)
BetterDiscord 1.2.1
Host 1.0.9002 Windows 10 64-Bit (10.0.19042)
ZeresPluginLibrary v1.2.32

**Additional Context**
It used to work until the most recent PluginLibrary update

**Comment by BaranKral** [comment]
i already updated the pluginlibrary when i click the search button nothing happen

**Comment by ddivito** [comment]
same here

**Comment by ddivito** [comment]
Discord Version
Stable 98381 (96e4f5d)
BetterDiscord 1.2.1
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

ZeresPluginLibrary
v1.2.32by Zerebos

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
