### ISSUE TITLE
[Bug] [RoleMembers] Broken

### ISSUE THREAD

**Issue by ev3nvy** [rauenzi/BetterDiscordAddons#467]
RoleMembers plugin seems to be broken, because popup in BDPluginLibrary no longer works.

**Comment by RayuCALDERA** [comment]
Can u fix this please @rauenzi

**Comment by acendvgnt** [comment]
#462 ?

**Comment by hjjcnk** [comment]
This is something I've noticed for over a month now, but I never posted about it cause I didn't have a github. I just made one today. It will show me all the roles of a server, yes, but when I click those roles, nothing happens, and I can no longer see the role members, so I have to manually go down the server member list and click every profile to see the roles, which is sort of what I was trying to avoid doing by getting this plugin.

**Comment by RayuCALDERA** [comment]
> #462 ?

?

**Comment by ev3nvy** [comment]
issue is a duplicate of #462, I forgot to check before opening an issue, will be closing this one, so follow that one
