### ISSUE TITLE
RoleMembers doesn't show members for any role [Bug] 

### ISSUE THREAD

**Issue by 0ember1** [rauenzi/BetterDiscordAddons#474]
**RoleMembers plugin**

**When pressing on a role in RoleMembers plugin, it doesn't show members of this role**

**Right click on any server icon. Then point on "Role Members", and try pressing on any role. It. It does nothing**

**After pressing on a role plugin was supposed to show me all members who had this role on the server, but that didn't happen.**

**Can't screenshot only video - https://cdn.discordapp.com/attachments/870912110849302590/893778955390300201/rolemembers2.mp4**

**Stable**

**Comment by TheEvasion** [comment]
https://github.com/rauenzi/BetterDiscordAddons/issues/462

Been like this for a couple months. Seems like support for the plugin has stopped

**Comment by SteffoSpieler** [comment]
![grafik](https://user-images.githubusercontent.com/41108856/137597301-3c1c4a40-7ba8-4522-bc16-311f779d57d5.png)
This error is showing in the console.

**Comment by TheHunter1234** [comment]
I am getting the same issue as well.

**Comment by PatheticMustan** [comment]
I can confirm, I also have the same issue with the latest plugin.
![image](https://user-images.githubusercontent.com/35382971/141660488-5417dcbd-12ba-4c95-a04b-dd5b7b1910ad.png)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
