### ISSUE TITLE
[RoleMembers] You can still somewhat make use of it

### ISSUE THREAD

**Issue by teisseire117** [rauenzi/BetterDiscordAddons#476]
EDIT:
check out #485 , I fixed the plugin. It's not going to be as beautiful as it was, but at least it's working.
Here's how it looks like : 

![bpPGljg](https://user-images.githubusercontent.com/43145883/139229559-233d2936-0888-4bf5-a4f5-04403feb0e4f.png)

~What's not working is the display of the popout, but the plug-in still find the users from the roles you want.
So you open the .js of the plug-in, you add `console.log(members)` like in the screenshot below
![6L8xBtN](https://user-images.githubusercontent.com/43145883/136596177-bba81c3e-202e-4a9c-ac4e-1ced836c2d20.png)~

~Then it'll show you the result in the console : 
![nN9qjOg](https://user-images.githubusercontent.com/43145883/136596329-ae90f31c-c018-4677-a566-5c919a760d4e.png)
after you click the role :
![8chHsLD](https://user-images.githubusercontent.com/43145883/136596965-35751014-21ed-433a-a8b1-844b92c8ec8d.png)~
 
~No more fancy popout but at least you can still find what you're looking~

**Comment by TheHunter1234** [comment]
I am getting the sam issue as well.

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
