### ISSUE TITLE
Better role colours flashing

### ISSUE THREAD

**Issue by Bowtell** [rauenzi/BetterDiscordAddons#478]
Hey, so recently I have noticed that people's names when im in the call with them will flash. It sort of looks like they are going from bold to non bold. 
It's not when they are speaking either, Seems to happen at random.

https://user-images.githubusercontent.com/6972491/136651413-76171289-d964-48b9-8be4-1fe4c036e3ad.mp4

Any help would be appreciated, I really like this plugin and would hate to have to disable it :(

**Comment by InFlamesGO** [comment]
Same
Stable 103255 (ae3387d)
BetterDiscord 1.2.4

**Comment by rauenzi** [comment]
Can you try adding this to your custom css and see if this fixes your issue?

```
.usernameFont-2oJxoI {
    backface-visibility: hidden;
}
```

**Comment by Bowtell** [comment]
Yep fixed the issue.
Thanks!
