### ISSUE TITLE
[Bug] AutoPlayGifs doesn't allow disabling chat or guild because of a missing function.

### ISSUE THREAD

**Issue by EvelynProto** [rauenzi/BetterDiscordAddons#480]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
AutoPlayGifs doesn't allow disabling chat or guild because of a missing function.

**To Reproduce**
1. Install AutoPlayGifs
2. Try to disable chat or guild gifs in settings.

**Expected Behavior**
You should be able to disable them.

**Screenshots**
![image](https://user-images.githubusercontent.com/54776821/137949105-643f5f38-5e03-4c15-914d-4efbc4310d36.png)

**Discord Version**
Stable 101451 (BD 1.2.1)

**Comment by InFlamesGO** [comment]
Same
Stable 103255 (ae3387d)
BetterDiscord 1.2.4

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
