### ISSUE TITLE
[Feature] Blur NSFW Plugin Option For Blurring Spoiler Text

### ISSUE THREAD

**Issue by BigFlubba** [rauenzi/BetterDiscordAddons#482]
**Which plugin/theme is this about?**
Blur NSFW

**Describe the feature you'd like**
The option to have the same thing for spoiler text. I would like for the option for when you have a spoiler text it is blurred untitled hovered. I would like this to be a forced option, meaning even if you click on the message and you move your mouse elsewhere not hovering over it, it will still be blurred.

**Additional context**
The possibility for this to be a togglable setting, both blurring spoiler text and whether it is a forced blur (even after clicking over it and moving your mouse away from the text) or not.

**Comment by rauenzi** [comment]
I won't be adding this, spoilers are already feature-complete.
