### ISSUE TITLE
PermissionsViewer channel / category popout not working [Bug] 

### ISSUE THREAD

**Issue by someone19204** [rauenzi/BetterDiscordAddons#484]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
you cant view popouts

**To Reproduce**
1. use plugin
2. right-click on a channel

**Expected Behavior**
you see the "Permissions" button

**Screenshots**
trying to fix the line
![image](https://user-images.githubusercontent.com/88501829/138866155-ffc9d63f-be67-42b4-a67b-f13d149ed3e9.png)
![image](https://user-images.githubusercontent.com/88501829/138866252-33ea2368-2e8d-4efe-b881-910d8a6b7e07.png)
fresh version
![image](https://user-images.githubusercontent.com/88501829/138866405-5b53c200-e4e6-405a-8056-b86b955dd6f2.png)
![image](https://user-images.githubusercontent.com/88501829/138866427-c8d4631e-bc6c-42dc-af72-a4baa7525399.png)

**Discord Version**
stable

**Additional Context**
this issue was a long time ago

**Comment by someone19204** [comment]
> Thanks to Strencher <3 you can change the the line 576 and following with:
> 
> ```js
> const [, VoiceChannelContextMenu] = WebpackModules.findAll(m => m.default && m.default.displayName == "ChannelListVoiceChannelContextMenu");
> const [, TextChannelContextMenu, CategoryChannelContextMenu] = WebpackModules.findAll(m => m.default && m.default.displayName == "ChannelListTextChannelContextMenu");
> ```
> 
> Then it should work like expected

it worked, thanks

**Comment by KazamaSion** [comment]
I think this issue needs to be kept open cuz the issue is not fixed in the official script.

**Comment by Zigamus** [comment]
Apparently something has changed, but now even that doesn't work.
