### ISSUE TITLE
[Bug] PermissionsViewer not appearing on text & voice channel's context menu

### ISSUE THREAD

**Issue by d0gkiller87** [rauenzi/BetterDiscordAddons#486]
**Which plugin/theme is this about?**
PermissionsViewer v0.2.0

**Describe the Bug**
The `Permissions` option doesn't appear on text & voice channel's context menu.

**To Reproduce**
1. Install the plugin.
2. Right click on any text or voice channel. You won't see the option.

**Expected Behavior**
The option should appear on text & voice channel's context menu.

**Screenshots**
`(None)`

**Discord Version**
Discord Stable 103016 (54edf1f) + BetterDiscord 1.2.3

**Additional Context**
`(None)`

**Comment by acendvgnt** [comment]
This is why #484 shouldn't have been closed.

**Comment by ItzDShadow** [comment]
bug appears because of wrong modules order, untill the fix i suggest replacing the function with this variant:
`patchChannelContextMenu() {
            const [VUNUSED, VoiceChannelContextMenu] = WebpackModules.getModules(m => m.default && m.default.displayName == "ChannelListVoiceChannelContextMenu");
            // eslint-disable-next-line no-unused-vars
            const [UNUSED, TextChannelContextMenu, CategoryChannelContextMenu] = WebpackModules.getModules(m => m.default && m.default.displayName == "ChannelListTextChannelContextMenu");
            const patch = (_, [props], retVal) => {
                const original = retVal.props.children[0].props.children;
                const newOne = DCM.buildMenuItem({
                    label: this.strings.contextMenuLabel,
                    action: () => {
                        const channel = props.channel;
                        if (!Object.keys(channel.permissionOverwrites).length) return Toasts.info(`#${channel.name} has no permission overrides`);
                        this.showModal(this.createModalChannel(channel.name, channel, props.guild));
                    }
                });
                if (Array.isArray(original)) original.splice(1, 0, newOne);
                else retVal.props.children[0].props.children = [original, newOne];
            };
            this.contextMenuPatches.push(Patcher.after(CategoryChannelContextMenu, "default", patch));
            this.contextMenuPatches.push(Patcher.after(TextChannelContextMenu, "default", patch));
            this.contextMenuPatches.push(Patcher.after(VoiceChannelContextMenu, "default", patch));
        }`

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
