### ISSUE TITLE
[Bug] [AccountDetailsPlus] Settings modal does not change visible status without closing and re-opening dialog

### ISSUE THREAD

**Issue by bbeenn1** [rauenzi/BetterDiscordAddons#487]
**Which plugin/theme is this about?**
AccountDetailsPlus v0.1.10

**Describe the Bug**
While adjusting Settings for the plugin, the toggle switches do not visibly toggle, but the value does change and appears to be saved upon re-opening the Settings modal.

**To Reproduce**
Open Discord Settings --> Plugins list --> AccountDetailsPlus --> Settings button
Attempt to toggle any setting, it does not toggle.
Close the Plugin Settings modal, reopen it and the settings appear to have been changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5580320/139804995-ff83b0de-b674-4fed-824a-8958bfe1a0a4.png)
![image](https://user-images.githubusercontent.com/5580320/139805018-65997d4b-ea07-4f23-aebd-47bc0840a89a.png)

**Discord Version**
Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
