### ISSUE TITLE
[Bug] [AccountDetailsPlus] "Disabling" plugin results in error message "AccountDetailsPlus could not be stopped"

### ISSUE THREAD

**Issue by bbeenn1** [rauenzi/BetterDiscordAddons#488]
**Which plugin/theme is this about?**
AccountDetailsPlus v0.1.10

**Describe the Bug**
Discord--> Settings --> Plugins "toggle" the plugin from on to off and an error popup will be presented stating the plugin could not be stopped, enabling the toggle appears to start the plugin normally without error.

**Discord Version**
Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
