### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by p0pcat** [rauenzi/BetterDiscordAddons#489]
**Which plugin/theme is this about?**
 PermissionsViewer 

**Describe the Bug**
 Channel permissions do not show up 

**To Reproduce**
 right click on a channel 

**Expected Behavior**
when right clicking on the channel it should also contain "Permission" popup with other stuff 

**Screenshots**
:(

**Discord Version**
 Stable 

**Additional Context**
 idk I have a lot of other plugins maybe they could somehow influence but I don't think so, also category permissions works perfectly (singed up into GitHub specifically to report it lol, ill better looked through bugs before posting 💀)
 sry I forgot to read and it seems there is already a fix

**Comment by Dschogo** [comment]
#484

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
