### ISSUE TITLE
TransparencyPatcher Windows Snap Broken.

### ISSUE THREAD

**Issue by ScoPeZs** [rauenzi/BetterDiscordAddons#49]
Hello, I'm using TransparencyPatcher v0.0.2 when I enable it I lose the "Windows Snap" functionality.

Youtube vid showing it.
[https://www.youtube.com/watch?v=LUTSipqvr-0](url)

**Comment by intrnl** [comment]
Able to be reproduced with Windows 10 April 2018 Update (17134.rs4_release.180410-1804) as well.
This seems to be something that isn't officially supported by Chromium itself as indicated by [issue #2170](https://github.com/electron/electron/issues/2170#issuecomment-345571732) on Electron.

**Comment by rauenzi** [comment]
Yeah what he said, there's nothing I can do about that unfortunately.
