### ISSUE TITLE
[Bug][RemoveMinimumSize] Not working!

### ISSUE THREAD

**Issue by StupidRepo** [rauenzi/BetterDiscordAddons#490]
**Which plugin/theme is this about?**
RemoveMinimumSize

**Describe the Bug**
It seems that it isn't working. It keeps saying "RemMiniSize could not be started."

**To Reproduce**
Installing RemMiniSize, click on the Checkmark to enable.

**Expected Behaviour**
Should work.

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Please read https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/RemoveMinimumSize

**Comment by StupidRepo** [comment]
Oh, wait but how do I enable it in BD?
