### ISSUE TITLE
[Feature] [BetterRoleColors] Colorize specifically-matched bot messages

### ISSUE THREAD

**Issue by seylerius** [rauenzi/BetterDiscordAddons#491]
**Which plugin/theme is this about?**
_BetterRoleColors_

**Is your feature request related to a problem? Please describe.**
I'm on a lot of servers with plural friends, using bots like PluralKit and Tupperbox. Messages proxied by these bots colorize with default color, rather than author-account's role color. This is frustrating, because I wind up with these bright white messages in the middle of all the personal and colorful ones. 

**Describe the feature you'd like**
I'd like to be able to match specific "displayed names" by specific bots and map those to user accounts, triggering all the standard and configurable colorizing functions from there. For example, I could map the display name `Heather Jane 🖋` from PluralKit to the user `@TheHeathers#1234`, and the message would be colorized the same as if it was sent unproxied.

**Additional context**
This is a screenshot featuring a few messages proxied by PluralKit. The role color of my account (proxied as Sable) is `#9932CC`, and the role color of Evenstar (account behind the other two proxied messages) is visible there as `#FF69B4`.
![BRC-pluralkit-uncolorized](https://user-images.githubusercontent.com/1145981/141013301-bda473d0-c9a0-4062-b505-a5a38bd35839.png)

And here is an approximate recoloring in GIMP of the same screenshot, demonstrating roughly how my BetterRoleColors feature would ideally work.
![BRC-pluralkit-colorized](https://user-images.githubusercontent.com/1145981/141013770-27d2e83c-2234-400a-bdee-a08a9f3f49a1.png)

**Comment by rauenzi** [comment]
This is not something I will add to BRC as it is outside the scope. BRC would solely be for role colors, not for proxied stuff like this. And BRC _does not_ color message text. That is a BD feature.
