### ISSUE TITLE
[Bug] SendButton not working with experimental image send UI

### ISSUE THREAD

**Issue by TheChilliPL** [rauenzi/BetterDiscordAddons#492]
**Which plugin/theme is this about?**
SendButton

**Describe the Bug**
The send button doesn't send the message if there's just the image included and no text content in the experimental image sending UI.

**To Reproduce**
1. Ensure you have the experimental image send UI
    - You can turn it on by accessing the experiments menu (using plugins or scripts from the internet) and setting the bucket override of `2021-09_inline_attachment_uploads` to `Treatment 1`
2. Drag&drop, paste, or use the plus button to upload an image. It should be visible above the textbox.
3. Click the send button.

**Expected Behavior**
The attachments should get sent as if you pressed the Enter key.

**Screenshots**

<details>
<summary>Show screenshots</summary>

![image](https://user-images.githubusercontent.com/18823939/141075312-328475f2-e5da-419c-8798-1946f6b7798a.png)

</details>

**Discord Version**
Stable 104144  
BetterDiscord 1.2.4  
Windows 11 Pro Insider 22471.1000

**Additional Context**

―

**Comment by Vitoire** [comment]
I wanna "push" this up, because the feature is now live and the Send Button is not working when you attach pictures. If you don't attach pictures, it works just fine. 

Patiently waiting for a fix, just wanted to give an update on the situation!

**Comment by Eden333** [comment]
Ow, I thought I was the only one with this issue

**Comment by rauenzi** [comment]
This plugin has been discontinued and has been integrated by Discord.

**Comment by TisFoolish** [comment]
For those that don't know, you can now right click on the text message box
and enable the new send button there.
