### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dragonunitedtm** [rauenzi/BetterDiscordAddons#493]
**Which plugin/theme is this about?**

betterrolecolors
**Describe the Bug**

 mentioned person role name is not colored 
![image](https://user-images.githubusercontent.com/38098603/141231130-09d56872-2e17-4d58-96b5-a03a3f40df3a.png)

**To Reproduce**

have 
![image](https://user-images.githubusercontent.com/38098603/141231083-0c5a369b-3935-4300-ab33-faef0a4f2b09.png)

**Expected Behavior**

mentioned person's name colored to role
**Screenshots**

**Discord Version**

stable
**Additional Context**

**Comment by dragonunitedtm** [comment]
using the Spectrua theme |neutron

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
