### ISSUE TITLE
[Feature] HideDisabledEmojis: add support for stickers

### ISSUE THREAD

**Issue by itVictor** [rauenzi/BetterDiscordAddons#494]
**Which plugin/theme is this about?**
HideDisabledEmojis

**Is your feature request related to a problem? Please describe.**
Always annoying to scroll through stickers in the menu that I can't use.

**Describe the feature you'd like**
The plugin should also hide stickers that the user is unable to use, much in a similar manner the plugin works for emotes in the emote menu.

**Additional context**
 Maybe split into its own plugin but that seems redundant when you can just add it here.

**Comment by rauenzi** [comment]
>Maybe split into its own plugin but that seems redundant when you can just add it here.

To me, this doesn't feel redundant as this is specifically intended for emojis and not stickers. I do not intend to add that to this plugin.
