### ISSUE TITLE
Error level 9000

### ISSUE THREAD

**Issue by Abuleil** [rauenzi/BetterDiscordAddons#496]
Idk if it is happening to everyone but I get the "YOU DIED Looks like you got slaughtered by an Error Level 9000. Might have been one of your plugins? .... check Console for errors"
I get it whenever I click on GIF or Emoji or Sticker.(I edited because I forgot to say how I get the bug)
![image](https://user-images.githubusercontent.com/94217139/141610596-0df87ce6-64e6-46b9-a3bc-5b029c765ad5.png)

**Comment by Abuleil** [comment]
And I am only using the "BetterDiscord" without any additional plugins.

**Comment by Abuleil** [comment]
895d2d073e9649031842.js:130 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl (923477d8a99576a6eea2.js:6084)
    at e (923477d8a99576a6eea2.js:6023)
    at Bo (923477d8a99576a6eea2.js:6035)
    at $s (923477d8a99576a6eea2.js:6080)
    at Gu (923477d8a99576a6eea2.js:6070)
    at Uu (923477d8a99576a6eea2.js:6070)
    at wu (923477d8a99576a6eea2.js:6070)
    at Au (923477d8a99576a6eea2.js:6067)
    at 923477d8a99576a6eea2.js:6012
    at t.unstable_runWithPriority (923477d8a99576a6eea2.js:6311)
    at Ki (923477d8a99576a6eea2.js:6012)
    at Xi (923477d8a99576a6eea2.js:6012)
    at qi (923477d8a99576a6eea2.js:6012)
    at we (923477d8a99576a6eea2.js:6089)
    at en (923477d8a99576a6eea2.js:5989)
    at HTMLDivElement.r (895d2d073e9649031842.js:126)
    
    
   That's how the error looks like in console (I think..)
![image](https://user-images.githubusercontent.com/94217139/141610794-2ecb50b1-76fc-4730-bc57-351b67a791c5.png)

**Comment by rauenzi** [comment]
If you're not using plugins why would you open the issue here?

**Comment by Abuleil** [comment]
Where should I open it? Doesn't better discord count as plugin?

**Comment by acendvgnt** [comment]
[BetterDiscord/BetterDiscord#1116](https://github.com/BetterDiscord/BetterDiscord/issues/1116#issuecomment-966716341) seems to be your bug. Same exact error stack trace. This repo is for BD WITH additional plugins/themes. If you have problems with base BD, go to the [BD repo](https://github.com/BetterDiscord/BetterDiscord/issues).

**Comment by Abuleil** [comment]
OK sorry for annoying you.

**Comment by txsweq12** [comment]
If you're not using plugins why would you open the issue here?

**Comment by rauenzi** [comment]
This issue is 11 months old.

**Comment by txsweq12** [comment]
sorry

**Comment by txsweq12** [comment]
how I remove this bug.

**Comment by sparty182020** [comment]
I just got the same bug
I am using a "few" plugins, but this hasn't happened before with me. Can someone reopen this?

**Comment by ashoklathwal** [comment]
Check this one for detailed explanation: [discord error level 9000](https://wealthquint.com/discord-error-level-9000-56477/)

**Comment by ArtiomVremea** [comment]
Having the same issues on vencord even without plugins and themes on it keeps showing up with the same error
