### ISSUE TITLE
[Bug] SearchSearch Icon Not Showing

### ISSUE THREAD

**Issue by BillChirico** [rauenzi/BetterDiscordAddons#497]
**Which plugin/theme is this about?**
SearchSearch 

**Describe the Bug**
Search button icon not showing

**To Reproduce**
1. Download plugin
2. See that the search icon is not showing

**Expected Behavior**
Search icon should show

**Screenshots**
![image](https://user-images.githubusercontent.com/13951316/141698444-98af4d22-c351-4df8-a18a-46fc0ae27814.png)

**Discord Version**
Stable 104752 (000c742)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Additional Context**
Not using any themes

**Comment by vexxic** [comment]
This is still an issue

Removing other plugins / themes do not make a difference

Discord Version
Stable 108044 (79ffd44)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19042)

![Screenshot 2021-12-16 163520](https://user-images.githubusercontent.com/28605864/146391378-00626045-2dc3-413c-a932-c594ae92adb7.png)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
