### ISSUE TITLE
[Bug]  AutoPlayGifs gifs play while out of focus

### ISSUE THREAD

**Issue by Ayetoh** [rauenzi/BetterDiscordAddons#498]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
Profil picture that use gif are still moving when discord is not focus and that cause a little gpu % usage that i really don't like ( 6-10% with a 3070 ) i would like to have those 10% gpu usage for my game running :) 

**To Reproduce**
-Click discord to open it, ( discord is in focus state ) 
-Click on your favorite game tab and start to play (discord should be on background state there )
-Press windows, over your cursor to discord, a little window will pop, OVER ( DONT CLICK ) your cursor to the window and discord should appear, and you will see those profil picture gif moving because discord is still in focus mode...

Add me on discord Ayeto#5097 if you cannot reproduce the bug.

**Expected Behavior**

When i'm clicking OUTSIDE of discord, discord should go in background mode and those gif shouldn't moving, just like when i click in the minimize button.

If i click on the minimize button and reproduce the step above the gif aren't moving at all because discord is in background mode

**Discord Version**
Stable 105608 (de4ad93)

**Comment by rauenzi** [comment]
This plugin has now been discontinued.
