### ISSUE TITLE
SendButton is not getting injected dynamically

### ISSUE THREAD

**Issue by narcolepticinsomniac** [rauenzi/BetterDiscordAddons#50]
Only time I see it is when I reload the plugin and exit out of settings to the current channel. As soon as you navigate to a different channel, no button. Something wrong with the observer, I guess.

**Comment by narcolepticinsomniac** [comment]
Well, you fixed it, so thanks. Not sure why you wouldn't bother responding or closing this issue, but it's resolved so I'll close it.

**Comment by rauenzi** [comment]
Just forgot to close it, been busy lately.

**Comment by narcolepticinsomniac** [comment]
![kg0oj6](https://user-images.githubusercontent.com/14100003/41495660-2f68f9d2-70fa-11e8-8915-3334df501a58.jpg)

NBD, fixed is fixed. Thanks again.
