### ISSUE TITLE
[Bug] Plugin not showing or loading/working

### ISSUE THREAD

**Issue by malyvb** [rauenzi/BetterDiscordAddons#500]
**Which plugin/theme is this about?**

 Nitroperks
**Describe the Bug**

I got the plugin into the plugins folder but it is not showing/working
**To Reproduce**

Download nitroperks and import it
**Expected Behavior**

Nitroperks working/loading and showing
**Screenshots**

NitroPerks file highlighted
![obraz](https://user-images.githubusercontent.com/62879469/145675272-f0817042-05c9-4be1-8a95-493f329b8c80.png)

**Discord Version**

Canary (but i'm gonna try it on Stable maybe)
**Additional Context**

**Comment by rauenzi** [comment]
Lmao
