### ISSUE TITLE
[Bug]  HideDisabledEmojis rows out of sync

### ISSUE THREAD

**Issue by JelCraft** [rauenzi/BetterDiscordAddons#502]
**Which plugin/theme is this about?**
HideDisabledEmojis 

**Describe the Bug**
On servers where no custom emojis are saved as favourites, the emoji rows shift up one category. This causes them to be out of sync with their title and the emoji "sidebar" for categories. (E.g. clicking "people", leads to "nature").

**To Reproduce**
Open a server with custom emojis, remove all favourite custom emojis in that server from favourites. The rows will now be out of sync by one. (Make sure to have at least one favourite default emoji.)

**Expected Behavior**
Clicking a category leads to the correct emoji category. Scrolling should also switch to the correctly corresponding sidebar row. Within the favourite emojis section, default Discord emojis should also be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/61025393/146941432-7e5d84fa-71c1-4ee6-abbc-5645ab714134.png)
![image](https://user-images.githubusercontent.com/61025393/146941448-c91c513d-59a2-4c5e-9d1e-f859597a55d9.png)

**Discord Version**
Stable

**Additional Context**
"Favourites" section only shows available custom emojis (no default emojis). This can create an "empty" favourites section because it still appears in the sidebar. This might be what is causing the problem.

**Comment by rauenzi** [comment]
Is this still happening?

**Comment by Glaived** [comment]
> Is this still happening?

Yes. v0.0.7

**Comment by deepspaceaxolotl** [comment]
I still have this issue. Because I'm in many servers, clicking the emoji categories just jumps through the first few servers and I have to scroll manually to reach the built-in emojis. A fix would be greatly appreciated!
