### ISSUE TITLE
[Bug] ServerSearch search icon wont appear in latest Discord (stable) version - Stable 108924 (eb8c571) BetterDiscord 1.3.0 Windows 10 64-Bit (10.0.22000) (Im actually on Win11)

### ISSUE THREAD

**Issue by ItsCubeTime** [rauenzi/BetterDiscordAddons#504]
**Which plugin/theme is this about?**
ServerSearch 

**Describe the Bug**
[Bug] ServerSearch search icon wont appear in latest Discord (stable) version - Stable 108924 (eb8c571) BetterDiscord 1.3.0 Windows 10 64-Bit (10.0.22000) (Im actually on Win11)

**To Reproduce**
Install  the latest ServerSearch from https://betterdiscord.app/plugin/ServerSearch (v0.1.8) and enable it.

**Expected Behavior**

**Screenshots**

https://user-images.githubusercontent.com/20190653/147457770-62febd02-20c5-4f72-b90d-b3e278e1897f.mp4

**Comment by ItsCubeTime** [comment]
Might be a user error if Ive forgotten to install some required library

**Comment by fbievan** [comment]
Nope, 
![image](https://user-images.githubusercontent.com/17110707/148671026-63633c3d-d744-462b-9f1b-c17bdf6ca1b0.png)
Just doenst work even with zerospluginlibary

**Comment by matievisthekat** [comment]
this is happening to me as well
![Screenshot_20220118_160953](https://user-images.githubusercontent.com/45036977/149953045-3c2e1fdf-3377-4d3c-85bd-c2f833823158.png)
l

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
