### ISSUE TITLE
[Bug] AutoPlayGifs doesn't work

### ISSUE THREAD

**Issue by Chiroyasumi** [rauenzi/BetterDiscordAddons#505]
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
I have downloaded the plugin it worked for a bit but now avatar's with gif wont work. I uninstalled it, deleted the config file and reinstalled it, nothing seems to fix the problem

**To Reproduce**
Download the plugin and just go in a chatroom

**Expected Behavior**
Avatars with gif should play 

**Screenshots**

https://user-images.githubusercontent.com/51413351/148661301-d87e6222-1c82-463f-ab23-c432281c41f3.mp4

**Discord Version**
Stable

**Additional Context**
Nothing to add

**Comment by skyli91** [comment]
i confirm

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
