### ISSUE TITLE
[Feature] BlurNSFW onscreen enable/disable toggle

### ISSUE THREAD

**Issue by sybaricat** [rauenzi/BetterDiscordAddons#506]
**Which plugin/theme is this about?**
BlurNSFW

**Is your feature request related to a problem? Please describe.**
I would like to be able to turn NSFW image blurring on and off on the fly (without going through the BD plugins manager every time) so that I can turn the plugin off when not needed.

**Describe the feature you'd like**
A toggle added to the main Discord UI, either where the master deafen/mute buttons are, or in the channel header next to the search box. Something that simply turns blurring on/off globally (turning the plugin on and off, effectively) and displays its status in some way (like crossing the symbol out when turned off, etc.).

**Comment by rauenzi** [comment]
This was added in the latest version on a per-channel basis. I won't be adding a global one.
