### ISSUE TITLE
[Bug] PermissionViewer's pop out modal is too big (aka out of the screen)

### ISSUE THREAD

**Issue by ducanh2002123** [rauenzi/BetterDiscordAddons#508]
**Which plugin/theme is this about?**

PermissionViewer
**Describe the Bug**

The permission viewing modal box is way too big, it overflows out of the screen area
**To Reproduce**

open the permission viewer dialog
**Expected Behavior**

it doesn't overflow out and instead resize to the correct screen size
**Screenshots**

![image](https://user-images.githubusercontent.com/10848519/149533228-1271bcd6-5c76-416e-be7a-065b9cdd61b4.png)
(Note: there's more roles that's above the image, and I have already reduced the zoom to 80% to view the Mod role)
**Discord Version**

Stable
**Additional Context**

Also, the "show permission" dialog is missing from the right click menu, likely due to the recent update

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
