### ISSUE TITLE
[Bug] BDContextMenu doesn't have context menu option until toggled off and on again

### ISSUE THREAD

**Issue by k4zo** [rauenzi/BetterDiscordAddons#510]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
Upon restarting Discord, right clicking the user settings button shows that the plugin has failed to add a new context menu option, and the only way to make the plugin work as expected is to manually go into the plugins tab of settings and toggle the plugin off and on again

**To Reproduce**
1) Start Discord without it already running in the system tray
2) Right click the user settings button

**Expected Behavior**
At the bottom of the list there's supposed to be the "BetterDiscord" context menu entry

**Screenshots**
https://i.imgur.com/69JGLD8.png
https://i.imgur.com/PE5m4Ec.png

**Discord Version**
Stable

**Additional Context**
Not applicable

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
