### ISSUE TITLE
[Bug] RoleMembers Context Menu Missing? [Stable 110451 (c233a73)]

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [rauenzi/BetterDiscordAddons#511]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
When Right-clicking on any server the context menu does not show anymore

**To Reproduce**
right-click on a server

**Expected Behavior**
to show the menu as shown in this demo:
![Demo](https://camo.githubusercontent.com/bbf40a87bf98112e900614196dd75051db675fcfe27de1f9c28a9fc52bbe079f/68747470733a2f2f692e696d6775722e636f6d2f78757079686e442e676966)

**Screenshots**
![Screen Shot 2022-01-18 at 5 43 30 pm](https://user-images.githubusercontent.com/2242880/149885972-04e30b7b-02d8-4bfe-a74a-d5ea67c21e1d.jpg)
see not there..

**Discord Version**
Stable 110451 (c233a73)

**Additional Context**
This is all I get for logs, nothing in logs though regarding the plugin.
[debug.log](https://github.com/rauenzi/BetterDiscordAddons/files/7886805/debug.log)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
