### ISSUE TITLE
[Bug] permissionviewer broken

### ISSUE THREAD

**Issue by dolphin-cat** [rauenzi/BetterDiscordAddons#512]
permission viewer doesn't show in context menu when right clicking on a server but it used to, did it get removed in some update?
edit: it doesn't show in any context menus

**Comment by acendvgnt** [comment]
Discord updated and broke a lot of things.

**Comment by XxUnkn0wnxX** [comment]
getting a lot of errors in the console
![Screen Shot 2022-01-19 at 8 18 17 pm](https://user-images.githubusercontent.com/2242880/150100744-5ecf25c7-eb6d-4afb-a762-f75f34812570.jpg)
[console_log.log](https://github.com/rauenzi/BetterDiscordAddons/files/7895712/console_log.log)

**Comment by dolphin-cat** [comment]
will it be fixed?

**Comment by dolphin-cat** [comment]
@rauenzi

**Comment by HRudyPlayZ** [comment]
I hope it will.

**Comment by rauenzi** [comment]
Thank you for these unhelpful comments.

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
