### ISSUE TITLE
Hide all permissions but show only 3 points

### ISSUE THREAD

**Issue by AndreZila01** [rauenzi/BetterDiscordAddons#513]
**Which plugin/theme is this about?**
PermissionsViewer 

**Is your feature request related to a problem? Please describe.**
Is not a problem but one idea. 

**Describe the feature you'd like**
I like hide the permissions but not hide 3 points.
![Original Image](https://user-images.githubusercontent.com/56931353/150222484-2c27c02c-5ff7-44bd-a8d3-f8bc1addddf9.png)

Like This: 
![Idea Image](https://user-images.githubusercontent.com/56931353/150223305-49cc7828-f6f6-4696-ac38-20221b997d36.png)
If user click on "arrow" see all permissions, like image 1. and give space between Note and permissions LUL

**Comment by rauenzi** [comment]
I've decided not to implement this, it would be better to just not have the menu there at all which there is already a setting for. Then if you need to see permissions you just use the context menu as normal.
