### ISSUE TITLE
[Bug] RoleMembers - Not showing the popup

### ISSUE THREAD

**Issue by teisseire117** [rauenzi/BetterDiscordAddons#514]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
I click on a role in the role list after right clicking a username, but nothing appears

**To Reproduce**
Try displaying the members of a role as you would usually do

**Expected Behavior**
User list of a chosen role should appear

**Screenshots**

![pBDdTJe](https://user-images.githubusercontent.com/43145883/150672163-318eb120-9afe-4d92-9689-449770198d99.gif)

**Discord Version**
Stable 111699 (e8f9fb9)
BetterDiscord 1.3.0

**Additional Context**
(I know it wasn't working before, but since you updated the plug-in 40 minutes ago it should then be working, so I may this Bug Report

Plug-in version :

![2KSFbAr](https://user-images.githubusercontent.com/43145883/150672239-8c73f239-651d-4a80-8fd5-ac8dc1b75548.png)

**Comment by rauenzi** [comment]
That's not a feature of the plugin and never was.

**Comment by teisseire117** [comment]
My memory played me.
Thank you for updating the plug-in though
