### ISSUE TITLE
[Bug] AccountDetailsPlus No settings menu

### ISSUE THREAD

**Issue by TheHunter1234** [rauenzi/BetterDiscordAddons#515]
The new update of AccountDetailsPlus does not have a settings option even after a manual update to the plugin.

**Comment by rauenzi** [comment]
Can you elaborate?

**Comment by TheHunter1234** [comment]
![image](https://user-images.githubusercontent.com/69104450/150673478-96546933-b357-4a6d-b3c4-f308cfbb3ae8.png)
no settings button on the plugin info

**Comment by TheHunter1234** [comment]
Is there supposed to be one? Before the update there was one. Was this removed?

**Comment by rauenzi** [comment]
I just pushed an update to resolve this.

**Comment by TheHunter1234** [comment]
I updated it, thanks for the help. 👍
