### ISSUE TITLE
[Bug] BetterRoleColors - Crashes Client

### ISSUE THREAD

**Issue by TheHunter1234** [rauenzi/BetterDiscordAddons#516]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Crash when clicking on user mentions or user profiles.

**To Reproduce**
Click on user mentions or profile.

**Expected Behavior**
Client crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/69104450/150672598-89bd89f6-3319-4e12-a00c-201e2d5b6d4d.png)

Using the latest version of the plugin along with everything else up to date.

**Comment by rauenzi** [comment]
What Discord version is this? I cannot reproduce. Are you clicking on regular users? Bots?

**Comment by rauenzi** [comment]
Also please note any other installed plugins and the version of ZeresPluginLibrary

**Comment by TheHunter1234** [comment]
![image](https://user-images.githubusercontent.com/69104450/150673252-bd998e3d-59e8-4373-ad1a-20b3cddba021.png)
![image](https://user-images.githubusercontent.com/69104450/150673256-5684b0e8-d885-4d56-9a5e-3ee7b9a23054.png)
![image](https://user-images.githubusercontent.com/69104450/150673257-517625c5-35fb-4768-8f4a-3fc154c3635f.png)
note i am using windows 11 pro
https://user-images.githubusercontent.com/69104450/150673299-7616a01a-c816-421b-9200-99adfea116e0.mp4
currently, i am clicking on normal users
i will test all of my plugins and do that one standalone but these are the results I am having so far

**Comment by ndbiaw** [comment]
same, my Better Discord crashed because of this plugin
Stable 111699 (e8f9fb9)
Host 1.0.9003 
Windows 10 64-Bit (10.0.19043)

**Comment by TheHunter1234** [comment]
I have found the plugin conflicting is PlatformIndicators. I have no idea what a fix would be or how, but could this be fixed. Is it your plugin causing the issue or Strencher's?

**Comment by rauenzi** [comment]
The end crash is indeed my plugin, and I can fix that part (will push out a temporary fix). But people without nicknames will not be colored due to the conflict

**Comment by TheHunter1234** [comment]
What could be done for them both to work without conflicts?

**Comment by rauenzi** [comment]
I would have to investigate or talk with Strencher

**Comment by TheHunter1234** [comment]
Got it! Thanks! 👍
