### ISSUE TITLE
[Bug] Unable to view permissions of different roles

### ISSUE THREAD

**Issue by Astilimos** [rauenzi/BetterDiscordAddons#517]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
In the channel/server permissions popup, switching roles doesn't work and produces an error in the console.

**To Reproduce**
1. Open the channel/server permissions window
2. Click on a role

**Screenshots**
![image](https://user-images.githubusercontent.com/56225739/150679048-da1c9f43-2755-47a3-b1ed-60a2fbd0c2db.png)

**Discord Version**
Stable

**Comment by Vyxxxx** [comment]
Same for me.
![yjcfyjcfyjgyjcgyjcgyj](https://user-images.githubusercontent.com/80600853/150697802-47eb0f50-13a0-4ce6-a13f-62637c796087.PNG)

**Comment by acendvgnt** [comment]
I tried replacing `e.removeClass("selected")` with `e.classList.remove("selected")` and that seems to have worked.

**Comment by mrchillington** [comment]
> I tried replacing `e.removeClass("selected")` with `e.classList.remove("selected")` and that seems to have worked.

This also worked for me
