### ISSUE TITLE
[Bug] BetterRoleColors not styling mentions in textbox

### ISSUE THREAD

**Issue by Neodymium7** [rauenzi/BetterDiscordAddons#518]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Mentions are properly styled/colored in sent messages, but not in the textbox when typing or editing a message

**To Reproduce**
Type a mention into the textbox

**Screenshots**
![image](https://cdn.discordapp.com/attachments/470024236497502218/935062040886788166/unknown.png)

**Discord Version**
Stable

**Additional Context**
No themes enabled. Only plugins enabled are BetterRoleColors and BDPluginLibrary

**Comment by rauenzi** [comment]
Yep I experienced this as well

**Comment by rauenzi** [comment]
This should be fixed in the latest version!
