### ISSUE TITLE
[Bug] Server Search plugin icon in Discord DM section is disappearing when going to a Server.

### ISSUE THREAD

**Issue by IamNickerson** [rauenzi/BetterDiscordAddons#519]
**Which plugin/theme is this about?**
Server Search Plugin.

**Describe the Bug**
The Server Search plugin icon in Discord DM section is disappearing when moving to a next Server.

**To Reproduce**
Just move to next Server.

**Expected Behavior**
Server Search plugin icon disappeared. 

**Screenshots**
In a Dm:
![image](https://user-images.githubusercontent.com/61643704/150816770-45e5a970-61fb-41cf-a61f-a7415a28af75.png)
Into a Server:
![image](https://user-images.githubusercontent.com/61643704/150816875-a751e52a-757d-4d8a-8104-6753c9786932.png)
When I am going back to the DM it doesn't appear back.

**Discord Version**
Stable.

**Additional Context**
If I need the plugin icon to appear I need to go better discord plugin settings disable it and enable it to appear it back but  after that I have to do it again and again if I am going to the next server because the plugin icon doesn't appear when I am on the next Server.

**Comment by IamNickerson** [comment]
Ok server search fixed.

**Comment by ExWaltz** [comment]
The button still disappears when I click on it or go to a server. The bug seems to only happen once at startup. After disabling and re-enabling it, the bug disappears.

Discord Version: 0.0.16
OS: Arch Linux
Plugins: ServerSearch v0.1.9, BDFDB v2.1.7

![bug demo](https://user-images.githubusercontent.com/69315365/154315682-629e49eb-f254-41a4-b649-fcd5370ac31a.gif)

**Comment by ExWaltz** [comment]
This bug is still present for me. After discord startup, going into a server will make the server search button disappear. 

**Discord version**: 0.0.16
**OS**: Arch linux

**Observed Behavior:**
![bug-demon](https://user-images.githubusercontent.com/69315365/154435555-31474c58-d2b5-4650-a6f6-d8dc2617a20e.gif)

After looking at it closely, the bug occurs because the server list gets deleted and then recreated when you enter a server for the first time after startup.

I don't have experience in writing BetterDiscord plugins, but I have made a quick fix for it.

```js
async onStart() {
    PluginUtilities.addStyle(this.getName(), this.css);
    const GuildList = WebpackModules.find(m => m.type && m.type.displayName == "NavigableGuilds");
    this.guildPatch = Patcher.after(GuildList, "type", () => {this.addSearchButton();});
    await new Promise(resolve => setTimeout(resolve, 1000));
    this.addSearchButton();

    // server list
    const target = document.querySelector(".listItem-3SmSlK .guildSeparator-a4uisj");

    // Detect if the server list is removed
    BdApi.onRemoved(target, () => {
        // Wait until the server list is recreated
        const observer = new MutationObserver((mutations) => {
            if (target) {
                // add the server search button
                this.addSearchButton();
                observer.disconnect();
                return;
            }
        });
        observer.observe(document.body, {subtree: true, childList: true});
        return () => {observer.disconnect();};
    })
}
```

**Comment by IamNickerson** [comment]
Yeah it is happening again before but when u gave out that code it really helped the plugin to not disappeared again thanks a lot btw and also pls mention to where to put that code in which line of the server search plugin.

**Comment by ExWaltz** [comment]
Replace the entire `onStart()` function on line 205 with the code above
or follow the diff file shown below

```diff
--- ServerSearch.plugin.js	2022-02-17 21:02:21.976087348 +0800
+++ ServerSearch-fixed.plugin.js	2022-02-17 16:57:23.296366562 +0800
@@ -208,6 +208,24 @@
             this.guildPatch = Patcher.after(GuildList, "type", () => {this.addSearchButton();});
             await new Promise(resolve => setTimeout(resolve, 1000));
             this.addSearchButton();
+
+            // server list
+            const target = document.querySelector(".listItem-3SmSlK .guildSeparator-a4uisj");
+
+            // Detect if the server list is removed
+            BdApi.onRemoved(target, () => {
+                // Wait until the server list is recreated
+                const observer = new MutationObserver((mutations) => {
+                    if (target) {
+                        // add the server search button
+                        this.addSearchButton();
+                        observer.disconnect();
+                        return;
+                    }
+                });
+                observer.observe(document.body, {subtree: true, childList: true});
+                return () => {observer.disconnect();};
+            })
         }
         
         onStop() {
```

**Comment by IamNickerson** [comment]
Just give the plugin js here if u can

**Comment by IamNickerson** [comment]
I am totally confused what are u trying to tell me to replace

**Comment by ExWaltz** [comment]
Here is the plugin:
https://gist.github.com/ExWaltz/60f197ab442a0d753d60f158fc7a5e39

and yea green is insert and red is remove in diff files.

**Comment by IamNickerson** [comment]
Okay thanks.
