### ISSUE TITLE
Clicking on a member using role members plugin crashes Discord

### ISSUE THREAD

**Issue by Liz-chan** [rauenzi/BetterDiscordAddons#52]
I went to go use role members as I hadn't used it in a while and when I clicked on someone to check their profile, Discord crashed. This also happened in other servers and other roles as well. 
![image](https://user-images.githubusercontent.com/18467466/41504030-cc449f5c-71b0-11e8-8b8b-bf079fee8e5a.png)

**Comment by rauenzi** [comment]
Are you sure it's role members and not one of the other plugins? Role members doesn't do anything to user popouts or modals.

**Comment by Liz-chan** [comment]
I disabled all the other plugins and tried it again and it still crashed my Discord. It wouldn't be one of my themes would it?

**Comment by rauenzi** [comment]
Can you show the console error that appears? `ctrl`+`shift+`i` click console at the top and look for red

**Comment by Liz-chan** [comment]
![image](https://user-images.githubusercontent.com/18467466/41504054-5ce593ae-71b1-11e8-9a7f-627619ab5a57.png)

**Comment by rauenzi** [comment]
Ah you clicked on a user inside the role member list?

**Comment by Liz-chan** [comment]
Yep.

**Comment by rauenzi** [comment]
Pushed a fix, check for updates by clicking the button on the plugins page!

**Comment by Liz-chan** [comment]
Sweet, fixed worked, thanks 😄
