### ISSUE TITLE
[Bug] PermissionsViewer - No scrollbar, can't select other roles

### ISSUE THREAD

**Issue by Drflash55** [rauenzi/BetterDiscordAddons#520]
**Which plugin/theme is this about?**
PermissionsViewer v0.2.1.

**Describe the Bug**
When attempting to view the permissions of a server, the scroll bar is completely gone. Impossible to click on other roles to see their permissions as well.

**To Reproduce**
1. Right click any server.
2. Click on permissions.
3. Nothing functions besides just closing it.

**Expected Behavior**
It shouldn't cover up the entire screen, have a scrollbar, and being able to select the other roles in that server.

**Screenshots**
How it looks:
![image](https://user-images.githubusercontent.com/13694448/150860659-0a1e64a4-c124-423b-ad78-da99eeb3c2fa.png)
(Didn't show anything else so as to not leak secrets.)

**Discord Version**
Stable 111699 (e8f9fb9)
BetterDiscord 1.4.0

**Additional Context**
No console errors, which is weird.

**Comment by BigFlubba** [comment]
I am having the same issue too. It will cut off of the screen and not all be visible. Happens on the latest version.
![image](https://user-images.githubusercontent.com/69104450/151627866-99986967-4327-46f7-a426-67a1cc3345c8.png)

**Comment by ponpoko094** [comment]
Changing the settings of PermissionsViewer may solve the problem.
1. Click on User Settings.
2. Click on BetterDiscord > Plugins in the sidebar.
3. Find the PermissionsViewer.
4. Click on Settings.
5. Click on Model Display Mode > Cozy
6. Done.
![image](https://user-images.githubusercontent.com/46832957/152536898-1631b257-2425-4ca9-9dd4-1886e9ca05d8.png)
![image](https://user-images.githubusercontent.com/46832957/152536988-fc9a31ca-5815-4e51-a5d6-cab214dcc225.png)

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
