### ISSUE TITLE
[Bug] AutoPlayGifs no longer plays avatars on member list

### ISSUE THREAD

**Issue by DieselPinkman** [rauenzi/BetterDiscordAddons#522]
**Which plugin/theme is this about?**

AutoPlayGifs
**Describe the Bug**

Animated avatars no longer play on the members list like they used to before the recent update.
**To Reproduce**

**Expected Behavior**

Avatars animate on members list.
**Screenshots**

**Discord Version**

**Additional Context**

**Comment by karimawii** [comment]
I have the same issue

**Comment by rauenzi** [comment]
This plugin has now been discontinued.
