### ISSUE TITLE
[Bug] [BetterRoleColors] Coloring user chat text despite option disabled

### ISSUE THREAD

**Issue by Zacam** [rauenzi/BetterDiscordAddons#524]
**Which plugin/theme is this about?**
BetterRoleColors v0.8.17

**Describe the Bug**
Chat text is colored with users Role color even though "Chat" option in Plugin is un-ticked/disabled.

**To Reproduce**
Enable BetterRoleColors, set "Chat" to un-ticked and reload; chat messages are still role colored on load of plugin.

**Expected Behavior**
Role names should be colored, but the text of the messages should not be.

**Screenshots**
![BRC-Bug](https://user-images.githubusercontent.com/2995385/151607652-5723965e-f40f-4165-8a99-029edec7a2f7.png)

Results in:
![BRC-MsgBug](https://user-images.githubusercontent.com/2995385/151608156-8acbf86b-3e41-43b4-ae89-5a105ed73e29.png)

If I turn it off, the coloring stays until I hover or roll over a colored message, at which point it goes back to normal, unless/until I re-enable the plugin:
![BRC-MsgBug2](https://user-images.githubusercontent.com/2995385/151608659-853e80cf-adc4-479a-b7e2-c60e8b8c0e0e.png)
(This shows what the original message should have looked like with the plugin enabled and the "Chat" un-ticked)

**Discord Version**
Stable 112515
BD 1.4.0

**Additional Context**
Win 7 x64 Ultimate
Have ensured/reproduced without theme involved, theme is ClearVision v6 (6.2.0 fixed for Discords recent changes)
Have customized the theme.css to use a custom home icon and background image.
I have also unloaded all other plugins save for BetterRoleColors and required ZeresPluginLibrary (v2.0.0) for confirmation, though screenshots show "full" environment of use (theme and other plugins loaded).

**Comment by rauenzi** [comment]
Try redownloading the plugin
