### ISSUE TITLE
[Bug] BetterRoleColors does not respect 'Chat' setting toggle

### ISSUE THREAD

**Issue by pr0geta** [rauenzi/BetterDiscordAddons#525]
**Which plugin/theme is this about?**

BetterRoleColors

**Describe the Bug**

When the 'Chat' toggle is turned off, message text is still coloured according to the user's roles. Occasionally, the message text will be the default colour, but will change to the role colour when the mouse moves over it.

**To Reproduce**

1. Go into the plugin's settings
2. Under 'Module Settings', set 'Chat' toggle to the off position
3. Go to any text channel.

**Expected Behavior**

When the 'Chat' toggle is turned off, the setting should be respected and message text should remain the default colour.

**Screenshots**

![image](https://user-images.githubusercontent.com/98614854/151609368-3ff821f6-283c-4659-86dd-304800fb4237.png)
![image](https://user-images.githubusercontent.com/98614854/151609410-72cf39ad-b457-488e-acd3-d133804974c8.png)

**Discord Version**

Stable 112515 (900f57b)
BetterDiscord 1.4.0
Host 1.0.9003 
Windows 10 64-Bit (10.0.19042)

**Comment by rauenzi** [comment]
Duplicate #524
