### ISSUE TITLE
[Bug] BetterFormattingRedux - Unable to fire observer

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [rauenzi/BetterDiscordAddons#526]
**Which plugin/theme is this about?**

BetterFormattingRedux

**Describe the Bug**

Getting the following error:

Unable to fire observer for BetterFormattingRedux v2.3.12 TypeError: Cannot read property 'create' of undefined
    at BetterFormattingRedux.buildToolbar (BetterFormattingRedux.plugin.js:573)
    at BetterFormattingRedux.addToolbar (BetterFormattingRedux.plugin.js:608)
    at BetterFormattingRedux.observer (BetterFormattingRedux.plugin.js:393)
    at Object.onMutation (<anonymous>:4:313953)
    at MutationObserver.<anonymous> (<anonymous>:4:309531)

**To Reproduce**

N/A, Just have console open & refresh discord

**Expected Behavior**

For No Errors to occur

**Screenshots**

![Screen Shot 2022-01-29 at 9 03 02 am](https://user-images.githubusercontent.com/2242880/151627774-77800f44-1419-4410-92a7-f29b40e3e850.jpg)

**Discord Version**

```text
Stable 112515 (900f57b)
BetterDiscord 1.4.0
Host 0.0.264 OS X 10.15.7 (20.6.0)
```

**Additional Context**

[debug.log](https://github.com/rauenzi/BetterDiscordAddons/files/7962057/debug.log)
[discord.com-1643407431808.log](https://github.com/rauenzi/BetterDiscordAddons/files/7962067/discord.com-1643407431808.log)

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
