### ISSUE TITLE
[Feature] - Option to sort plugins and themes by status (enabled & disabled).

### ISSUE THREAD

**Issue by BigFlubba** [rauenzi/BetterDiscordAddons#529]
I don't know why this is not a thing yet, but nonetheless, I would like the option for there to be a sorting option of enabled plugins and themes and disabled ones. This would help a lot for others (including me) who have more than 20 plugins installed and some enabled and disabled. This would be very helpful.

**Comment by rauenzi** [comment]
No clue what this has to do with this repository.

**Comment by BigFlubba** [comment]
It involves Better Discord which this is about.

**Comment by BigFlubba** [comment]
I cannot post it to any other repo because it doesn't involve that repo and only deals with Better Discord.

**Comment by BigFlubba** [comment]
Oh, you would be correct. Sry. Can you link it. Thanks.
