### ISSUE TITLE
[Bug] BDContextMenu not opening BetterDiscord settings

### ISSUE THREAD

**Issue by ashergz** [rauenzi/BetterDiscordAddons#530]
Clicking on BetterDiscord from the context menu does nothing, whereas clicking any of the BetterDiscord menu simply takes you to the main settings page.

![image](https://user-images.githubusercontent.com/35883201/151916043-d9d77108-3d91-457b-ab56-6cb578efac65.png)

**Comment by OmegaBlurz** [comment]
#531

**Comment by Zacam** [comment]
As a belated update:
At present, "BetterDiscord" no longer is an entry in the profile area cog-wheel context menu.

**Comment by rauenzi** [comment]
This has now been fixed
