### ISSUE TITLE
Download is gone [Other] 

### ISSUE THREAD

**Issue by Enferlain** [rauenzi/BetterDiscordAddons#534]
Where do you download the plugin now? There is no other emote blacklisting plugin

**Comment by Maverynthia** [comment]
Agreed I was using the EmojiUtilities as a BLOCKING plugin not a faveing one.

**Comment by vylryna** [comment]
I was looking for the plugin too but I realized my old hard drive still had the plugin, so I went ahead and grabbed it from there.

I have a backup here: https://gist.github.com/vylryna/fc0150da418e4a9923f4ca579a9a8a5e
