### ISSUE TITLE
Discord Crashes when I right-click a user profile [Bug]

### ISSUE THREAD

**Issue by Faneboom15** [rauenzi/BetterDiscordAddons#536]
**Discord crashes when I right-click on users (profiles)**
Plugin that causes this is unknown

**Bug description**
When I right-click on ANY discord user/profile in any server discord crashes.

**To Reproduce**
Just right-click any user/profile on any server

**Expected Behavior**
A user "interaction" menu should open but instead crashes

**Screenshots**
Just the regular discord crash screen

**Discord Version**
Stable

**Comment by mashingkeys** [comment]
I am also experiencing this, although it's when right clicking servers and channels as well.

**Comment by Neglevin** [comment]
Did you guys ever find out which plug-in was causing this?

**Comment by Faneboom15** [comment]
No, I didn't find what plugin caused the bug but now it's fixed.

lun., 11 apr. 2022, 12:05 a.m. Neglevin ***@***.***> a scris:
