### ISSUE TITLE
[Bug] BetterFormattingRedux Changelog on every restart of discord

### ISSUE THREAD

**Issue by mon5termatt** [rauenzi/BetterDiscordAddons#538]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
Changelog comes up on EVERY REBOOT

**To Reproduce**
Install, Close, Restart

**Expected Behavior**
One Time Changelog

**Screenshots**
![image](https://user-images.githubusercontent.com/43628254/152925474-d26f2cc6-4840-4ac0-9fc0-39607252e3ee.png)

**Discord Version**
Stable

**Comment by TrapStoner** [comment]
Wow this still isn't fixed...
