### ISSUE TITLE
[Bug] Permissions Viewer - When I right click on channels, their permissions are not visible.

### ISSUE THREAD

**Issue by ZeitBlade** [rauenzi/BetterDiscordAddons#539]
**Which plugin/theme is this about?**
Permissions Viewer

**Describe the Bug**
When I right click on channels, their permissions are not visible.

**Expected Behavior**
I want the permissions to appear when I right click on channels.

**Screenshots**
![image](https://user-images.githubusercontent.com/68385516/153390522-6c393821-0e64-4fc9-ab33-fef86210c7d9.png)

![image](https://user-images.githubusercontent.com/68385516/153390352-8cd0a609-c860-40fd-9b89-cce6637f226c.png)

**Discord Version**
Ptb 113977 (12a4d58)
BetterDiscord 1.5.1
Host 1.0.1012 Windows 11 64-Bit (10.0.22000)

**Comment by HoldWARE** [comment]
same for me needs to be fixed asap

**Comment by SaeidNH** [comment]
Same here.

Stable 114407 (811ab09)
BetterDiscord 1.5.1
Host 1.0.9003 Windows 10 64-Bit (10.0.22509)

**Comment by ZeitBlade** [comment]
[ ]

**Comment by BoAdla** [comment]
@rauenzi 😔

**Comment by rauenzi** [comment]
Comments like this are you you get blocked from the repo

**Comment by BoAdla** [comment]
Sorry

**Comment by ZeitBlade** [comment]
> Comments like this are you you get blocked from the repo

When Fix?

**Comment by HoldWARE** [comment]
> Comments like this are you you get blocked from the repo

Please fix this asap

**Comment by minhngoc25a** [comment]
> > Comments like this are you you get blocked from the repo
> 
> Please fix this asap

He's providing this for free, be patient dude. Don't act like this is an enterprise and assume that they're compelled to fix them ASAP. They'll fix them when they have time, and that's how FOSS works. If you can't take it, you can hire a developer or hire him to prioritize this issue, or fix it yourself.

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
