### ISSUE TITLE
[Bug] BetterRoleColors does not stylize "xxx is typing..."

### ISSUE THREAD

**Issue by MirTeiwaz** [rauenzi/BetterDiscordAddons#540]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
"<nickname> is typing..." is not coloured properly according to <nickname>'s top role colour

**To Reproduce**
Wait for the "xxx is typing..." to appear right below the message type box.

**Expected Behavior**
"xxx" should be coloured according to that person's top role colour.

**Screenshots**
<img width="333" alt="Screen Shot 2022-02-10 at 08 11 44" src="https://user-images.githubusercontent.com/16748184/153547068-a6b69ced-bdab-48a6-8fc5-5498040c88d8.png">

**Discord Version**
Stable

**Additional Context**
BDFDB 2.1.3
ZeresPluginLibrary 2.0.0

p.s. Was looking for Zere's Place Discord to report this, but I can't seem to find it. What's the Discord server link?

**Comment by rauenzi** [comment]
This should be fixed in the latest version! There is no longer a dedicated support Discord.
