### ISSUE TITLE
[Bug] PermissionsViewer doesn't work when BetterRoleColors in enabled

### ISSUE THREAD

**Issue by CJF1215** [rauenzi/BetterDiscordAddons#543]
**Which plugin/theme is this about?**
PermissionsViewer and BetterRoleColors

**Describe the Bug**
When BetterRoleColors is enabled in the plugin settings, User permissions don't appear in the user popout

**To Reproduce**
Enable BetterRoleColors (plugin options don't matter, with all on or off, it still happens) and PermissionsViewer and click on any user in a server

**Expected Behavior**
In the user popout, the nickname or username should be colored and the user's permissions should appear below their roles

**Screenshots**
Every BetterRoleColors setting on
![BetterRoleColors everything on](https://user-images.githubusercontent.com/64284737/154974685-22c8f0c5-a26e-43d0-9e73-801e6027f0f1.png)

Every BetterRoleColors setting off
![BetterRoleColors everything off](https://user-images.githubusercontent.com/64284737/154974728-0f9f5e0d-0d10-4a87-98b6-511f2f432f7a.png)

BetterRoleColors disabled
![BetterRoleColor disabled](https://user-images.githubusercontent.com/64284737/154974746-743ba379-9b5c-4762-8923-f4aaaf46c8b7.png)

**Discord Version**
Stable

**Additional Context**
With every option in BetterRoleColors turned on or off, it still has the same effect

**Comment by ArcWandx86** [comment]
Can confirm that this happens.

**Comment by yorik100** [comment]
Can confirm

**Comment by xartuu** [comment]
**Confirm ✔️!**
I use both plugins, one helps me a lot when building servers and the other makes Discord nicer to the eye. I don't want to give up on either for the time being, so I'm joining and hoping for a quick fix to this bug.

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
