### ISSUE TITLE
[Bug] ServerSearch Icon Disappears When I Restart Discord

### ISSUE THREAD

**Issue by MCHAMSTERYT2** [rauenzi/BetterDiscordAddons#544]
**Which plugin/theme is this about?**

ServerSearch
**Describe the Bug**

The ServerSearch Icon Disappears When I Restart Discord
**To Reproduce**

Install The SkeuoCord Theme Then Restart Discord With The ServerSearch Plugin And The ServerCount Plugin Enabled (The SkeuoCord Theme Is Optional)
**Expected Behavior**

It Should Stay When I Restart Discord
**Screenshots**

**Discord Version**

Stable
**Additional Context**

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for an alternative https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
