### ISSUE TITLE
When used once requires discord restart to use again

### ISSUE THREAD

**Issue by priimalhunter** [rauenzi/BetterDiscordAddons#55]
This plugin is great but can only be used once as when I try to search for another server it wont open up.

Example

https://gyazo.com/4ef4ddb957804371223c634336f37aa0

**Comment by priimalhunter** [comment]
Found out it was another plugin causing this issue

**Comment by priimalhunter** [comment]
Just incase you wanna know which plugin caused this issue it was 

DoNotTrack v0.0.1 by Zerebos

**Comment by rauenzi** [comment]
The issue is actually with ServerSearch, having DoNotTrack enabled just means that the error occurs instead of trying to ignore it.
