### ISSUE TITLE
snippets

### ISSUE THREAD

**Issue by Gamingbuilder** [rauenzi/BetterDiscordAddons#56]
The snipets don't work, can you uupdate them?

**Comment by NoireBlackHeart** [comment]
Hi rauenzi, can u tell me what/which plugin allows you to make such a profile picture
![default](https://user-images.githubusercontent.com/44205353/47029028-38409180-d173-11e8-8a1a-548418594d94.PNG)

**Comment by rauenzi** [comment]
It's a theme called UserPopouts Upgraded by Maple

**Comment by NoireBlackHeart** [comment]
this?
https://github.com/mrmaple240/UserPopoutUpgraded

**Comment by NoireBlackHeart** [comment]
(maybe it have other versions)

**Comment by NoireBlackHeart** [comment]
thanks

**Comment by NoireBlackHeart** [comment]
Hello again rauenzi, can you tell me please how to attach the status to all the pictures like this? If you don't mind
https://youtu.be/6AamQhz8P54

**Comment by rauenzi** [comment]
Use the plugin StatusEverywhere

**Comment by NoireBlackHeart** [comment]
wow that was fast
thank you
