### ISSUE TITLE
[Bug] BlurNSFW hover no longer clears blur

### ISSUE THREAD

**Issue by QuentinMcCarthy** [rauenzi/BetterDiscordAddons#570]
**Which plugin/theme is this about?**
BlurNSFW

**Describe the Bug**
BlurNSFW no longer disables the blur on images in chats unless the image is clicked into and in focus

**To Reproduce**
Attempt to unblur an image by hovering the mouse on it

**Expected Behavior**
Image unblurs

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by ColonelGerdauf** [comment]
I can confirm this to be the case as well. I suspect that a stealth update from Discord just so happened to break that particular function.

**Comment by heikadog** [comment]
can confirm unblur on hover for images no longer works

**Comment by JeffersonTan** [comment]
Same issue for me as well

**Comment by nagaisa** [comment]
same is happening to me as well for past good bit

**Comment by jericjan** [comment]
They rearranged how images load in chat apparently.  When you hover on an image, you're hovering on a hyperlink that's completely covering the blurred image, so the plugin can't tell if you're hovering over it at all. 

I did a little editing and it seems to work now in this pull request. #572

**Comment by rauenzi** [comment]
This should be fixed with the latest version!
