### ISSUE TITLE
[Bug] PermissionsViewer permission list has no scrollbar and extends outside screen

### ISSUE THREAD

**Issue by SpeckledFleebeedoo** [rauenzi/BetterDiscordAddons#574]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
When opening the detailed permissions list instead of fitting to the screen and having a scrollbar, it is drawn at full height, extending out of the screen at the top and bottom.

**To Reproduce**
Unknown... Potentially related to low monitor resolution (1440x900)?

**Expected Behavior**
A scrollbar, allowing me to scroll through the list of permissions.

**Screenshots**
![image](https://user-images.githubusercontent.com/49042682/159169331-49ea7be2-164d-4e21-884c-c43889b0162f.png)
Screenshot shows full height (but not full width) of monitor

**Discord Version**
Stable 11980, Linux

**Comment by FiredHydra** [comment]
I also have this same issue on a 1920x1080 resolution monitor. 
A "fix" that I ended up doing was commenting out line 215. Which was just disabling flex display in the CSS. 
Lines 214 - 223
```
#permissions-modal-wrapper #permissions-modal {
    display: flex;
    contain: layout;
    flex-direction: column;
    pointer-events: auto;
    border: 1px solid rgba(28,36,43,.6);
    border-radius: 5px;
    box-shadow: 0 2px 10px 0 rgba(0,0,0,.2);
    overflow: hidden;
}
```
would just turn into this if you want to edit your plugin file
```
#permissions-modal-wrapper #permissions-modal {
    /* display: flex; */
    contain: layout;
    flex-direction: column;
    pointer-events: auto;
    border: 1px solid rgba(28,36,43,.6);
    border-radius: 5px;
    box-shadow: 0 2px 10px 0 rgba(0,0,0,.2);
    overflow: hidden;
}
```

**Comment by rauenzi** [comment]
This should be fixed in the latest version!
