### ISSUE TITLE
[Bug] BetterRoleColor not changing color in voice modal after using keyboard shortcut to switch server

### ISSUE THREAD

**Issue by remi-espie** [rauenzi/BetterDiscordAddons#575]
**Which plugin/theme is this about?**
BetterRoleColor

**Describe the Bug**
The color of users in voice channel does not change when the user switches to a server with keyboard shortcut. They then change if a member is updated.

**To Reproduce**
Go to a server with people in voice channel, change to the next or previous server, change back to the server with people in voice channel via keyboard shortcut (CTRL+TAB for next, CTRL+SHIFT+TAB for previous)

**Expected Behavior**
Color of users in voice channel should change regardless of how you switch to a server.

**Screenshots**
![image](https://user-images.githubusercontent.com/60436978/160302538-9f3222b4-de7d-41c6-b46f-74f4faf5797f.png)

**Discord Version**
Stable

**Additional Context**
Don't mind the channel name lol

**Comment by rauenzi** [comment]
This is the same root issue as #422
