### ISSUE TITLE
[Bug] Enabling AccountDetailsPlus hides the account panel on bottom left

### ISSUE THREAD

**Issue by NotDreppy** [rauenzi/BetterDiscordAddons#577]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
When the plugin is enabled, the popout works, but it hides the account panel.
When I disable the plugin, the account panel shows up again.

**To Reproduce**
Simply install the plugin and enable it, then completely restart Discord.

**Expected Behavior**
The account panel should be hidden.

**Screenshots**
[https://cdn.discordapp.com/attachments/847748368787963906/961102006498508860/unknown.png?size=4096](url)

**Discord Version**
Canary 122654 (a920ed1)
BetterDiscord 1.5.2
Host 1.0.45 Windows 11 64-Bit (10.0.22000.593)

**Additional Context**
Try to recreate the bug in the EXACT same Windows environment, with the same Canary version.

**Comment by awooooool** [comment]
Happens to me too

Stable 122560 (be70dc4)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by nietdauf** [comment]
same here

**Comment by bghyt** [comment]
Temp fix: turn it off and back on [i wish i was kiddin]

**Comment by naotyu8** [comment]
same issue here

**Comment by I-NekoTin** [comment]
same problem

**Comment by bbeenn1** [comment]
The workaround mentioned by @bghyt works for me, toggle plugin off-on each startup of Discord. 
The issue may appear after my theme applies, but it could also be some other plugin, have not had any time to try tracking it down more unfortunately.

AccountDetailsPlus v1.0.1

Stable 122560 (be70dc4)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)

**Comment by Rayjacker** [comment]
On Discord Stable 122979 (0691b82), the workaround does not seem to work anymore.
Reloading the client shows the plugin working properly, but as soon as you hover over the account panel, it breaks. 
![image](https://user-images.githubusercontent.com/77126320/162392731-877cf8cd-0659-48ce-ae6a-53d912c295ba.png)

Turning the plugin on and off seems to do nothing, with subsequent attempts showing a "AccountDetailsPlus could not be stopped" error.

Stable 122979 (0691b82)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by NotDreppy** [comment]
Starting from Canary 123070 (e4f2640), the workaround DOES NOTHING. The plugin won't work at all.
For it to function again, you must reload the client, but it hides the account panel.
For the plugin to work properly as usual again, a new coded version is required.

**Comment by BlueStarBRS** [comment]
same here

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/162461003-30227bee-8c80-43f7-9221-5fd1ec9d9e77.png)

**Comment by BluCobalt** [comment]
![image](https://user-images.githubusercontent.com/37788256/162503938-1ae35314-698e-4906-92c3-eaaebd339bc8.png)
i have the same issue on powercord (through bdCompat, was working before) on linux and windows

**Comment by hackprotected** [comment]
I have this problem as well!

**Comment by OrniiDiien** [comment]
also have this problem

**Comment by ChunkleChip** [comment]
I am able to replicate this as well:
![image](https://user-images.githubusercontent.com/16302135/162605434-bdc74627-3edd-4bf8-82e7-cdbe14e2cbbc.png)

Stable 123305 (2d81cde)
BetterDiscord 1.5.2
Host 1.0.9004
Windows 10 64-Bit (10.0.19044)

**Comment by ccrowles** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/12866474/162614778-d46508df-c2d3-49d4-a945-7af9995e29f7.png)


Stable 123305 (2d81cde)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19042)

**Comment by LukeG007** [comment]
![image](https://user-images.githubusercontent.com/69555173/162637775-1a99a6c3-0e43-4446-8487-0d30b0f031b1.png)

**Comment by NotDreppy** [comment]
Issue closed.
The original creator has linked a pull request for modifying the plugin's code.
The new plugin file can be downloaded here: [https://github.com/rauenzi/BetterDiscordAddons/blob/89d6e4dbc94115e9d6dc626ece9a8b01bdc3219b/Plugins/AccountDetailsPlus/AccountDetailsPlus.plugin.js](url)

Side Note:
The version on BetterDiscord is still 1.0.1, please post the new one soon so people can download it from both 2 sites.

**Comment by awooooool** [comment]
> Issue closed. The original creator has linked a pull request for modifying the plugin's code. The new plugin file can be downloaded here: [https://github.com/rauenzi/BetterDiscordAddons/blob/89d6e4dbc94115e9d6dc626ece9a8b01bdc3219b/Plugins/AccountDetailsPlus/AccountDetailsPlus.plugin.js](url)
> 
> Side Note: The version on BetterDiscord is still 1.0.1, please post the new one soon so people can download it from both 2 sites.

Not accessible...? it redirects to https://github.com/rauenzi/BetterDiscordAddons/issues/url instead

**Comment by Rayjacker** [comment]
> Not accessible...? it redirects to https://github.com/rauenzi/BetterDiscordAddons/issues/url instead

Seems like it's a GitHub issue, copy the link and open it manually.

**Comment by BluCobalt** [comment]
You can also curl/wget [the updated raw file](https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/89d6e4dbc94115e9d6dc626ece9a8b01bdc3219b/Plugins/AccountDetailsPlus/AccountDetailsPlus.plugin.js)  into your plugin folder directly

**Comment by bbeenn1** [comment]
For those that are not fluent with GitHub: 
This is awaiting the merge request #582 to be fixed - it changes one line for the popout. 
Until that is closed this issue will still exist in the release made by rauenzi linked to the BetterDiscord repository.
