### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Tier6194** [rauenzi/BetterDiscordAddons#578]
**Which plugin/theme is this about?**
Accountdetailsplus
**Describe the Bug**
![image](https://user-images.githubusercontent.com/79399685/162483133-710e7b3d-7586-4ea4-98c3-90807cefdd20.png)
**To Reproduce**
i just enable the plugin
**Expected Behavior**
it to be normal
**Screenshots**
**Discord Version**
latest version
**Additional Context**

**Comment by xBiei** [comment]
same

**Comment by mrouie** [comment]
Is this the issue about the user icon disappearing? because I too am having this issue.
