### ISSUE TITLE
[Bug]  BetterRoleColour making user popout flash

### ISSUE THREAD

**Issue by lactri09** [rauenzi/BetterDiscordAddons#579]
**Which plugin/theme is this about?**
 BetterRoleColors

BetterRoleColors

**Describe the Bug**
 

when plugin is activated user details windown popup keeps opening and closing non stop at high speeds

**To Reproduce**

Turn on the plugin and click on fellow user in server and window will open and close rapidly

**Expected Behavior**

stay solid open 

**Screenshots**

**Discord Version**

Stable

**Additional Context**

All other plugins where closed and this still happened and when closed BetterRoleColors. It stoped hapening. (curently deleted the plugin for the meantime)

**Comment by Zacam** [comment]
I've also experienced this, but in my case, only when PronounDB is also loaded (in my case)

I can semi-workaround this issue by toggling PronounDB, but that then causes the Context Menu's for PronounDB to not display or any injection of it other than chat/conversation view user tagging.

Win 10 21H2 x64
Discord: Stable 123887
Better Discord: 1.5.3
BetterRoleColors: 0.8.17
PronounDB: 1.2.1

Strencher related when I opened this bug against PronounDB that it has something to do with a Discord change to Async loading. (https://github.com/Strencher/BetterDiscordStuff/issues/169)

**Comment by ArcWandx86** [comment]
This doesn't happen to me, and I don't have PronounDB, so that may be the case.

**Comment by rauenzi** [comment]
This should not happen with the new popouts
