### ISSUE TITLE
Settings not saving correctly

### ISSUE THREAD

**Issue by Enrico9431** [rauenzi/BetterDiscordAddons#583]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
Everytime I try to enable Leet (1337) and/or Extra Thicc in the Toolbar Buttons section and after that restart Discord, they'll be disabled again.

**To Reproduce**
Try enabling the aforementioned settings and restart you Discord to see them disabled again.

**Expected Behavior**
The settings should stay turned on when restarting Discord and not disabled again.

**Discord Version**
Stable 123455 (6191f50)
BetterDiscord 1.5.2
Host 1.0.9004
Windows 10 64-Bit (10.0.19044)

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
