### ISSUE TITLE
[Bug] Doesn't work

### ISSUE THREAD

**Issue by MaksiWWGaming** [rauenzi/BetterDiscordAddons#585]
**Which plugin/theme is this about?**
BetterFormatingRedux

**Describe the Bug**
None of the buttons do anything. It worked a few weeks back, doesn't work anymore. I click on a button to change the formating of my text, nothing happens

**To Reproduce**
Try typing something in chat and click on any setting, nothing will happen

**Expected Behavior**
Something should happen :P

**Screenshots**

**Discord Version**
Latest Discord PTB

**Additional Context**

**Comment by DraneLixX** [comment]
Hotfix here: https://github.com/rauenzi/BetterDiscordAddons/issues/576#issuecomment-1095686989

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
