### ISSUE TITLE
[Bug] BetterFormattingRedux buttons dont work

### ISSUE THREAD

**Issue by geroykarian** [rauenzi/BetterDiscordAddons#588]
**Which plugin/theme is this
 about?**
BetterFormattingRedux

**Describe the Bug**
After pressing the buttons, nothing happens

**To Reproduce**
I do not know

**Expected Behavior**
After pressing the buttons there will be a reaction

**Screenshots**
![126752629-2f94f1df-c626-4c95-9e7a-d4fc9e1a0d8f](https://user-images.githubusercontent.com/104049450/164146090-25488582-7f77-4e82-a4b7-aa97312998e1.gif)

**Discord Version**
Stable 90699 (baa844b)
BetterDiscord 1.5.3
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

**Additional Context**
No

**Comment by DraneLixX** [comment]
Hotfix here: https://github.com/rauenzi/BetterDiscordAddons/issues/576#issuecomment-1095686989

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
