### ISSUE TITLE
[Feature] AutoPlayGifs - Animate Emojis and Stickers when not focused

### ISSUE THREAD

**Issue by AKASGaming** [rauenzi/BetterDiscordAddons#589]
**Which plugin/theme is this about?**
AutoPlayGifs

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
Pls make Emojis and Stickers animate as well when not focused

**Additional context**
they are the only things that don't animate on my screen when not focused

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AutoPlayGifs
