### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GoldenWolfBW** [rauenzi/BetterDiscordAddons#591]
**Which plugin/theme is this about?**
Combination of using BetterRoleColors and PermissionViewer

**Describe the Bug**
When you click on a person with BetterroleColors, you can't see their permissions

**To Reproduce**
have both BetterRoleColors and PermissionsViewer enabled at the same time

**Expected Behavior**
It will not show permissions
**Screenshots**
![image](https://user-images.githubusercontent.com/104329370/165000961-152328a3-4847-4223-9ae0-7a1706033218.png)
![image](https://user-images.githubusercontent.com/104329370/165000995-4ab67756-f690-402c-a612-309138d83226.png)

**Discord Version**
Stable 125308 (7245591)
BetterDiscord 1.5.3

**Additional Context**
None, if needed more information, I can try to respond

(edited to make pictures so more detail)

**Comment by Traktool** [comment]
You can do this in the BetterRoleColors plugin :
![image](https://user-images.githubusercontent.com/22771674/178973733-98c8c599-64b3-411f-b3ac-db15978321e0.png)

This will disable the username color in the user popout, but nobody cares ?
User's permissions > colored username in user's popouts

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
