### ISSUE TITLE
[Bug] BetterRoleColors popouts flicker when BetterSearchPage is also enabled

### ISSUE THREAD

**Issue by TheSiriusET** [rauenzi/BetterDiscordAddons#592]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Popouts flicker when both plugins are enabled

**To Reproduce**
Enable both plugins at the same time

**Expected Behavior**
Popouts would not flicker, and would stay solid

**Screenshots**

**Discord Version**
Stable 122580

**Additional Context**

**Comment by rauenzi** [comment]
Sorry but I'm not tackling interop compat at this time.
