### ISSUE TITLE
[Bug] ServerSearch icon disappears after reloading Discord

### ISSUE THREAD

**Issue by Saltssaumure** [rauenzi/BetterDiscordAddons#593]
**Which plugin/theme is this about?**
ServerSearch

**Describe the Bug**
Resubmitting same issue as #544, but more general. Search button likes to disappear after refreshing/reopening Discord. Sometimes the button appears at first and disappears after a few seconds, and sometimes it survives until clicked. The popover does not appear if the button vanishes.

**To Reproduce**
- Enable plugin.
- Ctrl+R.
- Button disappears after a few seconds, or onclick.

**Screenshots**
[Video demonstration](https://www.youtube.com/watch?v=yXxa2p17AAA)

**Discord Version**
Stable 125721 (b3eed1d)  
BetterDiscord 1.5.3  
Host 1.0.9004  
Windows 10 64-Bit (10.0.19042)

**Additional Context**
Issue occurs regardless of other themes or plugins, tested with empty folders except this and ZeresPluginLibrary. Although, having many other plugins seems to increase the chance of the button vanishing without user input.

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for an alternative https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
