### ISSUE TITLE
In ServerSearch plugin the button is dissapering when opening discord

### ISSUE THREAD

**Issue by Bratice** [rauenzi/BetterDiscordAddons#594]
**Which plugin/theme is this about?**
ServerSearch

**Describe the Bug**
In ServerSearch plugin the button is dissapering when opening discord

**Discord Version**
Discord Canary

**Additional Context**
Please need a fix

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for an alternative https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
