### ISSUE TITLE
The plugin doesn't work (BetterFormattingRedux)

### ISSUE THREAD

**Issue by JustASimpleeGuy** [rauenzi/BetterDiscordAddons#596]
The plugin start normally, but the buttons doesn't work. I deleted the configs and restarted the Better Discord, and nothing.

**Comment by xsmashx88x** [comment]
same issue for me as well

**Comment by Technetium1** [comment]
Duplicate of https://github.com/rauenzi/BetterDiscordAddons/issues/576

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
