### ISSUE TITLE
BetterFormattingRedux crashes discord [Bug] 

### ISSUE THREAD

**Issue by Sowansow912** [rauenzi/BetterDiscordAddons#597]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
Whenever BetterDiscord attempts to start up, it immediately crashes

**To Reproduce**
Just add `BetterFormattingRedux.plugin.js` to the plugin folder

**Expected Behavior**
BetterDiscord to not crash

**Screenshots**
![Screenshot 2022-05-04 173501](https://user-images.githubusercontent.com/57327722/166829655-7e7b05ca-4428-4374-931c-01b92fffe19e.png)

**Discord Version**
Stable

**Comment by Sowansow912** [comment]
Fixed with most recent update

**Comment by Technetium1** [comment]
@Sowansow912 Please tell me that crash screen is a plugin. I need it.

**Comment by Sowansow912** [comment]
> @Sowansow912 Please tell me that crash screen is a plugin. I need it.

It comes from the Clearvision theme [https://github.com/ClearVision/ClearVision-v6](url)
