### ISSUE TITLE
[Feature] AutoPlayGifs -> Add Automod new systeme and even if discord isn't focus gif autoplay

### ISSUE THREAD

**Issue by Soulivan71** [rauenzi/BetterDiscordAddons#598]
_**Which plugin/theme is this about?**_
AutoPlayGifs.

**_Is your feature request related to a problem? Please describe._**
Auto animate avatar : discord automod system.

**_Describe the feature you'd like_**
Auto animate avatar : discord automod system. And even if discord is in background or second screen, autoplay gif etc

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AutoPlayGifs

**Comment by Soulivan71** [comment]
Mb I don't remembered
