### ISSUE TITLE
[Bug] BetterRoleColors colors username instead of nickname when Color Nickname

### ISSUE THREAD

**Issue by asorel1942** [rauenzi/BetterDiscordAddons#599]
Despite plugin settings set to color the nickname as shown below, plugin will color the username in popouts.

Stable 127019 (c8e7a02)
BetterDiscord 1.5.3
Host 0.0.17 Linux 64-Bit (5.17.1-3-MANJARO)

![image](https://user-images.githubusercontent.com/33983895/167163847-50b409af-d122-4bd2-b5e3-9163af5651d5.png)

![image](https://user-images.githubusercontent.com/33983895/167163593-3f85f09a-73ba-4d8f-97df-26c2fbd9ed14.png)

**Comment by rauenzi** [comment]
This should be fixed in the latest version!
