### ISSUE TITLE
AccountDetailsPlus hides my account panel

### ISSUE THREAD

**Issue by jack652** [rauenzi/BetterDiscordAddons#600]
**Which plugin/theme is this about?**
AccountDetailsPlus 

**Describe the Bug**
when AccountDetailsPlus is active, hides my account panel on the bottom next to the settings button

**To Reproduce**
have AccountDetailsPlus turned on

**Expected Behavior**
it should not hide the account pannel

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/167276019-cef7c363-c98e-4693-89a3-64d0521f0ff9.png)

**Discord Version**
stable

**Comment by TonyRL** [comment]
Duplicate of #590

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus
