### ISSUE TITLE
[Feature] Color Exceptions

### ISSUE THREAD

**Issue by Eden333** [rauenzi/BetterDiscordAddons#602]
**Which plugin/theme is this about?**

**Is your feature request related to a problem? Please describe.**

My friend has his role color in all black, while I'm using a dark-mode Theme. I can not see/read his name and he refuses to change it.

**Describe the feature you'd like**

If possible, add the function that the user can add exceptions to certain color codes, or make them appear in a different color:
If RoleColor = #000000
Then RoleColor = UserInput

"UserInput" could be a simple textbox in the plugin settings or something like that. 

or Maybe add that you can exclude users.

**Additional context**

**Comment by rauenzi** [comment]
You can already do this with CSS, I will not be adding this to the plugin
