### ISSUE TITLE
[Feature] Scroll Bar for Servers with Many Roles and Permissions

### ISSUE THREAD

**Issue by 31Delta** [rauenzi/BetterDiscordAddons#603]
**Which plugin/theme is this about?**
[PermissionViewer](https://github.com/rauenzi/BetterDiscordAddons/tree/f14d4161d2c4c9f8e9e635ec2ffe147b0015c8d8/Plugins/PermissionsViewer) Plugin

**Is your feature request related to a problem? Please describe.**
Yes. I am always frustrated when I can't view the whole thing when there are a lot of roles in the server.

**Describe the feature you'd like**
I would like for there to be a scroll bar for the detailed Server Permissions Viewer, and User Permissions Viewer for ease of viewing.

**Additional context**
Example of a Server Perms Viewer with lots of permissions, but not all of the roles/permissions are available 01: 
![image](https://user-images.githubusercontent.com/95656070/168889608-17be5626-a68a-48a8-bf5c-c7bb9889c491.png)

Example of a User Perms Viewer with lots/little roles but not all perms/roles are viewable 02:
![image](https://user-images.githubusercontent.com/95656070/168889984-401502aa-aff5-4465-bf7d-ac7dbd679df7.png)

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
