### ISSUE TITLE
[Bug] SERVER SEARCH PLUGIN NOT CLICKABLE

### ISSUE THREAD

**Issue by ynpr** [rauenzi/BetterDiscordAddons#604]
**Which plugin/theme is this about?**

**Describe the Bug**
When I enable the server search plugin and then click the search button nothing happens, no pop out or pop up nothing it just highlights it 

**Expected Behavior**
Its supposed to let me type in the box when I click on the server search button.

**Discord Version**
Stable     BetterDiscord 1.5.3 

**Additional Context**
PLEASEEEE HELP THIS PLUGIN IS MY FAVORITE AND MOST HELPFUL SINCE IM IN 150+ SERVERS

**Comment by ynpr** [comment]
![image](https://user-images.githubusercontent.com/105937892/169571172-18d72bd4-0255-45a5-9dc6-083e5661ff2d.png)
![image](https://user-images.githubusercontent.com/105937892/169571233-5710abf2-10cb-45f5-bb01-6227c7f92822.png)

First picture is when I enable the plugin, second picture is what happens after I click the button, its supposed to have a popout and let me type in the box.

**Comment by DriesMoo** [comment]
I have the same issue. Sometimes it doesn't even show up.

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for an alternative https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
