### ISSUE TITLE
PermissionsViewer Too Tall

### ISSUE THREAD

**Issue by Starstalker-awe** [rauenzi/BetterDiscordAddons#606]
With the number of different permissions Discord has added, the popup window isn't tall enough, and there is no possibility of scrolling, and it's not even possible to zoom out far enough to see all of them...
![image](https://user-images.githubusercontent.com/56582130/169623527-ba4e5f61-1100-4acc-9caf-b70ca9b7ebcd.png)

**Comment by ZackyGameDev** [comment]
I am having the same issue, the permissions viewer window seems to stretch beyond the screen

**Comment by ZackyGameDev** [comment]
So for now I fixed this issue by simply putting the following snippet in my `Custom CSS` tab in user settings:
```css
#permissions-modal {
    height: 80%;
}
```
this fix it for now

**Comment by Tempestest** [comment]
> So for now I fixed this issue by simply putting the following snippet in my `Custom CSS` tab in user settings:
> 
> ```css
> #permissions-modal {
>     height: 80%;
> }
> ```
> 
> this fix it for now (you can adjust the `height` value in here from 80% to anything you 
I tried this and it didnt work is there any other solution?

**Comment by ZackyGameDev** [comment]
are you sure that you clicked on "save" and "Update" after pasting this in the window? after that you should also try to reload the discord window (Ctrl + R or reopen discord or whatever) 

I am not a css/js expert so if this simple bodge doesn't work then I don't really have anything else to try

**Comment by Tempestest** [comment]
after reopening discord it worked thanks a lot

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
