### ISSUE TITLE
The Formatting doesn’t work anymore! [Bug] 

### ISSUE THREAD

**Issue by yiruzu** [rauenzi/BetterDiscordAddons#608]
**Which plugin/theme is this about?**

BetterFormattingRedux

**Describe the Bug**

The Formatting doesn’t work anymore…

**To Reproduce**

…

**Expected Behavior**

…

**Screenshots**

…

**Discord Version**

Stable

**Additional Context**

It worked a few weeks ago.

**Comment by Shadofer** [comment]
Same issue here

**Comment by Shadofer** [comment]
Fixed with https://github.com/rauenzi/BetterDiscordAddons/issues/576#issuecomment-1095686989
