### ISSUE TITLE
[Bug] Upon the ACCESSIBILITY_KEYBOARD_MODE_ENABLE event, the search button just dissapears.

### ISSUE THREAD

**Issue by TheRedXD** [rauenzi/BetterDiscordAddons#609]
**Which plugin/theme is this about?**

ServerSearch

**Describe the Bug**

Upon turning num lock off and typing some numbers, it appears that whatever runs the accessibility stuff in discord interferes with this extension.

**To Reproduce**

1. Make sure Num Lock is off
2. Click around and see it happen (you need to use the discord accessibility stuff)

**Expected Behavior**

Normal behavior upon using accessibility

**Screenshots**

Not applicable

**Discord Version**

Stable

**Additional Context**

No additional context required, other than my extension list (I got it using the BdApi because easier to do lol)
![image](https://user-images.githubusercontent.com/56270596/169882666-a1f1757e-8452-45ec-9897-1fabf75038d8.png)

**Comment by TheRedXD** [comment]
Quick note: My custom theme does not appear to interfere with anything, so should be all good and my theme should not be required hopefully

**Comment by TheRedXD** [comment]
whoops lol

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for an alternative https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
