### ISSUE TITLE
[Feature] Show Server Avatar 

### ISSUE THREAD

**Issue by aaashleyyyy** [rauenzi/BetterDiscordAddons#613]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Is your feature request related to a problem? Please describe.**
'Tis not

**Describe the feature you'd like**
In addition to your server nickname that shows when you have a server open, also show the server avatar.

**Additional context**
 Not needed

**Comment by rauenzi** [comment]
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus
