### ISSUE TITLE
[Bug] RoleMember plugin not working

### ISSUE THREAD

**Issue by Varatros** [rauenzi/BetterDiscordAddons#617]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
The popup appears to be broken again.

**To Reproduce**
Click on a mentioned role or click on a role in the server context menu.

**Expected Behavior**
The popup appears and I can see who's in a role.

**Screenshots**
It's throwing this error
![image](https://user-images.githubusercontent.com/66185110/172945495-335da370-1ae4-4052-80c9-d6376b258d30.png)

**Discord Version**
Stable 131204

**Additional Context**
Most likely discord updated something and the plugin just needs to be updated to work.

**Comment by cedrixm** [comment]
+1

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
