### ISSUE TITLE
[Bug] [BetterFormattingRedux] Icons not doing anything

### ISSUE THREAD

**Issue by TheBlackEntity** [rauenzi/BetterDiscordAddons#619]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
When you click on any icon which should enter the according formatting code

**To Reproduce**
Try clicking on any icon

**Expected Behavior**
When you clidk the icon, it should input the according formatting code

**Discord Version**
Stable

**Comment by Rekuiemu** [comment]
Think these plugins are abadoned

**Comment by TheBlackEntity** [comment]
> Think these plugins are abadoned 

Oof

**Comment by laurelenn** [comment]
Same here, really sad

**Comment by FawazTakhji** [comment]
someone fixed it #618

**Comment by TheBlackEntity** [comment]
> someone fixed it #618

Thanks for the info. Will try it out

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
