### ISSUE TITLE
[Bug] ReplySystem Seems to be not showing up after update of the plugin. 

### ISSUE THREAD

**Issue by BarterClub** [rauenzi/BetterDiscordAddons#62]
ReplySystem, Let me know if you need anything to show.

**Comment by rauenzi** [comment]
Are you using light theme?

**Comment by BarterClub** [comment]
Dark.

**Comment by rauenzi** [comment]
make sure you're on latest version, works for everyone that had it broken by the update

**Comment by BarterClub** [comment]
Nope just downloaded it. Seems still not to be working. Do you know of any other plugins that have conflicts with it?

**Comment by rauenzi** [comment]
Possibly quoter

**Comment by BarterClub** [comment]
ok got it to work. Seemed to be conflicting with somrthing. Also the text is very hard to see in text. Icon is fine tho. 
![image](https://user-images.githubusercontent.com/10663563/43363000-e196855a-92ad-11e8-9587-170c234741d5.png)

**Comment by rauenzi** [comment]
Compatibility should be fixed, same with colors.
