### ISSUE TITLE
[Bug] BetterRoleColor not coloring roles names in sidebar inside threads.

### ISSUE THREAD

**Issue by Crec0** [rauenzi/BetterDiscordAddons#620]
**Which plugin/theme is this about?**
BetterRoleColor

**Describe the Bug**
Role name in the sidebar in the threads is not colored.

**To Reproduce**
- Have a colored role and join a thread.
- Observe the sidebar the role name is not colored.

**Expected Behavior**
Role name should be colored with role color in threads just like any other channel.

**Screenshots**
Expected: (Screenshot from normal channel)
![image](https://user-images.githubusercontent.com/83436716/174003269-7a64b17e-677f-444d-b0d5-84e33f379187.png)
Observed: (Screenshot from thread channel)
![image](https://user-images.githubusercontent.com/83436716/174003271-a5cea2e9-f275-44de-97b6-719fc487e5af.png)

**Discord Version**
Canary

**Additional Context**
- N/A

**Comment by rauenzi** [comment]
This should be fixed in the latest version!
