### ISSUE TITLE
[Bug]  RoleMembers  The output of users is not displayed when clicking

### ISSUE THREAD

**Issue by LongerSayros** [rauenzi/BetterDiscordAddons#621]
**Which plugin/theme is this about?**
 RoleMembers

**Describe the Bug**
The output of users is not displayed when clicking ( no button ) and hovering over the necessary role ( the plugin should output users to the next window of this kind with the necessary role ) Maybe I don't understand how it is at all, or there is clearly something faulty 
(  https://i.stack.imgur.com/SCYrl.png ) 

**To Reproduce**
Install the plugin in the plugins folder, right-click on the server icon and select Role Members, then try clicking on roles 

**Expected Behavior**
A list of participants with the desired role will be displayed

**Screenshots**
https://i.stack.imgur.com/SCYrl.png 

**Discord Version**
Stable 132320 (8d01c6a) ,BetterDiscord 1.5.3 Host 1.0.9005

**Additional Context**

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
