### ISSUE TITLE
[Bug] The list of role users is not displayed

### ISSUE THREAD

**Issue by Dixtasy** [rauenzi/BetterDiscordAddons#622]
RoleMembers

The list of role users is not displayed

![unknown](https://user-images.githubusercontent.com/105545200/174294134-e37e7dfc-e480-4229-9baf-9c056d0af953.png)

Version:
Stable 132647 (57cb092)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.19043)

**Comment by VLBRTN** [comment]
+1

**Comment by Airwayx** [comment]
+1

**Comment by cedrixm** [comment]
+1

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
