### ISSUE TITLE
[Bug] RoleMembers Context Menu Missing

### ISSUE THREAD

**Issue by Benomat** [rauenzi/BetterDiscordAddons#624]
This has been fixed at the latest version.
Same issue as https://github.com/rauenzi/BetterDiscordAddons/issues/511
Plugin is on newest version.

_Originally posted by @rauenzi in https://github.com/rauenzi/BetterDiscordAddons/issues/511#issuecomment-1019442266_

**Comment by rauenzi** [comment]
That's from 5 months ago... Things can break in the meantime and you don't need to mention me.

**Comment by Benomat** [comment]
How do I fix it? Or do just wait for a fix?

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
