### ISSUE TITLE
[Bug] RoleMembers has completely stopped working

### ISSUE THREAD

**Issue by Hiviexd** [rauenzi/BetterDiscordAddons#625]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
It doesn't work anymore, role list doesn't appear in the context menu anymore (maybe related to the plugin not being able to initially load the context menu)

**To Reproduce**
right-click a server icon

**Expected Behavior**
Role members appear in the context menu

**Screenshots**
![image](https://user-images.githubusercontent.com/62819481/177883878-a538494a-540c-434d-9889-e0e524bfd6cd.png)

**Discord Version**
Stable 135402 (4c5bcd6)

**Comment by XxUnkn0wnxX** [comment]
yep same here, just noticed.. I miss this :(

**Comment by RiDaku** [comment]
It's been steadily declining in functionality for a while. It'd show the roles, but wouldn't open the members list. Then, as of over a week ago, the plugin itself stopped working. Very sad, as it was very helpful.

**Comment by My1Legocraft** [comment]
> It's been steadily declining in functionality for a while. It'd show the roles, but wouldn't open the members list. Then, as of over a week ago, the plugin itself stopped working. Very sad, as it was very helpful.

I have found a way to still see members in what role, not a plugin. Just found my own way.

**Comment by aetinx** [comment]
> > It's been steadily declining in functionality for a while. It'd show the roles, but wouldn't open the members list. Then, as of over a week ago, the plugin itself stopped working. Very sad, as it was very helpful.
> 
> I have found a way to still see members in what role, not a plugin. Just found my own way.

What's the way?

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
