### ISSUE TITLE
[Bug] all dropdown menus either not appearing or appearing, but not doing anything

### ISSUE THREAD

**Issue by redstefan1** [rauenzi/BetterDiscordAddons#626]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
whenever I try to open the toolbar it opens, but none of the buttons do anything, however if I write the wrapper myself it works and the formatting is applied, when digging through the setting I noticed that all drop down menus do not appear (the arrow turns as if it was appearing, but it doesn't)
**To Reproduce**
either go to settings and click on one of the dropdown menus or open the toolbox and try using it

**Expected Behavior**
I expected the dropdown menus to well, drop down and the toolbar to type the wrappers if you click the corresponding button if you click on any of the buttons

**Screenshots**

https://user-images.githubusercontent.com/69212977/178010962-9cba897d-d16a-48aa-b186-66b23af72162.mp4
Sorry if Videos don't work for some reason, I just felt like this specific issue is better suited for a screen recording

**Discord Version**
Stable

**Additional Context**
I have tried the following things to fix it: restart computer, reload the plugin, reload dc, redownload the plugin, repair betterdc using the repair tool in the downloader, also of note: right clicking on the codeblock button, while bringing up the menu for selecting programming language, if you press any of the buttons there it does also not work, so only the act of pasting in the wrapper seems to be broken there (also it used to work before)

**Comment by workframes** [comment]
Edit your plugin

**Comment by Maybe0sir** [comment]
I'm guessing I am supposed to edit line 511, but it's still not working for me

**Comment by rauenzi** [comment]
This has been fixed with the latest update!
