### ISSUE TITLE
[Bug] The Permission Liste button not working

### ISSUE THREAD

**Issue by Cyber24-Dr** [rauenzi/BetterDiscordAddons#629]
The module ( Permissionviewer ) is loaded, but the option is no longer present, you can no longer use it, 

See the image https://prnt.sc/PRPicCZ0OVJ7 
https://prnt.sc/hxQ0kOD4Fu12

Please update it so that it works again

**Comment by MauriceX24** [comment]
Same here. Could you please fix this? I use this plugin for support and sometimes its very helpful if users cant manage a server.
I am ready to donate to  you for this ^^
Cheers.

**Comment by Cyber24-Dr** [comment]
Same

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
