### ISSUE TITLE
New Discord Update broke the server list

### ISSUE THREAD

**Issue by Whomandwhy** [rauenzi/BetterDiscordAddons#63]
Once more, discord has seemingly needlessly updated and broke this wonderful theme.
The theme USED to make it so that the servers with unread messages would have their icons outlined, as oppose to a dot on the side like discord normally does it (which I hate, as it's very very hard to notice with a quick glance)
(My bad, for clarification I mean the Transient Material Theme)

**Comment by HRTHXC** [comment]
It's done the same here. The entire server list is no longer transparent.

**Comment by rauenzi** [comment]
The server list has now been fixed!
