### ISSUE TITLE
[Bug] Interface Isssues.

### ISSUE THREAD

**Issue by ShaneMonti** [rauenzi/BetterDiscordAddons#634]
[**Which plugin/theme is this about?**
PermissionsViewer.

**Describe the Bug**
The interface isn't usually working, missing the scroller to scroll up or down. And it cannot show all the permission/roles.

**To Reproduce**
Simply click the view permission's viewer.

**Expected Behavior**
It should have a scroller to scroll up or down to view the whole menu (It should appear all permission/roles).

**Screenshots**
![image](https://user-images.githubusercontent.com/110621001/182890648-60cd9cd0-90e1-46a3-8b91-e5b887624921.png)
![image](https://user-images.githubusercontent.com/110621001/182890660-b40b8ee6-ffcd-476c-8dd9-2278e64e8d89.png)

**Discord Version**
Stable

**Additional Context**
None.

**Comment by ThalusA** [comment]
When I click on users I also have this beautiful permissions list in their user popup
<img width="214" alt="image" src="https://user-images.githubusercontent.com/15985204/183314895-0fe5eb87-365d-4081-a038-00e0615437e6.png">

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
