### ISSUE TITLE
[Bug] BetterFormattingRedux toolbar buttons not working

### ISSUE THREAD

**Issue by rayjay7225** [rauenzi/BetterDiscordAddons#639]
**Which plugin/theme is this about?**
BetterFormattingRedux (version 2.3.12)

**Describe the Bug**
Buttons in the toolbar do not do anything and there are no errors in console 

**To Reproduce**
I do not know

**Expected Behavior**
The expected behavior is that when clicking a button in the plugin toolbar, it would format the text

**Screenshots**
![Discord_E7xBpE2LrQ](https://user-images.githubusercontent.com/79537106/183441604-417e3670-5b59-4443-af10-30683d794d35.gif)
(gif made with shareX)

**Discord Version**
Stable

**Additional Context**
There are no errors in the console,
The plugin starts normally,
I disabled all other plugins but makes no difference,

hashes of the plugin :
SHA1 : e94d9d29c54c985ea1a54b4941a270472b260c49
MD5 : a6c32bc422fe49dc38a2ecb3d5343493
SHA256 : a4827c45485657c83e5f922be4afde2cd01c17037f81bab1342ce2e6088c88d9

plugin code : 
[https://pastebin.com/raw/6R5ifBJ8](https://pastebin.com/raw/6R5ifBJ8)

**Comment by zluckytraveler** [comment]
I completely agree with this, it does not work for me either!

**Comment by WojtekPlay** [comment]
its been like that for me for like a month or 2

**Comment by BigBoss320** [comment]
there was a non official fix for it and i just understand how to fix it. You have to do it manually. Go here 
: https://github.com/rauenzi/BetterDiscordAddons/pull/618/files. Then go to your discord settings, plugin section, find the Better Formatting plugin and click on the pen to edit it. And after that, replace the lines that are in red on the site by the one that are green in your discord editing window.
For example, the line 3 is in red and replaced by the green, copy it, go to your editing window, delete line 3, paste the line you copied earlier

**Comment by BigBoss320** [comment]
it is working fine for me now

**Comment by rayjay7225** [comment]
thank you, works perfectly now <3
