### ISSUE TITLE
Custom CSS background is blocked by default background

### ISSUE THREAD

**Issue by Naranzhia** [rauenzi/BetterDiscordAddons#64]
![image](https://user-images.githubusercontent.com/34827124/43672779-ad827014-97e7-11e8-95af-aba1ba457cf9.png)
I don't know how it happened, little help?

**Comment by rauenzi** [comment]
A discord update happened within the last hour or so

**Comment by Naranzhia** [comment]
Oh, do I have to wait?

**Comment by rauenzi** [comment]
Are you using one of my themes like TransientMaterial. Why was this issue posted here?

**Comment by warmistead** [comment]
TransparencyPatcher v0.0.2 seems to be having an issue after the most recent update, same issue, the default discord background is covering custom backgrounds and seems to be messing with the maxmize function for the window as well.

**Comment by rauenzi** [comment]
Transparency patcher is not a theme, so your theme is what needs to update to show your custom background. Maximizing issues and such are issues native to electron not something I can mitigate
