### ISSUE TITLE
[Feature] Send Audio messages through dms.

### ISSUE THREAD

**Issue by killer0182** [rauenzi/BetterDiscordAddons#641]
Hello!
I was wondering if there is a plugin which can be used to send audio messages in discord dms without needing to use a third-party application, like telegram, whatsapp, etc. I could only find one plugin [ https://github.com/MKSx/Send-Audio-Plugin-BetterDiscord#readme ] but it has been archived by the owner so it doesn't work. It would be really useful if I can get a plugin that does this job.
Thanks for reading!

**Comment by rauenzi** [comment]
While I think this is a good plugin to have, I am not looking to take on more projects at this time, sorry!
