### ISSUE TITLE
[Bug] BetterFormattingRedux shows changelog every time

### ISSUE THREAD

**Issue by theapathyimp** [rauenzi/BetterDiscordAddons#642]
**Which plugin/theme is this about?**
BetterFormattingRedux v2.3.12

**Describe the Bug**
Changelog opens every time client is (re)loaded.

**To Reproduce**
Open or reload Discord.

**Expected Behavior**
Changelog opens once after initial update and then does not pop up again unless using the dedicated button in Plugins setting.

**Screenshots**
![Screenshot of Issue](https://user-images.githubusercontent.com/8020193/186043977-e071bb77-0255-48ed-ad04-3b895b291345.png)

**Discord Version**
Stable

**Additional Context**
![Screen Recording of Issue](https://user-images.githubusercontent.com/8020193/186049061-30cc0ca9-09e0-42cf-aac3-75c324dbb0c2.mp4)

**Comment by rauenzi** [comment]
You likely have multiple copies of the plugin installed. Please display the contents of your plugin folder

**Comment by theapathyimp** [comment]
> You likely have multiple copies of the plugin installed. Please display the contents of your plugin folder

This is not the case.

![Cz6rhiJ4b0wKAotr](https://user-images.githubusercontent.com/8020193/187818405-7a6035c0-2162-4055-a257-5fc0ad7de5d2.png)

**Comment by theapathyimp** [comment]
> You likely have multiple copies of the plugin installed. Please display the contents of your plugin folder

That is not the case.

![image](https://user-images.githubusercontent.com/8020193/190022871-e2adc810-f1f0-4eef-9fdd-198a0482ee1e.png)

**Comment by rauenzi** [comment]
Try removing all plugins except this and the library
