### ISSUE TITLE
[Bug] BDContextMenu not functioning

### ISSUE THREAD

**Issue by k4zo** [rauenzi/BetterDiscordAddons#643]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
Plugin does not add anything to context menu

**To Reproduce**
Enable BDContextMenu
Try to find any BD option in the user settings context menu

**Expected Behavior**
The options appear

**Screenshots**
[The bottom most button is from developer/experiments options, no BD related tabs to be found](https://i.imgur.com/fr0QNeG.png)

**Discord Version**
Stable

**Additional Context**
Plugin has been broken for months, assuming I'm the only person using it because I haven't seen a report of this issue from anyone else

**Comment by rauenzi** [comment]
This has been fixed in the latest update!
