### ISSUE TITLE
PermissionsViewer dont work [Bug] 

### ISSUE THREAD

**Issue by dankYoff** [rauenzi/BetterDiscordAddons#644]
**Which plugin/theme is this about?**
PermissionsViewer/dont show button in discord

**Describe the Bug**
Doesn't show a button to access roles in Discord

**Screenshots**
![зображення](https://user-images.githubusercontent.com/91318807/186802274-e52a1198-4f58-45bf-965c-489e11d411b4.png)
![зображення](https://user-images.githubusercontent.com/91318807/186802426-c59572ae-f793-478e-a9aa-cd6a4a52af5a.png)
Dont show a button

**Discord Version**
Stable 143763 (f3d44af)
BetterDiscord 1.6.3
Host 1.0.9006 Windows 10 64-Bit (10.0.19044)

**Comment by CodedAuster** [comment]
Can reproduce, no button, same issues. 
Stable 144057 (7146eaa)
BetterDiscord 1.6.2
Host 1.0.9006 Windows 10 64-Bit (10.0.19042)

**Comment by XxUnkn0wnxX** [comment]
This is still not working even after Commit: a9b7140adcd8ef0d1346ebbff166da9a82365340 @rauenzi 
Still dead on
```text
Stable 144494 (22d9861)
BetterDiscord 1.6.3
Host 0.0.268 OS X 10.15.7 (20.6.0)
```

Plugin Ver: 0.2.4

<img width="1549" alt="Screen Shot 2022-08-30 at 1 40 26 pm" src="https://user-images.githubusercontent.com/2242880/187344428-56e2537a-2088-488c-9116-59079762e664.png">
There is no **Permissions** Button found anywhere on any of the context menu's
<img width="340" alt="Screen Shot 2022-08-30 at 1 41 54 pm" src="https://user-images.githubusercontent.com/2242880/187344458-d4d42769-2731-418e-9e1c-e01f7f9d7f43.png">
<img width="349" alt="Screen Shot 2022-08-30 at 1 41 47 pm" src="https://user-images.githubusercontent.com/2242880/187344462-efacd4f8-538c-4b7d-adbd-20145047ef66.png">

[debug.log](https://github.com/rauenzi/BetterDiscordAddons/files/9449400/debug.log)
[discord.com-1661830830373.log](https://github.com/rauenzi/BetterDiscordAddons/files/9449401/discord.com-1661830830373.log)

**Comment by rauenzi** [comment]
No need to mention me, please update to the latest version of the library!

**Comment by rauenzi** [comment]
Also note that the plugin does not currently work with the profile skins which are still in A/B testing and not finalized
