### ISSUE TITLE
[BDContextMenu] Plugin not starting with Discord

### ISSUE THREAD

**Issue by zuzumi-f** [rauenzi/BetterDiscordAddons#646]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
BDContextMenu doesn't show when starting or reloading Discord

**To Reproduce**
Start or Reload Discord - Plugin doesn't show - Reload the plugin so it shows

**Expected Behavior**
Not need to reload the plugin every start

**Screenshots**
https://user-images.githubusercontent.com/79029257/187426385-6c4a382b-cb99-49ac-97bc-ee8072feb11d.mp4

**Discord Version**
Stable 144494 (22d9861)

**Comment by rauenzi** [comment]
Does it appear when right clicking a second time after reloading?

**Comment by zuzumi-f** [comment]
oh, yeah it does...
