### ISSUE TITLE
[Other] SmallCaps F is using "ғ" instead of "ꜰ"

### ISSUE THREAD

**Issue by Winsane** [rauenzi/BetterDiscordAddons#647]
The current SmallCaps F is using "ғ" (https://www.compart.com/en/unicode/U+0493)
It can be replaced with the actual Unicode Small Capital F "ꜰ" (https://www.compart.com/en/unicode/U+A730)
S is also currently a standard lowercase "s" instead of Unicode Small Capital S "ꜱ" (https://www.compart.com/en/unicode/U+A731)

**Comment by rauenzi** [comment]
This will be available in the next release of the plugin which won't happen until #682 is merged
