### ISSUE TITLE
[Bug] BetterFormattingRedux overlaps with the Scroll-to-bottom button

### ISSUE THREAD

**Issue by robmonte** [rauenzi/BetterDiscordAddons#649]
**Which plugin/theme is this about?**
BetterFormattingRedux 

**Describe the Bug**
When Discord inserts the button in the bottom-right of chat to jump to the present messages of a chat, oftentimes when trying to click it, you mouse over the formatting arrow which opens the formatting options over the button.

**Expected Behavior**
This addon should either permanently move the jump to present button up enough to never overlap, or move the button up upon expansion of the formatting tools. I would prefer the first one.

**Screenshots**

![image](https://dl.dropboxusercontent.com/s/o6a6f142w2z697c/Discord_GRU7fbQXoK.gif)
(Ignore the invisible cursor, not sure why it didn't show up in the recording)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
You should ask the author of your theme to add support for this plugin, not vice versa.

**Comment by robmonte** [comment]
@rauenzi 
Sorry, I am so used to my theme that I forgot that button wasn't the stock design of the Jump To Present button.

However, the issue still exists without theming as you can see here:
https://dl.dropboxusercontent.com/s/238msoxmn347ffu/Discord_N5dsZIvn8P.gif
