### ISSUE TITLE
Can't find the search button where is supposed to be 

### ISSUE THREAD

**Issue by orchid13** [rauenzi/BetterDiscordAddons#65]
As you can see the plugin is installed.
![discord_2018-08-15_15-36-26](https://user-images.githubusercontent.com/41364030/44143337-ffea2664-a0a0-11e8-916b-cd73d3efdb81.png)
![discord_2018-08-15_15-32-17](https://user-images.githubusercontent.com/41364030/44143304-ddd506d4-a0a0-11e8-9c07-fba31b1737bd.png)
yet there's no Search server button you can see that in this SS.
![discord_2018-08-15_15-33-52](https://user-images.githubusercontent.com/41364030/44143305-de0e40ac-a0a0-11e8-841e-6fe13cc1ccc3.png)

**Comment by rauenzi** [comment]
Update the plugin
