### ISSUE TITLE
[Bug] ServerSearch

### ISSUE THREAD

**Issue by Fefedu973** [rauenzi/BetterDiscordAddons#650]
**ServerSearch**

**Not working (nothing happend when clicking the button**

**Enable the plgin - try to press the search button**

**Open search ui**

**![image](https://user-images.githubusercontent.com/80718477/188695022-000a15cf-a124-4f67-8e27-23dace52384b.png)**

**Stable**

**Additional Context**
error : 

a1aea796b90de1cca0d7.js:126 Uncaught TypeError: Cannot read property 'append' of null
    at ServerSearch.showPopout (VM791 ServerSearch.plugin.js:295)
    at ServerSearch.showLargePopout (VM791 ServerSearch.plugin.js:387)
    at HTMLDivElement.eval (VM791 ServerSearch.plugin.js:284)
    at HTMLDivElement.r (a1aea796b90de1cca0d7.js:126)
showPopout @ ServerSearch.plugin.js:295
showLargePopout @ ServerSearch.plugin.js:387
eval @ ServerSearch.plugin.js:284
r @ a1aea796b90de1cca0d7.js:126

**Comment by rauenzi** [comment]
This plugin was discontinued https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ServerSearch
