### ISSUE TITLE
[Bug] Blur in DMs dose not save

### ISSUE THREAD

**Issue by Tsumitsuki** [rauenzi/BetterDiscordAddons#653]
**Which plugin/theme is this about?**
BlurNSFW

**Describe the Bug**
Enabled blur in DMs is not saved over sessions.
After restarting Discord it is disabled again.

Only in DMs

**Discord Version**
Stable 146284 (57b3d6d)
BetterDiscord 1.6.3

**Comment by rauenzi** [comment]
Should be fixed with latest update.
