### ISSUE TITLE
[Bug] Colours User in Server are shown White instead of the Colour assigned

### ISSUE THREAD

**Issue by gloomykid** [rauenzi/BetterDiscordAddons#658]
**Which plugin/theme is this about?**

BetterRoleColorsv0.9.0by [Zerebos](https://twitter.com/IAmZerebos)

**Describe the Bug**

Nothing has changed about the roles or settings, but the chat text of users in discord servers are no longer shown in the same colour as the assigned role colour. 

**To Reproduce**

As said above.

**Expected Behavior**

As said above.

**Screenshots**

[https://i.imgur.com/eexPFrx.png](url)

**Discord Version**

Stable 149345

**Additional Context**

As said above, nothing has changed about the add on or discord, and it no longer works as described.

**Comment by ry0408** [comment]
Can confirm still does not work, this is likely due to the update that Discord pushed out recently and broke all betterdiscord plugins

**Comment by rauenzi** [comment]
Should be fixed with latest update.
