### ISSUE TITLE
[Other] BlurNSFW not working with new discord version, questions

### ISSUE THREAD

**Issue by sixy69** [rauenzi/BetterDiscordAddons#659]
hi it is around 2 days that BlurNSFW is not working. is it normal? i guess it needs an update, if so how many days could it takes?

**Comment by Rayjacker** [comment]
About 2 days ago, Discord updated parts of it's [engine,](https://github.com/BetterDiscord/BetterDiscord/issues/1404#issuecomment-1258808958) breaking betterdiscord and all plugins. AFAIK, plugins need to be essentially rewritten to work with the new changes.

**Comment by sixy69** [comment]
yep i know i was wondering what would the ETA be

**Comment by Handoff2901** [comment]
Go look at how long it took to write these plugins. Given that they will need to be re-written, it will take that amount of time, minus the time needed for making the original design.

**Comment by rauenzi** [comment]
Should be fixed with latest update.
