### ISSUE TITLE
ImageToClipboard isn't working anymore

### ISSUE THREAD

**Issue by yorik100** [rauenzi/BetterDiscordAddons#66]
No "Copy image" button

**Comment by rauenzi** [comment]
Can you give me more information like your version and console errors? No one else has had this issue since the update before last.

**Comment by yorik100** [comment]
I'm on the last Discord update and it doesn't work on BOTH of my computers, last version of the plugin, Windows 7 and 10 tried on 2 different Discord accounts, reloaded Discord, the button just doesn't show up

**Comment by rauenzi** [comment]
Do you have better discord installed? Have you checked console for errors?

**Comment by yorik100** [comment]
0 errors and I reinstalled BandageBD

**Comment by yorik100** [comment]
![image](https://user-images.githubusercontent.com/16320315/44231491-a3371180-a19e-11e8-8706-0f2f058c062f.png)

**Comment by yorik100** [comment]
I reinstalled BandageBD

**Comment by rauenzi** [comment]
What is your locale?

**Comment by yorik100** [comment]
What is my locale?

**Comment by rauenzi** [comment]
Nevermind, I've determined the error was because the plugin didn't have a translation to your language. I have just pushed a fix to the library for this, it will fallback to English when the proper translation is not found. Restarting discord should fix this.

**Comment by intrnl** [comment]
Should have a toast on first time use of the  plugin when there's no translations.
