### ISSUE TITLE
[Feature] Inline-TeX support

### ISSUE THREAD

**Issue by MySurmise** [rauenzi/BetterDiscordAddons#663]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the feature you'd like**
Add Inline-TeX Button to format window just like e.g. the Notion TeX function works.
Would probably require you to send an image of the Text, but would be really great so I don't have to add more Plugin Junk to my Discord and this extension does everything formating-related

**Comment by rauenzi** [comment]
There are other plugins that work for TeX, I consider it out of scope for this plugin. TeX goes beyond just "formatting" imo.
