### ISSUE TITLE
Not work BetterFormattingRedux[Bug] 

### ISSUE THREAD

**Issue by MarlonPra** [rauenzi/BetterDiscordAddons#664]
**Which plugin/theme is this about?**
BetterFormattingRedux.

**Describe the Bug**
 When I try to make a text bold I select it completely and when I hit the bold button nothing happens, and it doesn't work with the other buttons either, it doesn't do anything.

**To Reproduce**
[screen-capture (1).webm](https://user-images.githubusercontent.com/79668146/195452379-3458de00-d240-4098-bed9-b3da7979670b.webm)

**Expected Behavior**

**Screenshots**

**Discord Version**
Stable 152033 (b78cee4)

**Additional Context**

**Comment by rauenzi** [comment]
Fixed
