### ISSUE TITLE
[Bug] BetterRoleColors 0.9.1 - Role Colors Reverted upon Not Being Displayed and Plugin May Cause Startup Crash Loops

### ISSUE THREAD

**Issue by hunter10bt** [rauenzi/BetterDiscordAddons#665]
**Which plugin/theme is this about?**
BetterRoleColors 0.9.1

**Describe the Bug**
- The colors displayed sometimes do not match the supposed color of the role
- BD sometimes crashes at the startup with the plugin enabled: Deletion fixes the issue 
- In the member list, the role colors go back to default when the name of the role in question is no longer at the screen. This can be repeated by switching channels then scrolling down the member list

**To Reproduce**
_Member List Role Colors Reversion_: This can be repeated by switching channels then scrolling down the member list
_Instability and Crash Loops_: May not be a consistent issue, but more likely to happen when displaying a channel in which a large number of different roles are displayed

**Expected Behavior**
The color of the roles in member list retain their proper colors even when they are no longer displayed

**Screenshots**
(None Applicable)

**Discord Version**
Stable

**Additional Context**
Diagnosed in manually installed BetterDiscord 1.8.0 (latest commit: `Fix ContextMenu Patcher`)

**Comment by hunter10bt** [comment]
Ye, the second issue is really difficult to reproduce even for me because the crash conditions seem quite random and the only thing I knew was that deleting the plugin fixes the random crashes.

**Comment by ShizCalev** [comment]
Getting the crash loops here too. They seem far more prominent when viewing servers with a large number of channels / users.

Example server:
https://discord.com/invite/VW9ZEwc

**Comment by hunter10bt** [comment]
Alright, after a few more rounds of testing and looking out in the main support server, the crash loops turned out to be an issue with another plugin (specifically TypingUsersAvatars).
