### ISSUE TITLE
[Feature] AutoUpdate link

### ISSUE THREAD

**Issue by Dominikodz** [rauenzi/BetterDiscordAddons#666]
**Which plugin/theme is this about?**
PermissionsViewer

**Is your feature request related to a problem? Please describe.**
Yes. I had to manually search for new version of this plugin

**Describe the feature you'd like**
AutoUpdate link in meta headline of plugin

**Additional context**
![obraz](https://user-images.githubusercontent.com/64926921/195606127-da8fec2b-1051-4847-b833-4b7e1bab7ed4.png)

**Comment by rauenzi** [comment]
There is no such thing

**Comment by Dominikodz** [comment]
Are you sure about this? there is @updateURL in the meta tag in other plugin that has been auto-updated
i.e 
![obraz](https://user-images.githubusercontent.com/64926921/195923673-95cffb45-10bf-4cea-9e16-0115ae5050bf.png)

**Comment by rauenzi** [comment]
Yes I am certain. My library already has an updating system that never used the `updateUrl` nor do even DevilBro's plugins. `@updateUrl` was an old relic of a plan that never came together over a year ago to have a very simple and naive updater inside of BD itself. Some devs added the tag in anticipation of that feature, but it never came to fruition.

Source: I am the BD dev.
