### ISSUE TITLE
[Bug] BetterFormattingRedux button/setting saving not working

### ISSUE THREAD

**Issue by Enrico9431** [rauenzi/BetterDiscordAddons#667]
**Which plugin/theme is this about?**
BetterFormattingRedux v2.3.14

**Describe the Bug**
Leet (1337)/Extra Thicc in the Toolbar Buttons and Active Formats section do not stay turned on after restarting Discord

**To Reproduce**
Turn the settings on and restart your Discord

**Expected Behavior**
Turning them on should stay like that through restarting

**Discord Version**
Stable

**Additional Context**
I do not simply click outside the window, I click the Done button to make sure I saved my settings.

As long as I don't reload/restart my Discord these functions work as intended so it's purely an issue regarding the saving of said settings

I've already made an issue about this very same thing before #583 but I cannot remember this problem not being there since I've got the plugin

**Comment by rauenzi** [comment]
Is this still happening for you? I cannot recreate this problem.

**Comment by Enrico9431** [comment]
Seems to still be the case for me, restarted Discord after enabling them and they're disabled again

**Comment by rauenzi** [comment]
Hmmm can you try deleting your BFRedux settings file? might be the case that something got messed up

**Comment by rauenzi** [comment]
Yeah you're not the first one to report weird issues with the settings file like this, but I just can't determine the cause. I use the same loading/saving system for this plugin as I do for all my plugins yet this one is the only one that has had error reports like this...
