### ISSUE TITLE
BetterFormattingRedux Chat Scrolling Issue

### ISSUE THREAD

**Issue by silent** [rauenzi/BetterDiscordAddons#67]
So when typing this happens
![image](https://i.imgur.com/tIyDygJ.gif)

I disabled all my plugins and as soon as I renabled this and tested this plugin was the one.

**Comment by rauenzi** [comment]
Try turning off your theme and see if it is a conflict between the theme and BFR

**Comment by silent** [comment]
Still happens without theme and custom css.

**Comment by rauenzi** [comment]
Can anyone else reproduce I am unable to

**Comment by rauenzi** [comment]
Still unable to reproduce and have been unable to find anyone else that can.
