### ISSUE TITLE
[Bug] blurNSFW not keeping settings

### ISSUE THREAD

**Issue by GaiaB0t** [rauenzi/BetterDiscordAddons#674]
**Which plugin/theme is this about?**
BlurNSFW v1.0.1(latest afaik)

**Describe the Bug**
BlurNSFW does not automatically enable itself on NSFW channels, nor does it persist manually chosen channels after restarting discord (Ctrl+r *or* full restarts)

**To Reproduce**
have BlurNSFW and zerespluginlibrary installed and enabled, check any nsfw channel or any channel at all
also, enable "blur media" checkbox on any particular channel, verify on any media that it is indeed blurred, then restart discord, and check those same channels you checked before

**Expected Behavior**
for blurNSFW plugin to automatically enable blur media on all nsfw channels, and to also stay enabled after any restarts

**Screenshots**
n/a

**Discord Version**
Stable 154186 (fccec91)

**Additional Context**
n/a

**Comment by Sebas-Re** [comment]
Just tested and yeah, having the same issue.
 Also, I agree with you, "blur media" should be enabled by default on all NSFW channels.

**Comment by SonicMastr** [comment]
You can try the fixed version here #684

**Comment by GaiaB0t** [comment]
> You can try the fixed version here #684

I feel dumb I cant figure out how to download it lol
github moment

**Comment by Sebas-Re** [comment]
> > You can try the fixed version here #684
> 
> I feel dumb I cant figure out how to download it lol github moment

same lmfao

**Comment by Sebas-Re** [comment]
I copied the whole file ( https://github.com/rauenzi/BetterDiscordAddons/blob/fd95b97d2bb9d53ca6b4161804c41220745df640/Plugins/BlurNSFW/BlurNSFW.plugin.js ) and replaced the plugin with that, but I was getting compiling errors at line 217 (apparently a parentesis was missing)

After adding the parentesis to the function, I got this error 

![image](https://user-images.githubusercontent.com/32151264/205148905-eeb6c9c4-6ed9-4b8b-8d7a-166429731d8b.png)

**Comment by Sebas-Re** [comment]
Looks to be working properly now, ty!!

**Comment by rauenzi** [comment]
Closing this as I put in a fix, if the issue persists, feel free to re-open.
