### ISSUE TITLE
[Bug] Role colors not syncing

### ISSUE THREAD

**Issue by a-rasines** [rauenzi/BetterDiscordAddons#676]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Role name colors get shifted when a new one is added to the list

**To Reproduce**
Method 1:
1. Go in a server where you have an exclusive role or you're the only one with that role online. The role must show users appart
2. Go into disconnected mode

Method 2:
1. Go in a server with roles with no online users that show separate to the others
2. Wait for someone with that role to log in
**Expected Behavior**
Role colors show for all roles and they keep their color when a new one appears

**Screenshots**
<img src='https://imgur.com/sW0NT4V.png'>

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
This should now be fixed
