### ISSUE TITLE
[Feature] [DoNotTrack] Disable RPC Server completely

### ISSUE THREAD

**Issue by rollingmoai** [rauenzi/BetterDiscordAddons#677]
**Which plugin/theme is this about?**
DoNotTrack

**Is your feature request related to a problem? Please describe.**
I have two discord clients. The other client is overtaking the RPC, so I would like to disable the RPC server of one of the clients.

**Describe the feature you'd like**
Option to disable the RPC server

**Additional context**
I have been using a [Vencord plugin](https://github.com/Vendicated/Vencord/blob/main/src/plugins/noRPC.ts) which works perfectly, but now I am trying to find a similar functionality in BD.

**Comment by rauenzi** [comment]
This is not possible until BD's structure changes to allow string patching before Discord loads
