### ISSUE TITLE
[Bug] Role colors in right gets shifted when user comes online

### ISSUE THREAD

**Issue by TilenS6** [rauenzi/BetterDiscordAddons#678]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Role colors get shifted up/down when they are added or removed from user menu on right of every server (see screenshots)

**To Reproduce**
Have your top person in a server go to invisible status (he must be the only one who has his role) and every color of roles will get shifted.

**Expected Behavior**
Role colors shifted up/down whenever someone goes online/offline and role group is removed.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/38072381/199706243-92faf6de-1ce5-4a25-95a6-4468e268b048.png)
After (note that one user is no longer present):
![image](https://user-images.githubusercontent.com/38072381/199706357-6ec1dfa9-c296-4847-9b87-385eda1e6a70.png)

**Discord Version**
Stable 155587 (54336ce)

**Comment by rauenzi** [comment]
This should be fixed at latest level
