### ISSUE TITLE
[Bug] HideDisabledEmojis + Zerebospluginlibary

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#679]
**Which plugin/theme is this about?**
HideDisabledEmojis Plugin also your plugin libary

**Describe the Bug**
it dosn´t  hide the unuseable emojis also console give some errors about it and 0pluginlibary

**Exaple Screenshot**
![image](https://user-images.githubusercontent.com/25110093/201253161-65d211ef-5c86-4e66-8021-b0ef9728c5c4.png)

Console errors:
![image](https://user-images.githubusercontent.com/25110093/201253321-605dcb6b-5d5f-4bb9-ae27-6a09c67eeb6b.png)
![image](https://user-images.githubusercontent.com/25110093/201253821-5c814074-fdae-4fca-b633-78fb34b8fe11.png)
![image](https://user-images.githubusercontent.com/25110093/201254565-c9b32928-a227-43de-b3e0-099f5f8ba773.png)

**Discord Version**
![image](https://user-images.githubusercontent.com/25110093/201254404-06c41ecd-1461-448f-abea-7ff6b2ee52e4.png)

**Additional Context**
well: ich hasse discord interne updates hust*

**Comment by Tharki-God** [comment]
fixed the plugin in https://github.com/rauenzi/BetterDiscordAddons/pull/683
