### ISSUE TITLE
[Bug] RoleMembers context menu not working properly

### ISSUE THREAD

**Issue by Sebas-Re** [rauenzi/BetterDiscordAddons#680]
**Which plugin/theme is this about?**
RoleMembers v1.0.1, vanilla theme

**Describe the Bug**
I open the context menu, but nothing happens when I click or hover over an user. Also, the first time I tried it, the UI bugged out and was showing a really broken version of discord's accessibility settings

**To Reproduce**
1. right click a server
2. select Members
3. select a role
4. hover over or click an user
5. nothing happens

**Expected Behavior**
User info should pop up, as the plugin's gifs shows

**Screenshots**
![image](https://user-images.githubusercontent.com/32151264/201444050-dba1c8c9-f91a-4e55-828a-bef420b764dc.png)

**Discord Version**
Stable 158088 (6ae587c) 
Host 1.0.9007 
Windows 10 64-Bit (10.0.19043)

**Comment by FroggyRaven** [comment]
same thing happening to me

**Comment by Soulivan71** [comment]
Role members version 0.1.19
Ptb 189717 (5d9c3fd) Host 1.0.1026 (31656) Windows 10 64-Bit (10.0.19045)
Im having a biggest issue, when I right clic on role members and a role im having this =>
![image](https://user-images.githubusercontent.com/36502190/232248954-08a9fbfd-6d27-406c-b926-8a8a9476031b.png)
