### ISSUE TITLE
[Feature] [PermissionsViewer] Fix the permissions order

### ISSUE THREAD

**Issue by J-URL** [rauenzi/BetterDiscordAddons#681]
**Which plugin/theme is this about?**
PermissionsViewer
**Is your feature request related to a problem? Please describe.**
The permissions list is out of order and makes it harder to easily see what permissions a role/channel has
**Describe the feature you'd like**
Change the order of the permissions to be in the same order as in the Discord channel permission list
like this:
View Channel
Manage Channel
Manage Permissions
Manage Webhooks
Create Invite
Send Messages and Create Posts
Send Messages in Threads and Posts
Create Public Threads
Create Private Threads
Embed Links
Attach Files
Add Reactions
Use External Emoji
Use External Stickers
Mention @everyone, @here, and All Roles
Manage Messages
Manage Threads and Posts
Read Message History
Send Text-to-Speech Messages
Use Application Commands
Connect
Speak
Video
Use Activities
Use Voice Activity
Priority Speaker
Mute Members
Deafen Members
Move Members
Request to Speak
Mention @everyone, @here, and All Roles
Manage Events

**Comment by rauenzi** [comment]
I don't see a good reason to implement it in this specific order. As long as the order is consistent it shouldn't matter. You cannot easily line up the two described menus.
