### ISSUE TITLE
BetterRoleColors [Bug] 

### ISSUE THREAD

**Issue by JasonP-01** [rauenzi/BetterDiscordAddons#685]
**Which plugin/theme is this about?**
 
 BetterRoleColors

**Describe the Bug**
<When highlighting a message with a mention the mention color resets to default (supposed to be there post hover)>

**To Reproduce**
<Mention someone with a role color and make sure the mentions get colored
hover over the message / select the message 
the color should be applied pre-hover and removed post hover (how the bug works)>

**Expected Behavior**
<The color stays what its meant to be an doesnt reset >

**Screenshots**

**Discord Version**
<Stable>

**Additional Context**

**Comment by Zzeyy** [comment]
Happens to me as well.
