### ISSUE TITLE
[Bug] [PermissionsViewer] Right-clicking a server crashes the client

### ISSUE THREAD

**Issue by Galo223344** [rauenzi/BetterDiscordAddons#686]
**Which plugin/theme is this about?**
Permissions Viewer

**Describe the Bug**
Right-clicking a server crashes the Discord client.

**To Reproduce**
Right-click a server icon.

**Expected Behavior**
The regular server context menu should pop up.

**Discord Version**
Stable 163658 (28d41b4)

**Comment by Galo223344** [comment]
Nevermind, it seems to also happen when you right-click a user profile. I guess the problem is with any context menu.

**Comment by ITESaurabh** [comment]
+1

**Comment by SakhJack** [comment]
also happens with `RoleMembers` plugin by Zerebos

**Comment by Michaillebedinskijpc2** [comment]
+1, however it's caused by right-clicking a channel

**Comment by HeadDevDaniel** [comment]
+1, it's also caused by right clicking anything on discord i have noticed

**Comment by master3395** [comment]
I have registered that it is only PermissionViewer and RoleMembers,  that crashes discord when right-clicking.
By the plugins I use.

**Comment by XxUnkn0wnxX** [comment]
Permission Viewer: 0.2.6
crashing when right-clicking on any user.

[Video](https://replay.dropbox.com/share/I8cIleNFo18zaHpV)
[debug.log](https://github.com/rauenzi/BetterDiscordAddons/files/10224191/debug.log)

**Comment by GaiaB0t** [comment]
> I have registered that it is only PermissionViewer and RoleMembers, that crashes discord when right-clicking. By the plugins I use.

also happens with blurNSFW, right clicking a channel causes it for it

**Comment by Equinoxx4978** [comment]
Happens to me with BlurNSFW

**Comment by dawson-vilamaa** [comment]
A temporary fix is to disable the "Context Menu Button" setting. Good thing that's an option.

**Comment by Equinoxx4978** [comment]
BetterDiscord did an update so its fixed now :+1:

**Comment by Technetium1** [comment]
Should be fixed by https://github.com/BetterDiscord/BetterDiscord/releases/tag/v1.8.4
