### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GlitchedSeal** [rauenzi/BetterDiscordAddons#693]
**Which plugin/theme is this about?**

HideDisabledEmojis
**Describe the Bug**

Can't see other servers in the emoji picker after uninstallation in only 1 server. Web version affected too.
**To Reproduce**

 --
**Expected Behavior**

I expected for the emoji picker to return back to original state.
**Screenshots**

![image](https://user-images.githubusercontent.com/76879888/214329063-1f9a28b1-a80b-4826-9440-3af30bdc1f68.png)
**Discord Version**

Stable 169464 (32fe226)
**Additional Context**

I was using BD before the discord update incident. I have tried deleting and reinstalling BD and the plugin but to no avail.

**Comment by GlitchedSeal** [comment]
Its stuck on that server and I can't seem to revert it back to normal.

**Comment by rauenzi** [comment]
If it's still that way after removing everything, then it's not the plugin. The plugin cannot make permanent changes.
