### ISSUE TITLE
[Bug] wrong permissions shown in voice dialog

### ISSUE THREAD

**Issue by Jonz00r** [rauenzi/BetterDiscordAddons#694]
**Which plugin/theme is this about?**
[PermissionsViewer](https://github.com/rauenzi/BetterDiscordAddons/tree/70a173a9e1f7b4ba452db42ab3fecd70b317b684/Plugins/PermissionsViewer)

**Describe the Bug**
Permissions always show my permissions no matter who i click on in voice channels

**To Reproduce**
try and view permissions through voice channel

**Expected Behavior**
show users permissions

**Screenshots**

**Discord Version**
stable

**Additional Context**

**Comment by Soulivan71** [comment]
Same Im using =>
PermissionViewer v0.2.6 
Discord version : Ptb 171780 (179c645) Host 1.0.1023 (29127) Windows 10 64-Bit (10.0.19045)

**Comment by Soulivan71** [comment]
Im using last version im still haivng the issue

**Comment by rauenzi** [comment]
I didn't realize this was about the popouts as opposed to right click. Just pushed a fix for this.

**Comment by Soulivan71** [comment]
Thx for the fix
