### ISSUE TITLE
[Bug] RoleMembers

### ISSUE THREAD

**Issue by Kuju29** [rauenzi/BetterDiscordAddons#696]
**Which plugin/theme is this about?**
plugin RoleMembers 

**Describe the Bug**
Show wrong text position and text color is not visible in theme. ClearVisionv6.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/22098092/216485994-6ba8fb73-80e0-482e-a586-3c38da5d5da3.png)

**Discord Version**
Stable 171621 (b20d67a)
Host 1.0.9010 (29128)
Windows 10 64-Bit (10.0.19045)

**Comment by Soulivan71** [comment]
Appear like this without theme too

**Comment by Fragmansas** [comment]
Same issue, plus missing background on the dropdown menu, as seen in OP's screenshot

**Comment by Cosmic-K9** [comment]
Same issue on the following setup:

Stable 175117 (ebf4be8)
Host 0.0.24
Linux 64-Bit (5.15.0-60-Generic)
Flatpak, installed with betterdiscordctl

**Comment by Soulivan71** [comment]
Hello biggest issue for me :
Role members version 0.1.19
Ptb 189717 (5d9c3fd) Host 1.0.1026 (31656) Windows 10 64-Bit (10.0.19045)
Im having a biggest issue, when I right clic on role members and a role im having this =>
![image](https://user-images.githubusercontent.com/36502190/232248954-08a9fbfd-6d27-406c-b926-8a8a9476031b.png)

**Comment by Soulivan71** [comment]
Thx for the fix
