### ISSUE TITLE
[Bug] HideDisabledEmojis doesn't hide disabled emojis

### ISSUE THREAD

**Issue by samfundev** [rauenzi/BetterDiscordAddons#699]
**Which plugin/theme is this about?**
HideDisabledEmojis

**Describe the Bug**
While the sections are hidden on the left side, the sections are not hidden on the right side of the picker.

**To Reproduce**
Open the emoji picker.

**Expected Behavior**
Disabled emojis should be hidden.

**Screenshots**
![emoji](https://user-images.githubusercontent.com/6759716/221457133-02569293-f4b5-4004-8c25-ec31bf442bc0.gif)

**Discord Version**
Stable

**Comment by Tharki-God** [comment]
the emoji sections still show up on sidebar when changing emoji for status

**Comment by RuochenFu21** [comment]
Can Confirm
