### ISSUE TITLE
[Bug] PermissionsViewer crashing better discord when rightclicking a server/server folder

### ISSUE THREAD

**Issue by wootlink** [rauenzi/BetterDiscordAddons#700]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
PermissionsViewer crashing better discord when rightclicking a server/server folder

**To Reproduce**
right click a server or folder (was trying to mark as read

**Comment by RobotoLev** [comment]
I can confirm that PermissionsViewer plugin is incompatible with the upcoming changes (there is a patched .asar file in BD Discord server; github PR: https://github.com/BetterDiscord/BetterDiscord/pull/1530).

Plugin crashes when right-clicking on the server header.

**Comment by M0REKZ** [comment]
same

**Comment by LewisPattJr** [comment]
Also experiencing this issue.
![image](https://user-images.githubusercontent.com/107158762/221997551-aa7a92b0-744a-4769-b91e-233123132b3e.png)
