### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NxtEb** [rauenzi/BetterDiscordAddons#707]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Role colors in the member list show up incorrectly.

**To Reproduce**
Unknown

**Expected Behavior**
For the correct role color to show up.

**Screenshots**
![Screenshot 2023-03-09 204629](https://user-images.githubusercontent.com/108758471/224203017-47bd0c1d-1551-420a-83c3-58068cb5a3f0.png) ![Screenshot 2023-03-09 204638](https://user-images.githubusercontent.com/108758471/224203055-1918845a-eb8a-47a1-85e9-cf5abd2977c8.png) ![Screenshot 2023-03-09 204734](https://user-images.githubusercontent.com/108758471/224203076-5da76d08-e31f-4a3a-9671-c064b776bbe6.png)

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by rauenzi** [comment]
This was fixed
