### ISSUE TITLE
Better Redux is not working

### ISSUE THREAD

**Issue by CorbsEditor** [rauenzi/BetterDiscordAddons#71]
I enabled it and I am not seeing it!
![image](https://user-images.githubusercontent.com/26362558/45513714-6fd1ad80-b771-11e8-9d3a-a30112b5575f.png)

**Comment by CorbsEditor** [comment]
That isn't working!

**Comment by williamjcm** [comment]
Do you see something like the screenshot below when you enable it ?

![image](https://user-images.githubusercontent.com/13572456/45515001-403d9800-b7a7-11e8-8641-11e996e8d7d9.png)

**Comment by CorbsEditor** [comment]
I had startup errors turned off, I turned it on and: 
![image](https://user-images.githubusercontent.com/26362558/45515230-8c6fe480-b775-11e8-9093-b0890c2063fd.png)
