### ISSUE TITLE
[Bug] Discord crashes when DoNoTrack plugin is installed

### ISSUE THREAD

**Issue by WarningHPB** [rauenzi/BetterDiscordAddons#710]
**Which plugin/theme is this about?**
DoNotTrack

**Describe the Bug**
Discord instantly crashes

**To Reproduce**
Have DoNotTrack installed and in the plugins folder, removing DoNotTrack from the plugin folder resolves the issue, placing the DoNotTrack plugin back into the folder causes Discord to crash again.

**Expected Behavior**
Discord to be useable with the DoNotTrack plugin installed

**Discord Version**
Stable

**Comment by Retr089** [comment]
I can also confirm that with any plugins installed, BetterDiscord will always crash even with repairing.
