### ISSUE TITLE
[Bug] PermissionsViewer doesnt appear anymore

### ISSUE THREAD

**Issue by IdeLuxiz** [rauenzi/BetterDiscordAddons#713]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
Missing "permissions" option when opening details of any channel/user from discord servers

**To Reproduce**
 By opening the details of an specific user or channel

**Expected Behavior**
To appear the option "permissions"

**Screenshots**
![imagen_2023-04-06_210830146](https://user-images.githubusercontent.com/115427530/230515137-9536e6a1-b35a-4b7f-a4df-e957274740b0.png)

**Discord Version**
Stable 187377 (f9a878e)

**Additional Context**
-

**Comment by ArcturusLight1** [comment]
Same issue. Did it get fixed by itself or what?
