### ISSUE TITLE
[Bug] [Enhancement] Plugins and Themes options (BDContextMenu)

### ISSUE THREAD

**Issue by panos78** [rauenzi/BetterDiscordAddons#715]
**Which plugin/theme is this about?**
BDContextMenu

**Describe the Bug**
I don't know if this is a bug or an enhancement.
When we open the context menu, the Plugins and Themes options should be visible if and only if there is at least one plugin or theme respectively.
Now, when there are no plugins or themes (in my case), you get the theme option and when hovering over it you get a black empty line on the right (like a submenu with no entries).

**To Reproduce**
Just navigate through the context menu without having any themes installed.

**Expected Behavior**
As I said already I expect that if there are no themes installed, there should be no option to select themes.

**Screenshots**
![image](https://user-images.githubusercontent.com/3087817/232706209-fef6f9e8-5941-4638-a4c3-e3d8679fd6d5.png)

**Discord Version**
BetterDiscord 1.9.2

**Comment by rauenzi** [comment]
This is intentional. It would be bad UX in my view to omit that section entirely because you can also click on the category to go directly to the page.
