### ISSUE TITLE
[Bug] PermissionsViewer

### ISSUE THREAD

**Issue by izmystic** [rauenzi/BetterDiscordAddons#716]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
Permissions button in context menu shows up for folders

**To Reproduce**
Right click a folder, it will show Permissions

**Expected Behavior**
It shouldn't show Permissions since it isn't a server

**Screenshots**
![](https://cdn.izmystic.dev/images/jnvia0m0.png)

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
This will be available in the next release of the plugin which will happen after #714 is settled
