### ISSUE TITLE
[Feature] Own username toggle

### ISSUE THREAD

**Issue by F0RMATTED** [rauenzi/BetterDiscordAddons#719]
**Which plugin/theme is this about?**
BetterRoleColors

**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
The section in the bottom left, that displays our own username next to the profile picture, mic/sound toggles and account #: Please give us the option to disable coloring here. Certain role colors collide with themes and i couldnt find a way to disable it here.

**Comment by rauenzi** [comment]
These ones right here 
![image](https://user-images.githubusercontent.com/6865942/233507111-0891e52f-27f1-4e12-9f27-0fe7c05ab5b7.png)

**Comment by F0RMATTED** [comment]
I tried that, it does nothing.
