### ISSUE TITLE
[Bug] BetterRoleColor - Wrong color if message is edited

### ISSUE THREAD

**Issue by lumynou5** [rauenzi/BetterDiscordAddons#722]
**Which plugin/theme is this about?**
BetterRoleColor

**Describe the Bug**
If a message that mentioned a user was edited and mention another user now, the color won't be updated.

**To Reproduce**
- Send a message to mention a user.
- Edit the message to mention another with a different role color.

**Expected Behavior**
The color is updated.

**Discord Version**
Stable

**Comment by rauenzi** [comment]
With the way mention coloring is currently done, this is not easily possible. Due to all the memoizing inside of react it's hard to get the up to date info without arbitrary time delays and I'd rather not go down this rabbit whole.
