### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SAINT-ZERO** [rauenzi/BetterDiscordAddons#725]
Plugin "BetterRoleColors"

Plugin settings are not displayed in the discord

The discord was rebooted, but the problem was not solved

<img width="1025" alt="Screenshot 2023-06-06 at 11 31 04" src="https://github.com/rauenzi/BetterDiscordAddons/assets/104649442/e8bfd41e-a43d-4ba4-9dfa-773c0c2d6fff">

Stable (0.0.275 (0.0.275))

**Comment by rauenzi** [comment]
This should be fixed with the newest version of the library
