### ISSUE TITLE
[Bug]  doesnt work anymore

### ISSUE THREAD

**Issue by idkk01** [rauenzi/BetterDiscordAddons#726]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

![image](https://github.com/rauenzi/BetterDiscordAddons/assets/128853441/cd8f20ec-4e08-437e-9c18-bf12af66b6d2)

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

![image](https://github.com/rauenzi/BetterDiscordAddons/assets/128853441/356e9c07-da4b-4de5-809e-5557d2d92118)

**Comment by Salty-Coder** [comment]
Known bug with BetterDiscord since a Discord update.
Fixed in [v1.9.3](https://github.com/BetterDiscord/BetterDiscord/releases/tag/v1.9.3).
https://github.com/BetterDiscord/BetterDiscord/pull/1633
