### ISSUE TITLE
[Bug] RoleMember issue with channel list menu/context menu

### ISSUE THREAD

**Issue by Soulivan71** [rauenzi/BetterDiscordAddons#739]
**Which plugin/theme is this about?**

RoleMember

**Describe the Bug**

Only online members appear when we go on top of a server

**To Reproduce**

Go top of server -> clic on role members -> role
Or go to icon server -> role member -> role

**Expected Behavior**

Have everyone that as the role

**Screenshots**

![image](https://github.com/rauenzi/BetterDiscordAddons/assets/36502190/5bd6beff-7082-4913-955f-bdebb171d074)
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/36502190/25cc8562-b0db-4c0e-bffa-4f061211d407)
And if I go on icon server I can get the members offline

**Discord Version**

Ptb 243840 (822eab2)

**Comment by rauenzi** [comment]
The plugin only shows members that are already loaded into memory and does not force load offline members. This is not something I can reasonably do with the plugin.

**Comment by Soulivan71** [comment]
Oki
