### ISSUE TITLE
[Bug] It just doesn't work anymore

### ISSUE THREAD

**Issue by Zzartoxo** [rauenzi/BetterDiscordAddons#749]
**Which plugin/theme is this about?**
 BetterRoleColors

**Describe the Bug**
 You can activate it and put any options, on !important or not, it simply just doesn't do anything anymore

**To Reproduce**
 Just download it and try it out

**Expected Behavior**
 Well I expected it to work like it used to?

**Screenshots**

**Discord Version**
 The normal one, so I guess stable

**Additional Context**

**Comment by Zzartoxo** [comment]
Nevermind, actually after restarting not only Discord but my whole computer, it somehow works. It never did for monthes though, so it's weird... Anyway sorry for disturbing, love your plugins <3

**Comment by JustOptimize** [comment]
> Nevermind, actually after restarting not only Discord but my whole computer, it somehow works. It never did for monthes though, so it's weird... Anyway sorry for disturbing, love your plugins <3

Close this issue then
