### ISSUE TITLE
ImageToClipboard

### ISSUE THREAD

**Issue by kkthebeast** [rauenzi/BetterDiscordAddons#77]
Not loading, :( 

https://lh3.googleusercontent.com/-4fMb6MkGtho/W8-tdP-M5bI/AAAAAAAAnWI/ipTdrl3kHnkjH-eXeRk3-ULqJEDr1Sz-gCHMYCw/s0/Discord_2018-10-23_18-23-31.png

**Comment by rauenzi** [comment]
That error means you downloaded the wrong thing. Use the download button on the readme for the plugin
