### ISSUE TITLE
PermissionsViewer Bug

### ISSUE THREAD

**Issue by PtrKR** [rauenzi/BetterDiscordAddons#78]
![image](https://user-images.githubusercontent.com/27128153/47961297-fc02a180-e04b-11e8-9279-14fccb1bb14b.png)

**Comment by rauenzi** [comment]
Make sure you have the latest version of the library that goes with it v1.0.4

**Comment by PtrKR** [comment]
Where I found libraries..? https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/ZeresPluginLibrary is 404.

**Comment by rauenzi** [comment]
You must have gotten a really old version if that's the link you have. https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js

**Comment by PtrKR** [comment]
Working successfully after update.. sorry :(

**Comment by rauenzi** [comment]
No problem, you're not the first with that issue. Didn't think that many people actually downloaded the original beta version
