### ISSUE TITLE
[Bug] [EmojiUtilities] In IRC mode, blacklisted emojis are written to a second line, with the first line remaining blank.

### ISSUE THREAD

**Issue by Exodus124** [rauenzi/BetterDiscordAddons#81]
Instead of replacing the emoji with text, this happens: 
![grafik](https://user-images.githubusercontent.com/37227744/51445316-f12ee300-1d03-11e9-9916-444d4837192c.png)

Expected behaviour would be
 that the emojis are written right next to nickname instead of below.

**Comment by rauenzi** [comment]
Yup this is known, when I have extra free time I can look into it
