### ISSUE TITLE
Permission Viewer doesn't show up in context menu anymore

### ISSUE THREAD

**Issue by Liz-chan** [rauenzi/BetterDiscordAddons#83]
Also, it shows this in the console whenever I right click a profile or channel.
![image](https://user-images.githubusercontent.com/18467466/52316433-57189d00-2989-11e9-8e30-3413cfb2b57f.png)
![image](https://user-images.githubusercontent.com/18467466/52316885-9647ed80-298b-11e9-9287-fb3c95b70784.png)

**Comment by SimplyLinn** [comment]
Can confirm, I have the same issue with the latest PV update

**Comment by rauenzi** [comment]
Seems to be an issue with some users having one display name for a component while others have a different name. When I get time I will use prototypes for filter instead of display name.
