### ISSUE TITLE
RoleMembers opens when clicking on a user with the same name of a role

### ISSUE THREAD

**Issue by itsphaze** [rauenzi/BetterDiscordAddons#84]
When clicking on a mention of a user that has the same name of a role, discord will open both the User modal and the RoleMembers model.

Demonstrating video: https://owo.sh/7fa13b.mp4

**Comment by rauenzi** [comment]
Hmm I fixed this bug once towards the inception of the plugin but it seems it returned. Will get to it at some point hopefully.
