### ISSUE TITLE
[Bug] More then one permission in the menu

### ISSUE THREAD

**Issue by FreezeyBlade** [rauenzi/BetterDiscordAddons#87]
IDK if this is on me, or that it just doesnt work, but i have like 12 permission vieuwers xD 
![image](https://user-images.githubusercontent.com/42521301/52671899-96f8fa80-2f1c-11e9-92a3-775309f3117d.png)

**Comment by rauenzi** [comment]
Happens if you enable/disable the plugin multiple times before the promises resolve. Just reload

**Comment by FreezeyBlade** [comment]
well, itl just tell me this 
![image](https://user-images.githubusercontent.com/42521301/52680830-3973a680-2f3a-11e9-9c84-de50a5738006.png)

**Comment by rauenzi** [comment]
>Just reload

Please do this, that error doesn't pop up during reload.
