### ISSUE TITLE
Still having the same isseu ,

### ISSUE THREAD

**Issue by FreezeyBlade** [rauenzi/BetterDiscordAddons#88]
![image](https://user-images.githubusercontent.com/42521301/52981409-e4bfa800-33df-11e9-89da-d104d50d3955.png)

FYI i use Enhanced and Betterdiscord at the same time, can that be the isseu?

**Comment by rauenzi** [comment]
You should not do that, I do not support that setup

**Comment by FreezeyBlade** [comment]
deleting it out of enhanced discord folder, and only putting it in better discord, doesnt fix it too, so i have to de-install better discord?

**Comment by Inve1951** [comment]
How about you use the BD plugin with BD and get rid of ED instead....

**Comment by FreezeyBlade** [comment]
> How about you use the BD plugin with BD and get rid of ED instead....

how bout you dont say anything cuz you aint a dev?

**Comment by Inve1951** [comment]
I don't see how that's relevant. You are quite wrong too.
I'm a BD plugin dev and have a deep understanding of BD and it's codebase.

**Comment by FreezeyBlade** [comment]
> I don't see how that's relevant. You are quite wrong too.
> I'm a BD plugin dev and have a deep understanding of BD and it's codebase.

i take back what i said, i just think BD is all over the place, while ED has more things you can do on your own

**Comment by Inve1951** [comment]
For ED support you are in the wrong place and Zere made it pretty clear that he doesn't support ED/BBD cross setups.
>You should not do that, I do not support that setup

**Comment by FreezeyBlade** [comment]
many BD plugins support ED though... kinda sad that this one doesnt, but thanks anyway

**Comment by Inve1951** [comment]
It's the other way around. ED supports BD plugins so they might just work on ED out of the box.
