### ISSUE TITLE
Role Members crash on opening user under role

### ISSUE THREAD

**Issue by master3395** [rauenzi/BetterDiscordAddons#91]
I went to go use role members and when I clicked on someone to check their profile, Discord crashed. This also happened in other servers and other roles as well.
![image](https://user-images.githubusercontent.com/4199669/53577762-8bd9d780-3b76-11e9-9321-0bdfd68617a5.png)

**Comment by rauenzi** [comment]
Update your plugin

**Comment by master3395** [comment]
That error, isn't related to this.
The other one, was right clicking.
This one is "clicking" the user it self.
When you first click the role.
Then click the user (boom error)

**Comment by rauenzi** [comment]
That should have been fixed as well. What versions of plugin, lib and discord are you using?

**Comment by master3395** [comment]
![image](https://user-images.githubusercontent.com/4199669/53596297-b9874680-3b9f-11e9-8399-ebf3d71ec57e.png)
![image](https://user-images.githubusercontent.com/4199669/53596266-a5dbe000-3b9f-11e9-80a4-9a34aa01af2c.png)
![image](https://user-images.githubusercontent.com/4199669/53596356-d3c12480-3b9f-11e9-9d8b-52a89dfffbf2.png)

**Comment by TheDarkBomber** [comment]
I also have this issue. I have updated, and therefore Discord doesn't crash when right clicking on a server, but it does crash when clicking on a role, and then clicking on a user from the member list that RoleMembers shows. I use Discord host 0.0.302, BD v0.3.0; BBD v0.2.7, RoleMembers v0.1.5 @rauenzi

**Comment by Liz-chan** [comment]
I also have the issue, just found it now.

**Comment by intrnl** [comment]
Can you share more details such as the error log on console? Just saying that it crashes doesn't *really* help.

**Comment by Liz-chan** [comment]
Got this

![image](https://user-images.githubusercontent.com/18467466/53679794-862be100-3c9f-11e9-8422-d9c82be62fff.png)
