### ISSUE TITLE
Suggestion Colored Role mentions

### ISSUE THREAD

**Issue by pupnewfster** [rauenzi/BetterDiscordAddons#92]
I know that the addon BetterRoleColors supports coloring the mentions for users to match their role in the server, but it would be nice to have it when you mention a role that mention is the color of the role if it has one.

**Comment by rauenzi** [comment]
I think discord already does this

**Comment by TheDarkBomber** [comment]
That's already a feature natively in Discord.

**Comment by pupnewfster** [comment]
That is what I had thought but it doesn't seem to be working for me.

**Comment by pupnewfster** [comment]
I figured it out, it was my theme that for some reason didn't have role colors
