### ISSUE TITLE
[Feature] [BetterFormatingRedux] arrow with white theme

### ISSUE THREAD

**Issue by yorik100** [rauenzi/BetterDiscordAddons#99]
It's invisible if you use white theme

**Comment by rauenzi** [comment]
This was implemented!

**Comment by yorik100** [comment]
Still impossible to see with white theme

**Comment by rauenzi** [comment]
It looks about as visible as every other UI element to me:

![Image](https://i.zackrauen.com/Un33aI.png)

I also made the main bar compatible with light theme:
![Image2](https://i.zackrauen.com/YEYNcn.png)

**Comment by rauenzi** [comment]
Well I am open to suggestions, but I used discord's own colors for it
